// Schema input SHA-256: 0924453c55999993509bfe8bc346955d2b1e731078df2ae1c7ccb6054fa02d7f
// @generated by kr-kafka-codegen. Do not edit.
use crate::{
    generated::*,
    wire::{Error, Reader, Writer},
};
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ApiVersion {
    pub api_key: i16,
    pub version: i16,
    pub request_header_version: i16,
    pub response_header_version: i16,
}
pub const SUPPORTED: &[ApiVersion] = &[
    ApiVersion {
        api_key: 18,
        version: 0,
        request_header_version: 1,
        response_header_version: 0,
    },
    ApiVersion {
        api_key: 18,
        version: 3,
        request_header_version: 2,
        response_header_version: 0,
    },
    ApiVersion {
        api_key: 3,
        version: 12,
        request_header_version: 2,
        response_header_version: 1,
    },
    ApiVersion {
        api_key: 1,
        version: 13,
        request_header_version: 2,
        response_header_version: 1,
    },
    ApiVersion {
        api_key: 0,
        version: 9,
        request_header_version: 2,
        response_header_version: 1,
    },
    ApiVersion {
        api_key: 0,
        version: 10,
        request_header_version: 2,
        response_header_version: 1,
    },
    ApiVersion {
        api_key: 0,
        version: 11,
        request_header_version: 2,
        response_header_version: 1,
    },
    ApiVersion {
        api_key: 0,
        version: 12,
        request_header_version: 2,
        response_header_version: 1,
    },
    ApiVersion {
        api_key: 0,
        version: 13,
        request_header_version: 2,
        response_header_version: 1,
    },
    ApiVersion {
        api_key: 22,
        version: 4,
        request_header_version: 2,
        response_header_version: 1,
    },
    ApiVersion {
        api_key: 17,
        version: 1,
        request_header_version: 1,
        response_header_version: 0,
    },
    ApiVersion {
        api_key: 36,
        version: 2,
        request_header_version: 2,
        response_header_version: 1,
    },
];
pub fn api_version(api_key: i16, version: i16) -> Result<&'static ApiVersion, Error> {
    SUPPORTED
        .iter()
        .find(|v| v.api_key == api_key && v.version == version)
        .ok_or(Error::UnsupportedVersion { api_key, version })
}
#[derive(Debug, Clone)]
pub enum Request<'a> {
    ApiVersionsRequest(api_versions_request::View<'a>),
    MetadataRequest(metadata_request::View<'a>),
    FetchRequest(fetch_request::View<'a>),
    ProduceRequest(produce_request::View<'a>),
    InitProducerIdRequest(init_producer_id_request::View<'a>),
    SaslHandshakeRequest(sasl_handshake_request::View<'a>),
    SaslAuthenticateRequest(sasl_authenticate_request::View<'a>),
}
impl<'a> Request<'a> {
    pub const fn api_key(&self) -> i16 {
        match self {
            Self::ApiVersionsRequest(_) => 18,
            Self::MetadataRequest(_) => 3,
            Self::FetchRequest(_) => 1,
            Self::ProduceRequest(_) => 0,
            Self::InitProducerIdRequest(_) => 22,
            Self::SaslHandshakeRequest(_) => 17,
            Self::SaslAuthenticateRequest(_) => 36,
        }
    }
    pub fn read_body(r: &mut Reader<'a>, api_key: i16, version: i16) -> Result<Self, Error> {
        api_version(api_key, version)?;
        match api_key {
            18 => Ok(Self::ApiVersionsRequest(api_versions_request::View::read(
                r, version,
            )?)),
            3 => Ok(Self::MetadataRequest(metadata_request::View::read(
                r, version,
            )?)),
            1 => Ok(Self::FetchRequest(fetch_request::View::read(r, version)?)),
            0 => Ok(Self::ProduceRequest(produce_request::View::read(
                r, version,
            )?)),
            22 => Ok(Self::InitProducerIdRequest(
                init_producer_id_request::View::read(r, version)?,
            )),
            17 => Ok(Self::SaslHandshakeRequest(
                sasl_handshake_request::View::read(r, version)?,
            )),
            36 => Ok(Self::SaslAuthenticateRequest(
                sasl_authenticate_request::View::read(r, version)?,
            )),
            _ => Err(Error::UnsupportedVersion { api_key, version }),
        }
    }
    pub fn write_body(&self, w: &mut Writer<'a>, version: i16) -> Result<(), Error> {
        api_version(self.api_key(), version)?;
        match self {
            Self::ApiVersionsRequest(value) => value.write(w, version),
            Self::MetadataRequest(value) => value.write(w, version),
            Self::FetchRequest(value) => value.write(w, version),
            Self::ProduceRequest(value) => value.write(w, version),
            Self::InitProducerIdRequest(value) => value.write(w, version),
            Self::SaslHandshakeRequest(value) => value.write(w, version),
            Self::SaslAuthenticateRequest(value) => value.write(w, version),
        }
    }
}
#[derive(Debug, Clone)]
pub enum Response<'a> {
    ApiVersionsResponse(api_versions_response::View<'a>),
    MetadataResponse(metadata_response::View<'a>),
    FetchResponse(fetch_response::View<'a>),
    ProduceResponse(produce_response::View<'a>),
    InitProducerIdResponse(init_producer_id_response::View<'a>),
    SaslHandshakeResponse(sasl_handshake_response::View<'a>),
    SaslAuthenticateResponse(sasl_authenticate_response::View<'a>),
}
impl<'a> Response<'a> {
    pub const fn api_key(&self) -> i16 {
        match self {
            Self::ApiVersionsResponse(_) => 18,
            Self::MetadataResponse(_) => 3,
            Self::FetchResponse(_) => 1,
            Self::ProduceResponse(_) => 0,
            Self::InitProducerIdResponse(_) => 22,
            Self::SaslHandshakeResponse(_) => 17,
            Self::SaslAuthenticateResponse(_) => 36,
        }
    }
    pub fn read_body(r: &mut Reader<'a>, api_key: i16, version: i16) -> Result<Self, Error> {
        api_version(api_key, version)?;
        match api_key {
            18 => Ok(Self::ApiVersionsResponse(
                api_versions_response::View::read(r, version)?,
            )),
            3 => Ok(Self::MetadataResponse(metadata_response::View::read(
                r, version,
            )?)),
            1 => Ok(Self::FetchResponse(fetch_response::View::read(r, version)?)),
            0 => Ok(Self::ProduceResponse(produce_response::View::read(
                r, version,
            )?)),
            22 => Ok(Self::InitProducerIdResponse(
                init_producer_id_response::View::read(r, version)?,
            )),
            17 => Ok(Self::SaslHandshakeResponse(
                sasl_handshake_response::View::read(r, version)?,
            )),
            36 => Ok(Self::SaslAuthenticateResponse(
                sasl_authenticate_response::View::read(r, version)?,
            )),
            _ => Err(Error::UnsupportedVersion { api_key, version }),
        }
    }
    pub fn write_body(&self, w: &mut Writer<'a>, version: i16) -> Result<(), Error> {
        api_version(self.api_key(), version)?;
        match self {
            Self::ApiVersionsResponse(value) => value.write(w, version),
            Self::MetadataResponse(value) => value.write(w, version),
            Self::FetchResponse(value) => value.write(w, version),
            Self::ProduceResponse(value) => value.write(w, version),
            Self::InitProducerIdResponse(value) => value.write(w, version),
            Self::SaslHandshakeResponse(value) => value.write(w, version),
            Self::SaslAuthenticateResponse(value) => value.write(w, version),
        }
    }
}
