// Generated by jextract

package io.krkafka.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     uint32_t struct_size;
 *     uint32_t kind;
 *     uint64_t token;
 *     uint64_t user_token;
 *     uint32_t topic;
 *     uint8_t topic_id[16];
 *     int32_t partition;
 *     uint32_t outcome;
 *     uint32_t reason;
 *     int64_t base_offset;
 *     uint32_t base_offset_present;
 *     int64_t timestamp_ms;
 *     uint32_t timestamp_present;
 *     uint32_t attempts;
 *     uint32_t count;
 * }
 * }
 */
public class kr_event {

    kr_event() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        kr_kafka_h.C_INT.withName("struct_size"),
        kr_kafka_h.C_INT.withName("kind"),
        kr_kafka_h.C_LONG_LONG.withName("token"),
        kr_kafka_h.C_LONG_LONG.withName("user_token"),
        kr_kafka_h.C_INT.withName("topic"),
        MemoryLayout.sequenceLayout(16, kr_kafka_h.C_CHAR).withName("topic_id"),
        kr_kafka_h.C_INT.withName("partition"),
        kr_kafka_h.C_INT.withName("outcome"),
        kr_kafka_h.C_INT.withName("reason"),
        kr_kafka_h.C_LONG_LONG.withName("base_offset"),
        kr_kafka_h.C_INT.withName("base_offset_present"),
        MemoryLayout.paddingLayout(4),
        kr_kafka_h.C_LONG_LONG.withName("timestamp_ms"),
        kr_kafka_h.C_INT.withName("timestamp_present"),
        kr_kafka_h.C_INT.withName("attempts"),
        kr_kafka_h.C_INT.withName("count"),
        MemoryLayout.paddingLayout(4)
    ).withName("$anon$90:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt struct_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("struct_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final OfInt struct_size$layout() {
        return struct_size$LAYOUT;
    }

    private static final long struct_size$OFFSET = $LAYOUT.byteOffset(groupElement("struct_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final long struct_size$offset() {
        return struct_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static int struct_size(MemorySegment struct) {
        return struct.get(struct_size$LAYOUT, struct_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static void struct_size(MemorySegment struct, int fieldValue) {
        struct.set(struct_size$LAYOUT, struct_size$OFFSET, fieldValue);
    }

    private static final OfInt kind$LAYOUT = (OfInt)$LAYOUT.select(groupElement("kind"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t kind
     * }
     */
    public static final OfInt kind$layout() {
        return kind$LAYOUT;
    }

    private static final long kind$OFFSET = $LAYOUT.byteOffset(groupElement("kind"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t kind
     * }
     */
    public static final long kind$offset() {
        return kind$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t kind
     * }
     */
    public static int kind(MemorySegment struct) {
        return struct.get(kind$LAYOUT, kind$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t kind
     * }
     */
    public static void kind(MemorySegment struct, int fieldValue) {
        struct.set(kind$LAYOUT, kind$OFFSET, fieldValue);
    }

    private static final OfLong token$LAYOUT = (OfLong)$LAYOUT.select(groupElement("token"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t token
     * }
     */
    public static final OfLong token$layout() {
        return token$LAYOUT;
    }

    private static final long token$OFFSET = $LAYOUT.byteOffset(groupElement("token"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t token
     * }
     */
    public static final long token$offset() {
        return token$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t token
     * }
     */
    public static long token(MemorySegment struct) {
        return struct.get(token$LAYOUT, token$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t token
     * }
     */
    public static void token(MemorySegment struct, long fieldValue) {
        struct.set(token$LAYOUT, token$OFFSET, fieldValue);
    }

    private static final OfLong user_token$LAYOUT = (OfLong)$LAYOUT.select(groupElement("user_token"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t user_token
     * }
     */
    public static final OfLong user_token$layout() {
        return user_token$LAYOUT;
    }

    private static final long user_token$OFFSET = $LAYOUT.byteOffset(groupElement("user_token"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t user_token
     * }
     */
    public static final long user_token$offset() {
        return user_token$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t user_token
     * }
     */
    public static long user_token(MemorySegment struct) {
        return struct.get(user_token$LAYOUT, user_token$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t user_token
     * }
     */
    public static void user_token(MemorySegment struct, long fieldValue) {
        struct.set(user_token$LAYOUT, user_token$OFFSET, fieldValue);
    }

    private static final OfInt topic$LAYOUT = (OfInt)$LAYOUT.select(groupElement("topic"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t topic
     * }
     */
    public static final OfInt topic$layout() {
        return topic$LAYOUT;
    }

    private static final long topic$OFFSET = $LAYOUT.byteOffset(groupElement("topic"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t topic
     * }
     */
    public static final long topic$offset() {
        return topic$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t topic
     * }
     */
    public static int topic(MemorySegment struct) {
        return struct.get(topic$LAYOUT, topic$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t topic
     * }
     */
    public static void topic(MemorySegment struct, int fieldValue) {
        struct.set(topic$LAYOUT, topic$OFFSET, fieldValue);
    }

    private static final SequenceLayout topic_id$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("topic_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t topic_id[16]
     * }
     */
    public static final SequenceLayout topic_id$layout() {
        return topic_id$LAYOUT;
    }

    private static final long topic_id$OFFSET = $LAYOUT.byteOffset(groupElement("topic_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t topic_id[16]
     * }
     */
    public static final long topic_id$offset() {
        return topic_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t topic_id[16]
     * }
     */
    public static MemorySegment topic_id(MemorySegment struct) {
        return struct.asSlice(topic_id$OFFSET, topic_id$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t topic_id[16]
     * }
     */
    public static void topic_id(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, topic_id$OFFSET, topic_id$LAYOUT.byteSize());
    }

    private static long[] topic_id$DIMS = { 16 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint8_t topic_id[16]
     * }
     */
    public static long[] topic_id$dimensions() {
        return topic_id$DIMS;
    }
    private static final VarHandle topic_id$ELEM_HANDLE = topic_id$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint8_t topic_id[16]
     * }
     */
    public static byte topic_id(MemorySegment struct, long index0) {
        return (byte)topic_id$ELEM_HANDLE.get(struct, topic_id$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint8_t topic_id[16]
     * }
     */
    public static void topic_id(MemorySegment struct, long index0, byte fieldValue) {
        topic_id$ELEM_HANDLE.set(struct, topic_id$OFFSET, index0, fieldValue);
    }

    private static final OfInt partition$LAYOUT = (OfInt)$LAYOUT.select(groupElement("partition"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t partition
     * }
     */
    public static final OfInt partition$layout() {
        return partition$LAYOUT;
    }

    private static final long partition$OFFSET = $LAYOUT.byteOffset(groupElement("partition"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t partition
     * }
     */
    public static final long partition$offset() {
        return partition$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t partition
     * }
     */
    public static int partition(MemorySegment struct) {
        return struct.get(partition$LAYOUT, partition$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t partition
     * }
     */
    public static void partition(MemorySegment struct, int fieldValue) {
        struct.set(partition$LAYOUT, partition$OFFSET, fieldValue);
    }

    private static final OfInt outcome$LAYOUT = (OfInt)$LAYOUT.select(groupElement("outcome"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t outcome
     * }
     */
    public static final OfInt outcome$layout() {
        return outcome$LAYOUT;
    }

    private static final long outcome$OFFSET = $LAYOUT.byteOffset(groupElement("outcome"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t outcome
     * }
     */
    public static final long outcome$offset() {
        return outcome$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t outcome
     * }
     */
    public static int outcome(MemorySegment struct) {
        return struct.get(outcome$LAYOUT, outcome$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t outcome
     * }
     */
    public static void outcome(MemorySegment struct, int fieldValue) {
        struct.set(outcome$LAYOUT, outcome$OFFSET, fieldValue);
    }

    private static final OfInt reason$LAYOUT = (OfInt)$LAYOUT.select(groupElement("reason"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t reason
     * }
     */
    public static final OfInt reason$layout() {
        return reason$LAYOUT;
    }

    private static final long reason$OFFSET = $LAYOUT.byteOffset(groupElement("reason"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t reason
     * }
     */
    public static final long reason$offset() {
        return reason$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t reason
     * }
     */
    public static int reason(MemorySegment struct) {
        return struct.get(reason$LAYOUT, reason$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t reason
     * }
     */
    public static void reason(MemorySegment struct, int fieldValue) {
        struct.set(reason$LAYOUT, reason$OFFSET, fieldValue);
    }

    private static final OfLong base_offset$LAYOUT = (OfLong)$LAYOUT.select(groupElement("base_offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t base_offset
     * }
     */
    public static final OfLong base_offset$layout() {
        return base_offset$LAYOUT;
    }

    private static final long base_offset$OFFSET = $LAYOUT.byteOffset(groupElement("base_offset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t base_offset
     * }
     */
    public static final long base_offset$offset() {
        return base_offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t base_offset
     * }
     */
    public static long base_offset(MemorySegment struct) {
        return struct.get(base_offset$LAYOUT, base_offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t base_offset
     * }
     */
    public static void base_offset(MemorySegment struct, long fieldValue) {
        struct.set(base_offset$LAYOUT, base_offset$OFFSET, fieldValue);
    }

    private static final OfInt base_offset_present$LAYOUT = (OfInt)$LAYOUT.select(groupElement("base_offset_present"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t base_offset_present
     * }
     */
    public static final OfInt base_offset_present$layout() {
        return base_offset_present$LAYOUT;
    }

    private static final long base_offset_present$OFFSET = $LAYOUT.byteOffset(groupElement("base_offset_present"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t base_offset_present
     * }
     */
    public static final long base_offset_present$offset() {
        return base_offset_present$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t base_offset_present
     * }
     */
    public static int base_offset_present(MemorySegment struct) {
        return struct.get(base_offset_present$LAYOUT, base_offset_present$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t base_offset_present
     * }
     */
    public static void base_offset_present(MemorySegment struct, int fieldValue) {
        struct.set(base_offset_present$LAYOUT, base_offset_present$OFFSET, fieldValue);
    }

    private static final OfLong timestamp_ms$LAYOUT = (OfLong)$LAYOUT.select(groupElement("timestamp_ms"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t timestamp_ms
     * }
     */
    public static final OfLong timestamp_ms$layout() {
        return timestamp_ms$LAYOUT;
    }

    private static final long timestamp_ms$OFFSET = $LAYOUT.byteOffset(groupElement("timestamp_ms"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t timestamp_ms
     * }
     */
    public static final long timestamp_ms$offset() {
        return timestamp_ms$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t timestamp_ms
     * }
     */
    public static long timestamp_ms(MemorySegment struct) {
        return struct.get(timestamp_ms$LAYOUT, timestamp_ms$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t timestamp_ms
     * }
     */
    public static void timestamp_ms(MemorySegment struct, long fieldValue) {
        struct.set(timestamp_ms$LAYOUT, timestamp_ms$OFFSET, fieldValue);
    }

    private static final OfInt timestamp_present$LAYOUT = (OfInt)$LAYOUT.select(groupElement("timestamp_present"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t timestamp_present
     * }
     */
    public static final OfInt timestamp_present$layout() {
        return timestamp_present$LAYOUT;
    }

    private static final long timestamp_present$OFFSET = $LAYOUT.byteOffset(groupElement("timestamp_present"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t timestamp_present
     * }
     */
    public static final long timestamp_present$offset() {
        return timestamp_present$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t timestamp_present
     * }
     */
    public static int timestamp_present(MemorySegment struct) {
        return struct.get(timestamp_present$LAYOUT, timestamp_present$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t timestamp_present
     * }
     */
    public static void timestamp_present(MemorySegment struct, int fieldValue) {
        struct.set(timestamp_present$LAYOUT, timestamp_present$OFFSET, fieldValue);
    }

    private static final OfInt attempts$LAYOUT = (OfInt)$LAYOUT.select(groupElement("attempts"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t attempts
     * }
     */
    public static final OfInt attempts$layout() {
        return attempts$LAYOUT;
    }

    private static final long attempts$OFFSET = $LAYOUT.byteOffset(groupElement("attempts"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t attempts
     * }
     */
    public static final long attempts$offset() {
        return attempts$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t attempts
     * }
     */
    public static int attempts(MemorySegment struct) {
        return struct.get(attempts$LAYOUT, attempts$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t attempts
     * }
     */
    public static void attempts(MemorySegment struct, int fieldValue) {
        struct.set(attempts$LAYOUT, attempts$OFFSET, fieldValue);
    }

    private static final OfInt count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t count
     * }
     */
    public static final OfInt count$layout() {
        return count$LAYOUT;
    }

    private static final long count$OFFSET = $LAYOUT.byteOffset(groupElement("count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t count
     * }
     */
    public static final long count$offset() {
        return count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t count
     * }
     */
    public static int count(MemorySegment struct) {
        return struct.get(count$LAYOUT, count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t count
     * }
     */
    public static void count(MemorySegment struct, int fieldValue) {
        struct.set(count$LAYOUT, count$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

