// Generated by jextract

package io.krkafka.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     uint32_t struct_size;
 *     kr_span key;
 *     kr_span value;
 *     uint32_t value_is_null;
 * }
 * }
 */
public class kr_header {

    kr_header() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        kr_kafka_h.C_INT.withName("struct_size"),
        MemoryLayout.paddingLayout(4),
        kr_span.layout().withName("key"),
        kr_span.layout().withName("value"),
        kr_kafka_h.C_INT.withName("value_is_null"),
        MemoryLayout.paddingLayout(4)
    ).withName("$anon$81:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt struct_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("struct_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final OfInt struct_size$layout() {
        return struct_size$LAYOUT;
    }

    private static final long struct_size$OFFSET = $LAYOUT.byteOffset(groupElement("struct_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final long struct_size$offset() {
        return struct_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static int struct_size(MemorySegment struct) {
        return struct.get(struct_size$LAYOUT, struct_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static void struct_size(MemorySegment struct, int fieldValue) {
        struct.set(struct_size$LAYOUT, struct_size$OFFSET, fieldValue);
    }

    private static final GroupLayout key$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("key"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * kr_span key
     * }
     */
    public static final GroupLayout key$layout() {
        return key$LAYOUT;
    }

    private static final long key$OFFSET = $LAYOUT.byteOffset(groupElement("key"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * kr_span key
     * }
     */
    public static final long key$offset() {
        return key$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * kr_span key
     * }
     */
    public static MemorySegment key(MemorySegment struct) {
        return struct.asSlice(key$OFFSET, key$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * kr_span key
     * }
     */
    public static void key(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, key$OFFSET, key$LAYOUT.byteSize());
    }

    private static final GroupLayout value$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("value"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * kr_span value
     * }
     */
    public static final GroupLayout value$layout() {
        return value$LAYOUT;
    }

    private static final long value$OFFSET = $LAYOUT.byteOffset(groupElement("value"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * kr_span value
     * }
     */
    public static final long value$offset() {
        return value$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * kr_span value
     * }
     */
    public static MemorySegment value(MemorySegment struct) {
        return struct.asSlice(value$OFFSET, value$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * kr_span value
     * }
     */
    public static void value(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, value$OFFSET, value$LAYOUT.byteSize());
    }

    private static final OfInt value_is_null$LAYOUT = (OfInt)$LAYOUT.select(groupElement("value_is_null"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t value_is_null
     * }
     */
    public static final OfInt value_is_null$layout() {
        return value_is_null$LAYOUT;
    }

    private static final long value_is_null$OFFSET = $LAYOUT.byteOffset(groupElement("value_is_null"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t value_is_null
     * }
     */
    public static final long value_is_null$offset() {
        return value_is_null$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t value_is_null
     * }
     */
    public static int value_is_null(MemorySegment struct) {
        return struct.get(value_is_null$LAYOUT, value_is_null$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t value_is_null
     * }
     */
    public static void value_is_null(MemorySegment struct, int fieldValue) {
        struct.set(value_is_null$LAYOUT, value_is_null$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

