// Generated by jextract

package io.krkafka.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class kr_kafka_h extends kr_kafka_h$shared {

    kr_kafka_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());

    private static final int KR_OK = (int)0L;
    /**
     * {@snippet lang=c :
     * #define KR_OK 0
     * }
     */
    public static int KR_OK() {
        return KR_OK;
    }

    private static class kr_abi_version {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            kr_kafka_h.C_INT    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("kr_abi_version");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * uint32_t kr_abi_version()
     * }
     */
    public static FunctionDescriptor kr_abi_version$descriptor() {
        return kr_abi_version.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * uint32_t kr_abi_version()
     * }
     */
    public static MethodHandle kr_abi_version$handle() {
        return kr_abi_version.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * uint32_t kr_abi_version()
     * }
     */
    public static MemorySegment kr_abi_version$address() {
        return kr_abi_version.ADDR;
    }

    /**
     * {@snippet lang=c :
     * uint32_t kr_abi_version()
     * }
     */
    public static int kr_abi_version() {
        var mh$ = kr_abi_version.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("kr_abi_version");
            }
            return (int)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class kr_producer_config_init {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("kr_producer_config_init");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t kr_producer_config_init(kr_producer_config *, uint32_t struct_size)
     * }
     */
    public static FunctionDescriptor kr_producer_config_init$descriptor() {
        return kr_producer_config_init.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t kr_producer_config_init(kr_producer_config *, uint32_t struct_size)
     * }
     */
    public static MethodHandle kr_producer_config_init$handle() {
        return kr_producer_config_init.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t kr_producer_config_init(kr_producer_config *, uint32_t struct_size)
     * }
     */
    public static MemorySegment kr_producer_config_init$address() {
        return kr_producer_config_init.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t kr_producer_config_init(kr_producer_config *, uint32_t struct_size)
     * }
     */
    public static int kr_producer_config_init(MemorySegment x0, int struct_size) {
        var mh$ = kr_producer_config_init.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("kr_producer_config_init", x0, struct_size);
            }
            return (int)mh$.invokeExact(x0, struct_size);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class kr_producer_create {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("kr_producer_create");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t kr_producer_create(const kr_producer_config *, kr_producer **)
     * }
     */
    public static FunctionDescriptor kr_producer_create$descriptor() {
        return kr_producer_create.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t kr_producer_create(const kr_producer_config *, kr_producer **)
     * }
     */
    public static MethodHandle kr_producer_create$handle() {
        return kr_producer_create.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t kr_producer_create(const kr_producer_config *, kr_producer **)
     * }
     */
    public static MemorySegment kr_producer_create$address() {
        return kr_producer_create.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t kr_producer_create(const kr_producer_config *, kr_producer **)
     * }
     */
    public static int kr_producer_create(MemorySegment x0, MemorySegment x1) {
        var mh$ = kr_producer_create.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("kr_producer_create", x0, x1);
            }
            return (int)mh$.invokeExact(x0, x1);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class kr_topic_open {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("kr_topic_open");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t kr_topic_open(kr_producer *, const char *, uint32_t, uint32_t *)
     * }
     */
    public static FunctionDescriptor kr_topic_open$descriptor() {
        return kr_topic_open.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t kr_topic_open(kr_producer *, const char *, uint32_t, uint32_t *)
     * }
     */
    public static MethodHandle kr_topic_open$handle() {
        return kr_topic_open.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t kr_topic_open(kr_producer *, const char *, uint32_t, uint32_t *)
     * }
     */
    public static MemorySegment kr_topic_open$address() {
        return kr_topic_open.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t kr_topic_open(kr_producer *, const char *, uint32_t, uint32_t *)
     * }
     */
    public static int kr_topic_open(MemorySegment x0, MemorySegment x1, int x2, MemorySegment x3) {
        var mh$ = kr_topic_open.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("kr_topic_open", x0, x1, x2, x3);
            }
            return (int)mh$.invokeExact(x0, x1, x2, x3);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class kr_topic_id {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("kr_topic_id");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t kr_topic_id(kr_producer *, uint32_t, uint8_t id_out[16])
     * }
     */
    public static FunctionDescriptor kr_topic_id$descriptor() {
        return kr_topic_id.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t kr_topic_id(kr_producer *, uint32_t, uint8_t id_out[16])
     * }
     */
    public static MethodHandle kr_topic_id$handle() {
        return kr_topic_id.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t kr_topic_id(kr_producer *, uint32_t, uint8_t id_out[16])
     * }
     */
    public static MemorySegment kr_topic_id$address() {
        return kr_topic_id.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t kr_topic_id(kr_producer *, uint32_t, uint8_t id_out[16])
     * }
     */
    public static int kr_topic_id(MemorySegment x0, int x1, MemorySegment id_out) {
        var mh$ = kr_topic_id.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("kr_topic_id", x0, x1, id_out);
            }
            return (int)mh$.invokeExact(x0, x1, id_out);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class kr_topic_close {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("kr_topic_close");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t kr_topic_close(kr_producer *, uint32_t)
     * }
     */
    public static FunctionDescriptor kr_topic_close$descriptor() {
        return kr_topic_close.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t kr_topic_close(kr_producer *, uint32_t)
     * }
     */
    public static MethodHandle kr_topic_close$handle() {
        return kr_topic_close.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t kr_topic_close(kr_producer *, uint32_t)
     * }
     */
    public static MemorySegment kr_topic_close$address() {
        return kr_topic_close.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t kr_topic_close(kr_producer *, uint32_t)
     * }
     */
    public static int kr_topic_close(MemorySegment x0, int x1) {
        var mh$ = kr_topic_close.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("kr_topic_close", x0, x1);
            }
            return (int)mh$.invokeExact(x0, x1);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class kr_owner_status {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("kr_owner_status");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t kr_owner_status(kr_producer *, uint32_t *status)
     * }
     */
    public static FunctionDescriptor kr_owner_status$descriptor() {
        return kr_owner_status.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t kr_owner_status(kr_producer *, uint32_t *status)
     * }
     */
    public static MethodHandle kr_owner_status$handle() {
        return kr_owner_status.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t kr_owner_status(kr_producer *, uint32_t *status)
     * }
     */
    public static MemorySegment kr_owner_status$address() {
        return kr_owner_status.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t kr_owner_status(kr_producer *, uint32_t *status)
     * }
     */
    public static int kr_owner_status(MemorySegment x0, MemorySegment status) {
        var mh$ = kr_owner_status.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("kr_owner_status", x0, status);
            }
            return (int)mh$.invokeExact(x0, status);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class kr_topic_get_status {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("kr_topic_get_status");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t kr_topic_get_status(kr_producer *, uint32_t topic, kr_topic_status *)
     * }
     */
    public static FunctionDescriptor kr_topic_get_status$descriptor() {
        return kr_topic_get_status.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t kr_topic_get_status(kr_producer *, uint32_t topic, kr_topic_status *)
     * }
     */
    public static MethodHandle kr_topic_get_status$handle() {
        return kr_topic_get_status.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t kr_topic_get_status(kr_producer *, uint32_t topic, kr_topic_status *)
     * }
     */
    public static MemorySegment kr_topic_get_status$address() {
        return kr_topic_get_status.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t kr_topic_get_status(kr_producer *, uint32_t topic, kr_topic_status *)
     * }
     */
    public static int kr_topic_get_status(MemorySegment x0, int topic, MemorySegment x2) {
        var mh$ = kr_topic_get_status.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("kr_topic_get_status", x0, topic, x2);
            }
            return (int)mh$.invokeExact(x0, topic, x2);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class kr_topic_refresh {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("kr_topic_refresh");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t kr_topic_refresh(kr_producer *, uint32_t topic)
     * }
     */
    public static FunctionDescriptor kr_topic_refresh$descriptor() {
        return kr_topic_refresh.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t kr_topic_refresh(kr_producer *, uint32_t topic)
     * }
     */
    public static MethodHandle kr_topic_refresh$handle() {
        return kr_topic_refresh.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t kr_topic_refresh(kr_producer *, uint32_t topic)
     * }
     */
    public static MemorySegment kr_topic_refresh$address() {
        return kr_topic_refresh.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t kr_topic_refresh(kr_producer *, uint32_t topic)
     * }
     */
    public static int kr_topic_refresh(MemorySegment x0, int topic) {
        var mh$ = kr_topic_refresh.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("kr_topic_refresh", x0, topic);
            }
            return (int)mh$.invokeExact(x0, topic);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class kr_metadata_acquire {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("kr_metadata_acquire");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t kr_metadata_acquire(kr_producer *, uint32_t topic, kr_metadata_snapshot *)
     * }
     */
    public static FunctionDescriptor kr_metadata_acquire$descriptor() {
        return kr_metadata_acquire.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t kr_metadata_acquire(kr_producer *, uint32_t topic, kr_metadata_snapshot *)
     * }
     */
    public static MethodHandle kr_metadata_acquire$handle() {
        return kr_metadata_acquire.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t kr_metadata_acquire(kr_producer *, uint32_t topic, kr_metadata_snapshot *)
     * }
     */
    public static MemorySegment kr_metadata_acquire$address() {
        return kr_metadata_acquire.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t kr_metadata_acquire(kr_producer *, uint32_t topic, kr_metadata_snapshot *)
     * }
     */
    public static int kr_metadata_acquire(MemorySegment x0, int topic, MemorySegment x2) {
        var mh$ = kr_metadata_acquire.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("kr_metadata_acquire", x0, topic, x2);
            }
            return (int)mh$.invokeExact(x0, topic, x2);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class kr_metadata_release {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_LONG_LONG
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("kr_metadata_release");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t kr_metadata_release(kr_producer *, uint64_t snapshot)
     * }
     */
    public static FunctionDescriptor kr_metadata_release$descriptor() {
        return kr_metadata_release.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t kr_metadata_release(kr_producer *, uint64_t snapshot)
     * }
     */
    public static MethodHandle kr_metadata_release$handle() {
        return kr_metadata_release.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t kr_metadata_release(kr_producer *, uint64_t snapshot)
     * }
     */
    public static MemorySegment kr_metadata_release$address() {
        return kr_metadata_release.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t kr_metadata_release(kr_producer *, uint64_t snapshot)
     * }
     */
    public static int kr_metadata_release(MemorySegment x0, long snapshot) {
        var mh$ = kr_metadata_release.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("kr_metadata_release", x0, snapshot);
            }
            return (int)mh$.invokeExact(x0, snapshot);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class kr_metadata_brokers {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_LONG_LONG,
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("kr_metadata_brokers");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t kr_metadata_brokers(kr_producer *, uint64_t snapshot, uint32_t start, kr_metadata_broker *, uint32_t capacity, uint32_t *written)
     * }
     */
    public static FunctionDescriptor kr_metadata_brokers$descriptor() {
        return kr_metadata_brokers.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t kr_metadata_brokers(kr_producer *, uint64_t snapshot, uint32_t start, kr_metadata_broker *, uint32_t capacity, uint32_t *written)
     * }
     */
    public static MethodHandle kr_metadata_brokers$handle() {
        return kr_metadata_brokers.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t kr_metadata_brokers(kr_producer *, uint64_t snapshot, uint32_t start, kr_metadata_broker *, uint32_t capacity, uint32_t *written)
     * }
     */
    public static MemorySegment kr_metadata_brokers$address() {
        return kr_metadata_brokers.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t kr_metadata_brokers(kr_producer *, uint64_t snapshot, uint32_t start, kr_metadata_broker *, uint32_t capacity, uint32_t *written)
     * }
     */
    public static int kr_metadata_brokers(MemorySegment x0, long snapshot, int start, MemorySegment x3, int capacity, MemorySegment written) {
        var mh$ = kr_metadata_brokers.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("kr_metadata_brokers", x0, snapshot, start, x3, capacity, written);
            }
            return (int)mh$.invokeExact(x0, snapshot, start, x3, capacity, written);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class kr_metadata_partitions {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_LONG_LONG,
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("kr_metadata_partitions");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t kr_metadata_partitions(kr_producer *, uint64_t snapshot, uint32_t start, kr_metadata_partition *, uint32_t capacity, uint32_t *written)
     * }
     */
    public static FunctionDescriptor kr_metadata_partitions$descriptor() {
        return kr_metadata_partitions.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t kr_metadata_partitions(kr_producer *, uint64_t snapshot, uint32_t start, kr_metadata_partition *, uint32_t capacity, uint32_t *written)
     * }
     */
    public static MethodHandle kr_metadata_partitions$handle() {
        return kr_metadata_partitions.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t kr_metadata_partitions(kr_producer *, uint64_t snapshot, uint32_t start, kr_metadata_partition *, uint32_t capacity, uint32_t *written)
     * }
     */
    public static MemorySegment kr_metadata_partitions$address() {
        return kr_metadata_partitions.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t kr_metadata_partitions(kr_producer *, uint64_t snapshot, uint32_t start, kr_metadata_partition *, uint32_t capacity, uint32_t *written)
     * }
     */
    public static int kr_metadata_partitions(MemorySegment x0, long snapshot, int start, MemorySegment x3, int capacity, MemorySegment written) {
        var mh$ = kr_metadata_partitions.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("kr_metadata_partitions", x0, snapshot, start, x3, capacity, written);
            }
            return (int)mh$.invokeExact(x0, snapshot, start, x3, capacity, written);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class kr_metadata_nodes {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_LONG_LONG,
            kr_kafka_h.C_INT,
            kr_kafka_h.C_INT,
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("kr_metadata_nodes");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t kr_metadata_nodes(kr_producer *, uint64_t snapshot, uint32_t partition, uint32_t kind, uint32_t start, int32_t *, uint32_t capacity, uint32_t *written)
     * }
     */
    public static FunctionDescriptor kr_metadata_nodes$descriptor() {
        return kr_metadata_nodes.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t kr_metadata_nodes(kr_producer *, uint64_t snapshot, uint32_t partition, uint32_t kind, uint32_t start, int32_t *, uint32_t capacity, uint32_t *written)
     * }
     */
    public static MethodHandle kr_metadata_nodes$handle() {
        return kr_metadata_nodes.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t kr_metadata_nodes(kr_producer *, uint64_t snapshot, uint32_t partition, uint32_t kind, uint32_t start, int32_t *, uint32_t capacity, uint32_t *written)
     * }
     */
    public static MemorySegment kr_metadata_nodes$address() {
        return kr_metadata_nodes.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t kr_metadata_nodes(kr_producer *, uint64_t snapshot, uint32_t partition, uint32_t kind, uint32_t start, int32_t *, uint32_t capacity, uint32_t *written)
     * }
     */
    public static int kr_metadata_nodes(MemorySegment x0, long snapshot, int partition, int kind, int start, MemorySegment x5, int capacity, MemorySegment written) {
        var mh$ = kr_metadata_nodes.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("kr_metadata_nodes", x0, snapshot, partition, kind, start, x5, capacity, written);
            }
            return (int)mh$.invokeExact(x0, snapshot, partition, kind, start, x5, capacity, written);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class kr_metadata_string {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_LONG_LONG,
            kr_kafka_h.C_INT,
            kr_kafka_h.C_INT,
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("kr_metadata_string");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t kr_metadata_string(kr_producer *, uint64_t snapshot, uint32_t broker, uint32_t kind, uint32_t start, uint8_t *, uint32_t capacity, uint32_t *written)
     * }
     */
    public static FunctionDescriptor kr_metadata_string$descriptor() {
        return kr_metadata_string.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t kr_metadata_string(kr_producer *, uint64_t snapshot, uint32_t broker, uint32_t kind, uint32_t start, uint8_t *, uint32_t capacity, uint32_t *written)
     * }
     */
    public static MethodHandle kr_metadata_string$handle() {
        return kr_metadata_string.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t kr_metadata_string(kr_producer *, uint64_t snapshot, uint32_t broker, uint32_t kind, uint32_t start, uint8_t *, uint32_t capacity, uint32_t *written)
     * }
     */
    public static MemorySegment kr_metadata_string$address() {
        return kr_metadata_string.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t kr_metadata_string(kr_producer *, uint64_t snapshot, uint32_t broker, uint32_t kind, uint32_t start, uint8_t *, uint32_t capacity, uint32_t *written)
     * }
     */
    public static int kr_metadata_string(MemorySegment x0, long snapshot, int broker, int kind, int start, MemorySegment x5, int capacity, MemorySegment written) {
        var mh$ = kr_metadata_string.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("kr_metadata_string", x0, snapshot, broker, kind, start, x5, capacity, written);
            }
            return (int)mh$.invokeExact(x0, snapshot, broker, kind, start, x5, capacity, written);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class kr_buffer_acquire {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("kr_buffer_acquire");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t kr_buffer_acquire(kr_producer *, uint32_t, uint8_t **, uint64_t *)
     * }
     */
    public static FunctionDescriptor kr_buffer_acquire$descriptor() {
        return kr_buffer_acquire.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t kr_buffer_acquire(kr_producer *, uint32_t, uint8_t **, uint64_t *)
     * }
     */
    public static MethodHandle kr_buffer_acquire$handle() {
        return kr_buffer_acquire.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t kr_buffer_acquire(kr_producer *, uint32_t, uint8_t **, uint64_t *)
     * }
     */
    public static MemorySegment kr_buffer_acquire$address() {
        return kr_buffer_acquire.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t kr_buffer_acquire(kr_producer *, uint32_t, uint8_t **, uint64_t *)
     * }
     */
    public static int kr_buffer_acquire(MemorySegment x0, int x1, MemorySegment x2, MemorySegment x3) {
        var mh$ = kr_buffer_acquire.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("kr_buffer_acquire", x0, x1, x2, x3);
            }
            return (int)mh$.invokeExact(x0, x1, x2, x3);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class kr_buffer_commit {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_LONG_LONG,
            kr_kafka_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("kr_buffer_commit");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t kr_buffer_commit(kr_producer *, uint64_t, uint32_t)
     * }
     */
    public static FunctionDescriptor kr_buffer_commit$descriptor() {
        return kr_buffer_commit.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t kr_buffer_commit(kr_producer *, uint64_t, uint32_t)
     * }
     */
    public static MethodHandle kr_buffer_commit$handle() {
        return kr_buffer_commit.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t kr_buffer_commit(kr_producer *, uint64_t, uint32_t)
     * }
     */
    public static MemorySegment kr_buffer_commit$address() {
        return kr_buffer_commit.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t kr_buffer_commit(kr_producer *, uint64_t, uint32_t)
     * }
     */
    public static int kr_buffer_commit(MemorySegment x0, long x1, int x2) {
        var mh$ = kr_buffer_commit.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("kr_buffer_commit", x0, x1, x2);
            }
            return (int)mh$.invokeExact(x0, x1, x2);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class kr_buffer_release {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_LONG_LONG
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("kr_buffer_release");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t kr_buffer_release(kr_producer *, uint64_t)
     * }
     */
    public static FunctionDescriptor kr_buffer_release$descriptor() {
        return kr_buffer_release.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t kr_buffer_release(kr_producer *, uint64_t)
     * }
     */
    public static MethodHandle kr_buffer_release$handle() {
        return kr_buffer_release.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t kr_buffer_release(kr_producer *, uint64_t)
     * }
     */
    public static MemorySegment kr_buffer_release$address() {
        return kr_buffer_release.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t kr_buffer_release(kr_producer *, uint64_t)
     * }
     */
    public static int kr_buffer_release(MemorySegment x0, long x1) {
        var mh$ = kr_buffer_release.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("kr_buffer_release", x0, x1);
            }
            return (int)mh$.invokeExact(x0, x1);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class kr_lease_register {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_LONG_LONG,
            kr_kafka_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("kr_lease_register");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t kr_lease_register(kr_producer *, const uint8_t *, uint64_t, uint64_t *)
     * }
     */
    public static FunctionDescriptor kr_lease_register$descriptor() {
        return kr_lease_register.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t kr_lease_register(kr_producer *, const uint8_t *, uint64_t, uint64_t *)
     * }
     */
    public static MethodHandle kr_lease_register$handle() {
        return kr_lease_register.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t kr_lease_register(kr_producer *, const uint8_t *, uint64_t, uint64_t *)
     * }
     */
    public static MemorySegment kr_lease_register$address() {
        return kr_lease_register.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t kr_lease_register(kr_producer *, const uint8_t *, uint64_t, uint64_t *)
     * }
     */
    public static int kr_lease_register(MemorySegment x0, MemorySegment x1, long x2, MemorySegment x3) {
        var mh$ = kr_lease_register.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("kr_lease_register", x0, x1, x2, x3);
            }
            return (int)mh$.invokeExact(x0, x1, x2, x3);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class kr_submitv_copy {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("kr_submitv_copy");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * uint32_t kr_submitv_copy(kr_producer *, const kr_record *, uint32_t)
     * }
     */
    public static FunctionDescriptor kr_submitv_copy$descriptor() {
        return kr_submitv_copy.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * uint32_t kr_submitv_copy(kr_producer *, const kr_record *, uint32_t)
     * }
     */
    public static MethodHandle kr_submitv_copy$handle() {
        return kr_submitv_copy.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * uint32_t kr_submitv_copy(kr_producer *, const kr_record *, uint32_t)
     * }
     */
    public static MemorySegment kr_submitv_copy$address() {
        return kr_submitv_copy.ADDR;
    }

    /**
     * {@snippet lang=c :
     * uint32_t kr_submitv_copy(kr_producer *, const kr_record *, uint32_t)
     * }
     */
    public static int kr_submitv_copy(MemorySegment x0, MemorySegment x1, int x2) {
        var mh$ = kr_submitv_copy.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("kr_submitv_copy", x0, x1, x2);
            }
            return (int)mh$.invokeExact(x0, x1, x2);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class kr_submitv_leased {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_LONG_LONG,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("kr_submitv_leased");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * uint32_t kr_submitv_leased(kr_producer *, uint64_t, const kr_record *, uint32_t)
     * }
     */
    public static FunctionDescriptor kr_submitv_leased$descriptor() {
        return kr_submitv_leased.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * uint32_t kr_submitv_leased(kr_producer *, uint64_t, const kr_record *, uint32_t)
     * }
     */
    public static MethodHandle kr_submitv_leased$handle() {
        return kr_submitv_leased.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * uint32_t kr_submitv_leased(kr_producer *, uint64_t, const kr_record *, uint32_t)
     * }
     */
    public static MemorySegment kr_submitv_leased$address() {
        return kr_submitv_leased.ADDR;
    }

    /**
     * {@snippet lang=c :
     * uint32_t kr_submitv_leased(kr_producer *, uint64_t, const kr_record *, uint32_t)
     * }
     */
    public static int kr_submitv_leased(MemorySegment x0, long x1, MemorySegment x2, int x3) {
        var mh$ = kr_submitv_leased.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("kr_submitv_leased", x0, x1, x2, x3);
            }
            return (int)mh$.invokeExact(x0, x1, x2, x3);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class kr_poll_events {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("kr_poll_events");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * uint32_t kr_poll_events(kr_producer *, kr_event *, uint32_t)
     * }
     */
    public static FunctionDescriptor kr_poll_events$descriptor() {
        return kr_poll_events.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * uint32_t kr_poll_events(kr_producer *, kr_event *, uint32_t)
     * }
     */
    public static MethodHandle kr_poll_events$handle() {
        return kr_poll_events.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * uint32_t kr_poll_events(kr_producer *, kr_event *, uint32_t)
     * }
     */
    public static MemorySegment kr_poll_events$address() {
        return kr_poll_events.ADDR;
    }

    /**
     * {@snippet lang=c :
     * uint32_t kr_poll_events(kr_producer *, kr_event *, uint32_t)
     * }
     */
    public static int kr_poll_events(MemorySegment x0, MemorySegment x1, int x2) {
        var mh$ = kr_poll_events.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("kr_poll_events", x0, x1, x2);
            }
            return (int)mh$.invokeExact(x0, x1, x2);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class kr_flush {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("kr_flush");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t kr_flush(kr_producer *, uint64_t *)
     * }
     */
    public static FunctionDescriptor kr_flush$descriptor() {
        return kr_flush.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t kr_flush(kr_producer *, uint64_t *)
     * }
     */
    public static MethodHandle kr_flush$handle() {
        return kr_flush.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t kr_flush(kr_producer *, uint64_t *)
     * }
     */
    public static MemorySegment kr_flush$address() {
        return kr_flush.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t kr_flush(kr_producer *, uint64_t *)
     * }
     */
    public static int kr_flush(MemorySegment x0, MemorySegment x1) {
        var mh$ = kr_flush.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("kr_flush", x0, x1);
            }
            return (int)mh$.invokeExact(x0, x1);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class kr_close {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER,
            kr_kafka_h.C_LONG_LONG
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("kr_close");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t kr_close(kr_producer *, uint64_t timeout_ms)
     * }
     */
    public static FunctionDescriptor kr_close$descriptor() {
        return kr_close.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t kr_close(kr_producer *, uint64_t timeout_ms)
     * }
     */
    public static MethodHandle kr_close$handle() {
        return kr_close.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t kr_close(kr_producer *, uint64_t timeout_ms)
     * }
     */
    public static MemorySegment kr_close$address() {
        return kr_close.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t kr_close(kr_producer *, uint64_t timeout_ms)
     * }
     */
    public static int kr_close(MemorySegment x0, long timeout_ms) {
        var mh$ = kr_close.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("kr_close", x0, timeout_ms);
            }
            return (int)mh$.invokeExact(x0, timeout_ms);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class kr_last_error {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            kr_kafka_h.C_INT,
            kr_kafka_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("kr_last_error");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t kr_last_error(kr_producer *)
     * }
     */
    public static FunctionDescriptor kr_last_error$descriptor() {
        return kr_last_error.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t kr_last_error(kr_producer *)
     * }
     */
    public static MethodHandle kr_last_error$handle() {
        return kr_last_error.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t kr_last_error(kr_producer *)
     * }
     */
    public static MemorySegment kr_last_error$address() {
        return kr_last_error.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t kr_last_error(kr_producer *)
     * }
     */
    public static int kr_last_error(MemorySegment x0) {
        var mh$ = kr_last_error.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("kr_last_error", x0);
            }
            return (int)mh$.invokeExact(x0);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class kr_destroy {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            kr_kafka_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("kr_destroy");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void kr_destroy(kr_producer *)
     * }
     */
    public static FunctionDescriptor kr_destroy$descriptor() {
        return kr_destroy.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void kr_destroy(kr_producer *)
     * }
     */
    public static MethodHandle kr_destroy$handle() {
        return kr_destroy.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void kr_destroy(kr_producer *)
     * }
     */
    public static MemorySegment kr_destroy$address() {
        return kr_destroy.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void kr_destroy(kr_producer *)
     * }
     */
    public static void kr_destroy(MemorySegment x0) {
        var mh$ = kr_destroy.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("kr_destroy", x0);
            }
            mh$.invokeExact(x0);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
    private static final int KR_ABI_VERSION = (int)4L;
    /**
     * {@snippet lang=c :
     * #define KR_ABI_VERSION 4
     * }
     */
    public static int KR_ABI_VERSION() {
        return KR_ABI_VERSION;
    }
    private static final int KR_ERR_INVALID = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define KR_ERR_INVALID -1
     * }
     */
    public static int KR_ERR_INVALID() {
        return KR_ERR_INVALID;
    }
    private static final int KR_ERR_VERSION = (int)-2L;
    /**
     * {@snippet lang=c :
     * #define KR_ERR_VERSION -2
     * }
     */
    public static int KR_ERR_VERSION() {
        return KR_ERR_VERSION;
    }
    private static final int KR_ERR_EXHAUSTED = (int)-3L;
    /**
     * {@snippet lang=c :
     * #define KR_ERR_EXHAUSTED -3
     * }
     */
    public static int KR_ERR_EXHAUSTED() {
        return KR_ERR_EXHAUSTED;
    }
    private static final int KR_ERR_NOT_READY = (int)-4L;
    /**
     * {@snippet lang=c :
     * #define KR_ERR_NOT_READY -4
     * }
     */
    public static int KR_ERR_NOT_READY() {
        return KR_ERR_NOT_READY;
    }
    private static final int KR_ERR_CLOSED = (int)-5L;
    /**
     * {@snippet lang=c :
     * #define KR_ERR_CLOSED -5
     * }
     */
    public static int KR_ERR_CLOSED() {
        return KR_ERR_CLOSED;
    }
    private static final int KR_ERR_UNSUPPORTED = (int)-6L;
    /**
     * {@snippet lang=c :
     * #define KR_ERR_UNSUPPORTED -6
     * }
     */
    public static int KR_ERR_UNSUPPORTED() {
        return KR_ERR_UNSUPPORTED;
    }
    private static final int KR_ERR_FAILED = (int)-7L;
    /**
     * {@snippet lang=c :
     * #define KR_ERR_FAILED -7
     * }
     */
    public static int KR_ERR_FAILED() {
        return KR_ERR_FAILED;
    }
    private static final int KR_ERR_TIMEOUT = (int)-8L;
    /**
     * {@snippet lang=c :
     * #define KR_ERR_TIMEOUT -8
     * }
     */
    public static int KR_ERR_TIMEOUT() {
        return KR_ERR_TIMEOUT;
    }
    private static final int KR_EVENT_DELIVERY = (int)1L;
    /**
     * {@snippet lang=c :
     * #define KR_EVENT_DELIVERY 1
     * }
     */
    public static int KR_EVENT_DELIVERY() {
        return KR_EVENT_DELIVERY;
    }
    private static final int KR_EVENT_INPUT_RELEASED = (int)2L;
    /**
     * {@snippet lang=c :
     * #define KR_EVENT_INPUT_RELEASED 2
     * }
     */
    public static int KR_EVENT_INPUT_RELEASED() {
        return KR_EVENT_INPUT_RELEASED;
    }
    private static final int KR_EVENT_FLUSH_DONE = (int)3L;
    /**
     * {@snippet lang=c :
     * #define KR_EVENT_FLUSH_DONE 3
     * }
     */
    public static int KR_EVENT_FLUSH_DONE() {
        return KR_EVENT_FLUSH_DONE;
    }
    private static final int KR_EVENT_TOPIC_READY = (int)4L;
    /**
     * {@snippet lang=c :
     * #define KR_EVENT_TOPIC_READY 4
     * }
     */
    public static int KR_EVENT_TOPIC_READY() {
        return KR_EVENT_TOPIC_READY;
    }
    private static final int KR_EVENT_TOPIC_FAILED = (int)5L;
    /**
     * {@snippet lang=c :
     * #define KR_EVENT_TOPIC_FAILED 5
     * }
     */
    public static int KR_EVENT_TOPIC_FAILED() {
        return KR_EVENT_TOPIC_FAILED;
    }
    private static final int KR_EVENT_CLOSED = (int)6L;
    /**
     * {@snippet lang=c :
     * #define KR_EVENT_CLOSED 6
     * }
     */
    public static int KR_EVENT_CLOSED() {
        return KR_EVENT_CLOSED;
    }
    private static final int KR_EVENT_FATAL = (int)7L;
    /**
     * {@snippet lang=c :
     * #define KR_EVENT_FATAL 7
     * }
     */
    public static int KR_EVENT_FATAL() {
        return KR_EVENT_FATAL;
    }
    private static final int KR_DELIVERY_ACKED = (int)0L;
    /**
     * {@snippet lang=c :
     * #define KR_DELIVERY_ACKED 0
     * }
     */
    public static int KR_DELIVERY_ACKED() {
        return KR_DELIVERY_ACKED;
    }
    private static final int KR_DELIVERY_NOT_WRITTEN = (int)1L;
    /**
     * {@snippet lang=c :
     * #define KR_DELIVERY_NOT_WRITTEN 1
     * }
     */
    public static int KR_DELIVERY_NOT_WRITTEN() {
        return KR_DELIVERY_NOT_WRITTEN;
    }
    private static final int KR_DELIVERY_UNKNOWN = (int)2L;
    /**
     * {@snippet lang=c :
     * #define KR_DELIVERY_UNKNOWN 2
     * }
     */
    public static int KR_DELIVERY_UNKNOWN() {
        return KR_DELIVERY_UNKNOWN;
    }
    private static final int KR_REASON_NONE = (int)0L;
    /**
     * {@snippet lang=c :
     * #define KR_REASON_NONE 0
     * }
     */
    public static int KR_REASON_NONE() {
        return KR_REASON_NONE;
    }
    private static final int KR_REASON_DEADLINE = (int)1L;
    /**
     * {@snippet lang=c :
     * #define KR_REASON_DEADLINE 1
     * }
     */
    public static int KR_REASON_DEADLINE() {
        return KR_REASON_DEADLINE;
    }
    private static final int KR_REASON_CANCELLED = (int)2L;
    /**
     * {@snippet lang=c :
     * #define KR_REASON_CANCELLED 2
     * }
     */
    public static int KR_REASON_CANCELLED() {
        return KR_REASON_CANCELLED;
    }
    private static final int KR_REASON_TOPIC_DELETED = (int)3L;
    /**
     * {@snippet lang=c :
     * #define KR_REASON_TOPIC_DELETED 3
     * }
     */
    public static int KR_REASON_TOPIC_DELETED() {
        return KR_REASON_TOPIC_DELETED;
    }
    private static final int KR_REASON_TOPIC_RESOLUTION = (int)4L;
    /**
     * {@snippet lang=c :
     * #define KR_REASON_TOPIC_RESOLUTION 4
     * }
     */
    public static int KR_REASON_TOPIC_RESOLUTION() {
        return KR_REASON_TOPIC_RESOLUTION;
    }
    private static final int KR_REASON_PARTITION_FAILED = (int)5L;
    /**
     * {@snippet lang=c :
     * #define KR_REASON_PARTITION_FAILED 5
     * }
     */
    public static int KR_REASON_PARTITION_FAILED() {
        return KR_REASON_PARTITION_FAILED;
    }
    private static final int KR_REASON_COMPRESSED_TOO_LARGE = (int)6L;
    /**
     * {@snippet lang=c :
     * #define KR_REASON_COMPRESSED_TOO_LARGE 6
     * }
     */
    public static int KR_REASON_COMPRESSED_TOO_LARGE() {
        return KR_REASON_COMPRESSED_TOO_LARGE;
    }
    private static final int KR_REASON_INVALID_RECORD = (int)7L;
    /**
     * {@snippet lang=c :
     * #define KR_REASON_INVALID_RECORD 7
     * }
     */
    public static int KR_REASON_INVALID_RECORD() {
        return KR_REASON_INVALID_RECORD;
    }
    private static final int KR_REASON_BROKER_REJECTED = (int)8L;
    /**
     * {@snippet lang=c :
     * #define KR_REASON_BROKER_REJECTED 8
     * }
     */
    public static int KR_REASON_BROKER_REJECTED() {
        return KR_REASON_BROKER_REJECTED;
    }
    private static final int KR_REASON_PRODUCER_FENCED = (int)9L;
    /**
     * {@snippet lang=c :
     * #define KR_REASON_PRODUCER_FENCED 9
     * }
     */
    public static int KR_REASON_PRODUCER_FENCED() {
        return KR_REASON_PRODUCER_FENCED;
    }
    private static final int KR_REASON_PROTOCOL_VIOLATION = (int)10L;
    /**
     * {@snippet lang=c :
     * #define KR_REASON_PROTOCOL_VIOLATION 10
     * }
     */
    public static int KR_REASON_PROTOCOL_VIOLATION() {
        return KR_REASON_PROTOCOL_VIOLATION;
    }
    private static final int KR_REASON_TRANSPORT = (int)11L;
    /**
     * {@snippet lang=c :
     * #define KR_REASON_TRANSPORT 11
     * }
     */
    public static int KR_REASON_TRANSPORT() {
        return KR_REASON_TRANSPORT;
    }
    private static final int KR_REASON_RUNTIME_FAILED = (int)12L;
    /**
     * {@snippet lang=c :
     * #define KR_REASON_RUNTIME_FAILED 12
     * }
     */
    public static int KR_REASON_RUNTIME_FAILED() {
        return KR_REASON_RUNTIME_FAILED;
    }
    private static final int KR_REASON_SEQUENCE_UNRESOLVED = (int)13L;
    /**
     * {@snippet lang=c :
     * #define KR_REASON_SEQUENCE_UNRESOLVED 13
     * }
     */
    public static int KR_REASON_SEQUENCE_UNRESOLVED() {
        return KR_REASON_SEQUENCE_UNRESOLVED;
    }
    private static final int KR_REASON_CLOSED = (int)14L;
    /**
     * {@snippet lang=c :
     * #define KR_REASON_CLOSED 14
     * }
     */
    public static int KR_REASON_CLOSED() {
        return KR_REASON_CLOSED;
    }
    private static final int KR_REASON_RESOURCE_EXHAUSTED = (int)15L;
    /**
     * {@snippet lang=c :
     * #define KR_REASON_RESOURCE_EXHAUSTED 15
     * }
     */
    public static int KR_REASON_RESOURCE_EXHAUSTED() {
        return KR_REASON_RESOURCE_EXHAUSTED;
    }
    private static final int KR_REASON_AUTHENTICATION = (int)16L;
    /**
     * {@snippet lang=c :
     * #define KR_REASON_AUTHENTICATION 16
     * }
     */
    public static int KR_REASON_AUTHENTICATION() {
        return KR_REASON_AUTHENTICATION;
    }
    private static final int KR_OWNER_RUNNING = (int)0L;
    /**
     * {@snippet lang=c :
     * #define KR_OWNER_RUNNING 0
     * }
     */
    public static int KR_OWNER_RUNNING() {
        return KR_OWNER_RUNNING;
    }
    private static final int KR_OWNER_CLOSED = (int)1L;
    /**
     * {@snippet lang=c :
     * #define KR_OWNER_CLOSED 1
     * }
     */
    public static int KR_OWNER_CLOSED() {
        return KR_OWNER_CLOSED;
    }
    private static final int KR_OWNER_ABORTED = (int)2L;
    /**
     * {@snippet lang=c :
     * #define KR_OWNER_ABORTED 2
     * }
     */
    public static int KR_OWNER_ABORTED() {
        return KR_OWNER_ABORTED;
    }
    private static final int KR_TOPIC_RESOLVING = (int)0L;
    /**
     * {@snippet lang=c :
     * #define KR_TOPIC_RESOLVING 0
     * }
     */
    public static int KR_TOPIC_RESOLVING() {
        return KR_TOPIC_RESOLVING;
    }
    private static final int KR_TOPIC_READY = (int)1L;
    /**
     * {@snippet lang=c :
     * #define KR_TOPIC_READY 1
     * }
     */
    public static int KR_TOPIC_READY() {
        return KR_TOPIC_READY;
    }
    private static final int KR_TOPIC_FAILED = (int)2L;
    /**
     * {@snippet lang=c :
     * #define KR_TOPIC_FAILED 2
     * }
     */
    public static int KR_TOPIC_FAILED() {
        return KR_TOPIC_FAILED;
    }
    private static final int KR_TOPIC_DELETED = (int)3L;
    /**
     * {@snippet lang=c :
     * #define KR_TOPIC_DELETED 3
     * }
     */
    public static int KR_TOPIC_DELETED() {
        return KR_TOPIC_DELETED;
    }
    private static final int KR_TOPIC_CLOSING = (int)4L;
    /**
     * {@snippet lang=c :
     * #define KR_TOPIC_CLOSING 4
     * }
     */
    public static int KR_TOPIC_CLOSING() {
        return KR_TOPIC_CLOSING;
    }
    private static final int KR_TOPIC_RETIRED = (int)5L;
    /**
     * {@snippet lang=c :
     * #define KR_TOPIC_RETIRED 5
     * }
     */
    public static int KR_TOPIC_RETIRED() {
        return KR_TOPIC_RETIRED;
    }
    private static final int KR_TOPIC_STALE = (int)6L;
    /**
     * {@snippet lang=c :
     * #define KR_TOPIC_STALE 6
     * }
     */
    public static int KR_TOPIC_STALE() {
        return KR_TOPIC_STALE;
    }
    private static final int KR_METADATA_REPLICAS = (int)0L;
    /**
     * {@snippet lang=c :
     * #define KR_METADATA_REPLICAS 0
     * }
     */
    public static int KR_METADATA_REPLICAS() {
        return KR_METADATA_REPLICAS;
    }
    private static final int KR_METADATA_ISR = (int)1L;
    /**
     * {@snippet lang=c :
     * #define KR_METADATA_ISR 1
     * }
     */
    public static int KR_METADATA_ISR() {
        return KR_METADATA_ISR;
    }
    private static final int KR_METADATA_OFFLINE = (int)2L;
    /**
     * {@snippet lang=c :
     * #define KR_METADATA_OFFLINE 2
     * }
     */
    public static int KR_METADATA_OFFLINE() {
        return KR_METADATA_OFFLINE;
    }
    private static final int KR_METADATA_HOST = (int)0L;
    /**
     * {@snippet lang=c :
     * #define KR_METADATA_HOST 0
     * }
     */
    public static int KR_METADATA_HOST() {
        return KR_METADATA_HOST;
    }
    private static final int KR_METADATA_RACK = (int)1L;
    /**
     * {@snippet lang=c :
     * #define KR_METADATA_RACK 1
     * }
     */
    public static int KR_METADATA_RACK() {
        return KR_METADATA_RACK;
    }
}

