// Generated by jextract

package io.krkafka.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     uint32_t struct_size;
 *     int32_t partition;
 *     int32_t leader;
 *     int32_t leader_epoch;
 *     int32_t error_code;
 *     uint32_t replica_count;
 *     uint32_t isr_count;
 *     uint32_t offline_count;
 * }
 * }
 */
public class kr_metadata_partition {

    kr_metadata_partition() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        kr_kafka_h.C_INT.withName("struct_size"),
        kr_kafka_h.C_INT.withName("partition"),
        kr_kafka_h.C_INT.withName("leader"),
        kr_kafka_h.C_INT.withName("leader_epoch"),
        kr_kafka_h.C_INT.withName("error_code"),
        kr_kafka_h.C_INT.withName("replica_count"),
        kr_kafka_h.C_INT.withName("isr_count"),
        kr_kafka_h.C_INT.withName("offline_count")
    ).withName("$anon$74:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt struct_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("struct_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final OfInt struct_size$layout() {
        return struct_size$LAYOUT;
    }

    private static final long struct_size$OFFSET = $LAYOUT.byteOffset(groupElement("struct_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final long struct_size$offset() {
        return struct_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static int struct_size(MemorySegment struct) {
        return struct.get(struct_size$LAYOUT, struct_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static void struct_size(MemorySegment struct, int fieldValue) {
        struct.set(struct_size$LAYOUT, struct_size$OFFSET, fieldValue);
    }

    private static final OfInt partition$LAYOUT = (OfInt)$LAYOUT.select(groupElement("partition"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t partition
     * }
     */
    public static final OfInt partition$layout() {
        return partition$LAYOUT;
    }

    private static final long partition$OFFSET = $LAYOUT.byteOffset(groupElement("partition"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t partition
     * }
     */
    public static final long partition$offset() {
        return partition$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t partition
     * }
     */
    public static int partition(MemorySegment struct) {
        return struct.get(partition$LAYOUT, partition$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t partition
     * }
     */
    public static void partition(MemorySegment struct, int fieldValue) {
        struct.set(partition$LAYOUT, partition$OFFSET, fieldValue);
    }

    private static final OfInt leader$LAYOUT = (OfInt)$LAYOUT.select(groupElement("leader"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t leader
     * }
     */
    public static final OfInt leader$layout() {
        return leader$LAYOUT;
    }

    private static final long leader$OFFSET = $LAYOUT.byteOffset(groupElement("leader"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t leader
     * }
     */
    public static final long leader$offset() {
        return leader$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t leader
     * }
     */
    public static int leader(MemorySegment struct) {
        return struct.get(leader$LAYOUT, leader$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t leader
     * }
     */
    public static void leader(MemorySegment struct, int fieldValue) {
        struct.set(leader$LAYOUT, leader$OFFSET, fieldValue);
    }

    private static final OfInt leader_epoch$LAYOUT = (OfInt)$LAYOUT.select(groupElement("leader_epoch"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t leader_epoch
     * }
     */
    public static final OfInt leader_epoch$layout() {
        return leader_epoch$LAYOUT;
    }

    private static final long leader_epoch$OFFSET = $LAYOUT.byteOffset(groupElement("leader_epoch"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t leader_epoch
     * }
     */
    public static final long leader_epoch$offset() {
        return leader_epoch$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t leader_epoch
     * }
     */
    public static int leader_epoch(MemorySegment struct) {
        return struct.get(leader_epoch$LAYOUT, leader_epoch$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t leader_epoch
     * }
     */
    public static void leader_epoch(MemorySegment struct, int fieldValue) {
        struct.set(leader_epoch$LAYOUT, leader_epoch$OFFSET, fieldValue);
    }

    private static final OfInt error_code$LAYOUT = (OfInt)$LAYOUT.select(groupElement("error_code"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t error_code
     * }
     */
    public static final OfInt error_code$layout() {
        return error_code$LAYOUT;
    }

    private static final long error_code$OFFSET = $LAYOUT.byteOffset(groupElement("error_code"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t error_code
     * }
     */
    public static final long error_code$offset() {
        return error_code$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t error_code
     * }
     */
    public static int error_code(MemorySegment struct) {
        return struct.get(error_code$LAYOUT, error_code$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t error_code
     * }
     */
    public static void error_code(MemorySegment struct, int fieldValue) {
        struct.set(error_code$LAYOUT, error_code$OFFSET, fieldValue);
    }

    private static final OfInt replica_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("replica_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t replica_count
     * }
     */
    public static final OfInt replica_count$layout() {
        return replica_count$LAYOUT;
    }

    private static final long replica_count$OFFSET = $LAYOUT.byteOffset(groupElement("replica_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t replica_count
     * }
     */
    public static final long replica_count$offset() {
        return replica_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t replica_count
     * }
     */
    public static int replica_count(MemorySegment struct) {
        return struct.get(replica_count$LAYOUT, replica_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t replica_count
     * }
     */
    public static void replica_count(MemorySegment struct, int fieldValue) {
        struct.set(replica_count$LAYOUT, replica_count$OFFSET, fieldValue);
    }

    private static final OfInt isr_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("isr_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t isr_count
     * }
     */
    public static final OfInt isr_count$layout() {
        return isr_count$LAYOUT;
    }

    private static final long isr_count$OFFSET = $LAYOUT.byteOffset(groupElement("isr_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t isr_count
     * }
     */
    public static final long isr_count$offset() {
        return isr_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t isr_count
     * }
     */
    public static int isr_count(MemorySegment struct) {
        return struct.get(isr_count$LAYOUT, isr_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t isr_count
     * }
     */
    public static void isr_count(MemorySegment struct, int fieldValue) {
        struct.set(isr_count$LAYOUT, isr_count$OFFSET, fieldValue);
    }

    private static final OfInt offline_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("offline_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t offline_count
     * }
     */
    public static final OfInt offline_count$layout() {
        return offline_count$LAYOUT;
    }

    private static final long offline_count$OFFSET = $LAYOUT.byteOffset(groupElement("offline_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t offline_count
     * }
     */
    public static final long offline_count$offset() {
        return offline_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t offline_count
     * }
     */
    public static int offline_count(MemorySegment struct) {
        return struct.get(offline_count$LAYOUT, offline_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t offline_count
     * }
     */
    public static void offline_count(MemorySegment struct, int fieldValue) {
        struct.set(offline_count$LAYOUT, offline_count$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

