// Generated by jextract

package io.krkafka.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     uint32_t struct_size;
 *     int32_t id;
 *     uint32_t port;
 *     uint32_t host_len;
 *     uint32_t rack_len;
 *     uint32_t rack_present;
 * }
 * }
 */
public class kr_metadata_broker {

    kr_metadata_broker() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        kr_kafka_h.C_INT.withName("struct_size"),
        kr_kafka_h.C_INT.withName("id"),
        kr_kafka_h.C_INT.withName("port"),
        kr_kafka_h.C_INT.withName("host_len"),
        kr_kafka_h.C_INT.withName("rack_len"),
        kr_kafka_h.C_INT.withName("rack_present")
    ).withName("$anon$71:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt struct_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("struct_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final OfInt struct_size$layout() {
        return struct_size$LAYOUT;
    }

    private static final long struct_size$OFFSET = $LAYOUT.byteOffset(groupElement("struct_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final long struct_size$offset() {
        return struct_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static int struct_size(MemorySegment struct) {
        return struct.get(struct_size$LAYOUT, struct_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static void struct_size(MemorySegment struct, int fieldValue) {
        struct.set(struct_size$LAYOUT, struct_size$OFFSET, fieldValue);
    }

    private static final OfInt id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t id
     * }
     */
    public static final OfInt id$layout() {
        return id$LAYOUT;
    }

    private static final long id$OFFSET = $LAYOUT.byteOffset(groupElement("id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t id
     * }
     */
    public static final long id$offset() {
        return id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t id
     * }
     */
    public static int id(MemorySegment struct) {
        return struct.get(id$LAYOUT, id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t id
     * }
     */
    public static void id(MemorySegment struct, int fieldValue) {
        struct.set(id$LAYOUT, id$OFFSET, fieldValue);
    }

    private static final OfInt port$LAYOUT = (OfInt)$LAYOUT.select(groupElement("port"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t port
     * }
     */
    public static final OfInt port$layout() {
        return port$LAYOUT;
    }

    private static final long port$OFFSET = $LAYOUT.byteOffset(groupElement("port"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t port
     * }
     */
    public static final long port$offset() {
        return port$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t port
     * }
     */
    public static int port(MemorySegment struct) {
        return struct.get(port$LAYOUT, port$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t port
     * }
     */
    public static void port(MemorySegment struct, int fieldValue) {
        struct.set(port$LAYOUT, port$OFFSET, fieldValue);
    }

    private static final OfInt host_len$LAYOUT = (OfInt)$LAYOUT.select(groupElement("host_len"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t host_len
     * }
     */
    public static final OfInt host_len$layout() {
        return host_len$LAYOUT;
    }

    private static final long host_len$OFFSET = $LAYOUT.byteOffset(groupElement("host_len"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t host_len
     * }
     */
    public static final long host_len$offset() {
        return host_len$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t host_len
     * }
     */
    public static int host_len(MemorySegment struct) {
        return struct.get(host_len$LAYOUT, host_len$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t host_len
     * }
     */
    public static void host_len(MemorySegment struct, int fieldValue) {
        struct.set(host_len$LAYOUT, host_len$OFFSET, fieldValue);
    }

    private static final OfInt rack_len$LAYOUT = (OfInt)$LAYOUT.select(groupElement("rack_len"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t rack_len
     * }
     */
    public static final OfInt rack_len$layout() {
        return rack_len$LAYOUT;
    }

    private static final long rack_len$OFFSET = $LAYOUT.byteOffset(groupElement("rack_len"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t rack_len
     * }
     */
    public static final long rack_len$offset() {
        return rack_len$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t rack_len
     * }
     */
    public static int rack_len(MemorySegment struct) {
        return struct.get(rack_len$LAYOUT, rack_len$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t rack_len
     * }
     */
    public static void rack_len(MemorySegment struct, int fieldValue) {
        struct.set(rack_len$LAYOUT, rack_len$OFFSET, fieldValue);
    }

    private static final OfInt rack_present$LAYOUT = (OfInt)$LAYOUT.select(groupElement("rack_present"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t rack_present
     * }
     */
    public static final OfInt rack_present$layout() {
        return rack_present$LAYOUT;
    }

    private static final long rack_present$OFFSET = $LAYOUT.byteOffset(groupElement("rack_present"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t rack_present
     * }
     */
    public static final long rack_present$offset() {
        return rack_present$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t rack_present
     * }
     */
    public static int rack_present(MemorySegment struct) {
        return struct.get(rack_present$LAYOUT, rack_present$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t rack_present
     * }
     */
    public static void rack_present(MemorySegment struct, int fieldValue) {
        struct.set(rack_present$LAYOUT, rack_present$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

