// Generated by jextract

package io.krkafka.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     uint32_t struct_size;
 *     uint64_t delivery_timeout_ns;
 *     uint64_t request_timeout_ns;
 *     uint64_t linger_max_ns;
 *     uint64_t metadata_max_age_ns;
 *     uint64_t topic_resolve_timeout_ns;
 *     uint64_t retry_backoff_min_ns;
 *     uint64_t retry_backoff_max_ns;
 *     uint64_t input_bytes;
 *     uint64_t compressed_bytes;
 *     uint64_t control_reserve_bytes;
 *     uint64_t codec_workspace_bytes;
 *     uint32_t max_in_flight_per_connection;
 *     uint32_t lanes;
 *     uint32_t codec_contexts;
 *     uint32_t max_attempts;
 *     uint32_t request_max_partitions;
 *     uint32_t brokers_max;
 *     uint32_t worker_jobs;
 *     uint32_t connection_wire_window_bytes;
 *     uint32_t batch_target_bytes;
 *     uint32_t batch_hard_bytes;
 *     uint32_t request_target_bytes;
 *     uint32_t request_hard_bytes;
 *     uint32_t record_descriptors;
 *     uint32_t staging_bytes_per_connection;
 *     uint32_t rx_bytes_per_connection;
 *     uint32_t delivery_event_capacity;
 *     uint32_t release_event_capacity;
 *     uint32_t mailbox_capacity;
 *     uint32_t max_open_topics;
 *     uint32_t pending_records_per_topic;
 *     uint32_t max_live_leases;
 *     uint32_t max_batches;
 *     uint32_t codec_window_log;
 *     uint32_t output_chunk_bytes;
 *     uint32_t progressive_threshold;
 *     uint32_t tls_plaintext_bytes;
 *     uint32_t tls_ciphertext_bytes;
 *     uint32_t max_header_count;
 *     uint32_t max_submissions_per_poll;
 *     uint32_t max_submission_records;
 *     uint32_t max_completions_per_poll;
 *     uint32_t sim_encode_bytes_per_poll;
 *     uint32_t target_poll_ms;
 *     uint32_t coalesce_below_bytes;
 *     uint32_t linger_skip_below_rate;
 *     uint32_t unkeyed_policy;
 *     uint32_t unkeyed_run_bytes;
 *     uint32_t partitioner;
 *     uint32_t compression;
 *     uint32_t compression_level;
 *     uint32_t transport;
 *     uint32_t security;
 *     uint32_t sasl_mechanism;
 *     uint32_t tls_system_roots;
 *     kr_span client_id;
 *     const kr_broker *bootstrap;
 *     uint32_t bootstrap_count;
 *     const kr_span *tls_roots;
 *     uint32_t tls_root_count;
 *     kr_span tls_server_name;
 *     kr_span username;
 *     kr_span password;
 *     uint32_t batch_target_mode;
 *     uint32_t request_batching_policy;
 *     uint32_t reserved_request_policy;
 * }
 * }
 */
public class kr_producer_config {

    kr_producer_config() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        kr_kafka_h.C_INT.withName("struct_size"),
        MemoryLayout.paddingLayout(4),
        kr_kafka_h.C_LONG_LONG.withName("delivery_timeout_ns"),
        kr_kafka_h.C_LONG_LONG.withName("request_timeout_ns"),
        kr_kafka_h.C_LONG_LONG.withName("linger_max_ns"),
        kr_kafka_h.C_LONG_LONG.withName("metadata_max_age_ns"),
        kr_kafka_h.C_LONG_LONG.withName("topic_resolve_timeout_ns"),
        kr_kafka_h.C_LONG_LONG.withName("retry_backoff_min_ns"),
        kr_kafka_h.C_LONG_LONG.withName("retry_backoff_max_ns"),
        kr_kafka_h.C_LONG_LONG.withName("input_bytes"),
        kr_kafka_h.C_LONG_LONG.withName("compressed_bytes"),
        kr_kafka_h.C_LONG_LONG.withName("control_reserve_bytes"),
        kr_kafka_h.C_LONG_LONG.withName("codec_workspace_bytes"),
        kr_kafka_h.C_INT.withName("max_in_flight_per_connection"),
        kr_kafka_h.C_INT.withName("lanes"),
        kr_kafka_h.C_INT.withName("codec_contexts"),
        kr_kafka_h.C_INT.withName("max_attempts"),
        kr_kafka_h.C_INT.withName("request_max_partitions"),
        kr_kafka_h.C_INT.withName("brokers_max"),
        kr_kafka_h.C_INT.withName("worker_jobs"),
        kr_kafka_h.C_INT.withName("connection_wire_window_bytes"),
        kr_kafka_h.C_INT.withName("batch_target_bytes"),
        kr_kafka_h.C_INT.withName("batch_hard_bytes"),
        kr_kafka_h.C_INT.withName("request_target_bytes"),
        kr_kafka_h.C_INT.withName("request_hard_bytes"),
        kr_kafka_h.C_INT.withName("record_descriptors"),
        kr_kafka_h.C_INT.withName("staging_bytes_per_connection"),
        kr_kafka_h.C_INT.withName("rx_bytes_per_connection"),
        kr_kafka_h.C_INT.withName("delivery_event_capacity"),
        kr_kafka_h.C_INT.withName("release_event_capacity"),
        kr_kafka_h.C_INT.withName("mailbox_capacity"),
        kr_kafka_h.C_INT.withName("max_open_topics"),
        kr_kafka_h.C_INT.withName("pending_records_per_topic"),
        kr_kafka_h.C_INT.withName("max_live_leases"),
        kr_kafka_h.C_INT.withName("max_batches"),
        kr_kafka_h.C_INT.withName("codec_window_log"),
        kr_kafka_h.C_INT.withName("output_chunk_bytes"),
        kr_kafka_h.C_INT.withName("progressive_threshold"),
        kr_kafka_h.C_INT.withName("tls_plaintext_bytes"),
        kr_kafka_h.C_INT.withName("tls_ciphertext_bytes"),
        kr_kafka_h.C_INT.withName("max_header_count"),
        kr_kafka_h.C_INT.withName("max_submissions_per_poll"),
        kr_kafka_h.C_INT.withName("max_submission_records"),
        kr_kafka_h.C_INT.withName("max_completions_per_poll"),
        kr_kafka_h.C_INT.withName("sim_encode_bytes_per_poll"),
        kr_kafka_h.C_INT.withName("target_poll_ms"),
        kr_kafka_h.C_INT.withName("coalesce_below_bytes"),
        kr_kafka_h.C_INT.withName("linger_skip_below_rate"),
        kr_kafka_h.C_INT.withName("unkeyed_policy"),
        kr_kafka_h.C_INT.withName("unkeyed_run_bytes"),
        kr_kafka_h.C_INT.withName("partitioner"),
        kr_kafka_h.C_INT.withName("compression"),
        kr_kafka_h.C_INT.withName("compression_level"),
        kr_kafka_h.C_INT.withName("transport"),
        kr_kafka_h.C_INT.withName("security"),
        kr_kafka_h.C_INT.withName("sasl_mechanism"),
        kr_kafka_h.C_INT.withName("tls_system_roots"),
        kr_span.layout().withName("client_id"),
        kr_kafka_h.C_POINTER.withName("bootstrap"),
        kr_kafka_h.C_INT.withName("bootstrap_count"),
        MemoryLayout.paddingLayout(4),
        kr_kafka_h.C_POINTER.withName("tls_roots"),
        kr_kafka_h.C_INT.withName("tls_root_count"),
        MemoryLayout.paddingLayout(4),
        kr_span.layout().withName("tls_server_name"),
        kr_span.layout().withName("username"),
        kr_span.layout().withName("password"),
        kr_kafka_h.C_INT.withName("batch_target_mode"),
        kr_kafka_h.C_INT.withName("request_batching_policy"),
        kr_kafka_h.C_INT.withName("reserved_request_policy"),
        MemoryLayout.paddingLayout(4)
    ).withName("$anon$95:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt struct_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("struct_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final OfInt struct_size$layout() {
        return struct_size$LAYOUT;
    }

    private static final long struct_size$OFFSET = $LAYOUT.byteOffset(groupElement("struct_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final long struct_size$offset() {
        return struct_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static int struct_size(MemorySegment struct) {
        return struct.get(struct_size$LAYOUT, struct_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static void struct_size(MemorySegment struct, int fieldValue) {
        struct.set(struct_size$LAYOUT, struct_size$OFFSET, fieldValue);
    }

    private static final OfLong delivery_timeout_ns$LAYOUT = (OfLong)$LAYOUT.select(groupElement("delivery_timeout_ns"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t delivery_timeout_ns
     * }
     */
    public static final OfLong delivery_timeout_ns$layout() {
        return delivery_timeout_ns$LAYOUT;
    }

    private static final long delivery_timeout_ns$OFFSET = $LAYOUT.byteOffset(groupElement("delivery_timeout_ns"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t delivery_timeout_ns
     * }
     */
    public static final long delivery_timeout_ns$offset() {
        return delivery_timeout_ns$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t delivery_timeout_ns
     * }
     */
    public static long delivery_timeout_ns(MemorySegment struct) {
        return struct.get(delivery_timeout_ns$LAYOUT, delivery_timeout_ns$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t delivery_timeout_ns
     * }
     */
    public static void delivery_timeout_ns(MemorySegment struct, long fieldValue) {
        struct.set(delivery_timeout_ns$LAYOUT, delivery_timeout_ns$OFFSET, fieldValue);
    }

    private static final OfLong request_timeout_ns$LAYOUT = (OfLong)$LAYOUT.select(groupElement("request_timeout_ns"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t request_timeout_ns
     * }
     */
    public static final OfLong request_timeout_ns$layout() {
        return request_timeout_ns$LAYOUT;
    }

    private static final long request_timeout_ns$OFFSET = $LAYOUT.byteOffset(groupElement("request_timeout_ns"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t request_timeout_ns
     * }
     */
    public static final long request_timeout_ns$offset() {
        return request_timeout_ns$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t request_timeout_ns
     * }
     */
    public static long request_timeout_ns(MemorySegment struct) {
        return struct.get(request_timeout_ns$LAYOUT, request_timeout_ns$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t request_timeout_ns
     * }
     */
    public static void request_timeout_ns(MemorySegment struct, long fieldValue) {
        struct.set(request_timeout_ns$LAYOUT, request_timeout_ns$OFFSET, fieldValue);
    }

    private static final OfLong linger_max_ns$LAYOUT = (OfLong)$LAYOUT.select(groupElement("linger_max_ns"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t linger_max_ns
     * }
     */
    public static final OfLong linger_max_ns$layout() {
        return linger_max_ns$LAYOUT;
    }

    private static final long linger_max_ns$OFFSET = $LAYOUT.byteOffset(groupElement("linger_max_ns"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t linger_max_ns
     * }
     */
    public static final long linger_max_ns$offset() {
        return linger_max_ns$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t linger_max_ns
     * }
     */
    public static long linger_max_ns(MemorySegment struct) {
        return struct.get(linger_max_ns$LAYOUT, linger_max_ns$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t linger_max_ns
     * }
     */
    public static void linger_max_ns(MemorySegment struct, long fieldValue) {
        struct.set(linger_max_ns$LAYOUT, linger_max_ns$OFFSET, fieldValue);
    }

    private static final OfLong metadata_max_age_ns$LAYOUT = (OfLong)$LAYOUT.select(groupElement("metadata_max_age_ns"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t metadata_max_age_ns
     * }
     */
    public static final OfLong metadata_max_age_ns$layout() {
        return metadata_max_age_ns$LAYOUT;
    }

    private static final long metadata_max_age_ns$OFFSET = $LAYOUT.byteOffset(groupElement("metadata_max_age_ns"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t metadata_max_age_ns
     * }
     */
    public static final long metadata_max_age_ns$offset() {
        return metadata_max_age_ns$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t metadata_max_age_ns
     * }
     */
    public static long metadata_max_age_ns(MemorySegment struct) {
        return struct.get(metadata_max_age_ns$LAYOUT, metadata_max_age_ns$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t metadata_max_age_ns
     * }
     */
    public static void metadata_max_age_ns(MemorySegment struct, long fieldValue) {
        struct.set(metadata_max_age_ns$LAYOUT, metadata_max_age_ns$OFFSET, fieldValue);
    }

    private static final OfLong topic_resolve_timeout_ns$LAYOUT = (OfLong)$LAYOUT.select(groupElement("topic_resolve_timeout_ns"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t topic_resolve_timeout_ns
     * }
     */
    public static final OfLong topic_resolve_timeout_ns$layout() {
        return topic_resolve_timeout_ns$LAYOUT;
    }

    private static final long topic_resolve_timeout_ns$OFFSET = $LAYOUT.byteOffset(groupElement("topic_resolve_timeout_ns"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t topic_resolve_timeout_ns
     * }
     */
    public static final long topic_resolve_timeout_ns$offset() {
        return topic_resolve_timeout_ns$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t topic_resolve_timeout_ns
     * }
     */
    public static long topic_resolve_timeout_ns(MemorySegment struct) {
        return struct.get(topic_resolve_timeout_ns$LAYOUT, topic_resolve_timeout_ns$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t topic_resolve_timeout_ns
     * }
     */
    public static void topic_resolve_timeout_ns(MemorySegment struct, long fieldValue) {
        struct.set(topic_resolve_timeout_ns$LAYOUT, topic_resolve_timeout_ns$OFFSET, fieldValue);
    }

    private static final OfLong retry_backoff_min_ns$LAYOUT = (OfLong)$LAYOUT.select(groupElement("retry_backoff_min_ns"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t retry_backoff_min_ns
     * }
     */
    public static final OfLong retry_backoff_min_ns$layout() {
        return retry_backoff_min_ns$LAYOUT;
    }

    private static final long retry_backoff_min_ns$OFFSET = $LAYOUT.byteOffset(groupElement("retry_backoff_min_ns"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t retry_backoff_min_ns
     * }
     */
    public static final long retry_backoff_min_ns$offset() {
        return retry_backoff_min_ns$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t retry_backoff_min_ns
     * }
     */
    public static long retry_backoff_min_ns(MemorySegment struct) {
        return struct.get(retry_backoff_min_ns$LAYOUT, retry_backoff_min_ns$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t retry_backoff_min_ns
     * }
     */
    public static void retry_backoff_min_ns(MemorySegment struct, long fieldValue) {
        struct.set(retry_backoff_min_ns$LAYOUT, retry_backoff_min_ns$OFFSET, fieldValue);
    }

    private static final OfLong retry_backoff_max_ns$LAYOUT = (OfLong)$LAYOUT.select(groupElement("retry_backoff_max_ns"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t retry_backoff_max_ns
     * }
     */
    public static final OfLong retry_backoff_max_ns$layout() {
        return retry_backoff_max_ns$LAYOUT;
    }

    private static final long retry_backoff_max_ns$OFFSET = $LAYOUT.byteOffset(groupElement("retry_backoff_max_ns"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t retry_backoff_max_ns
     * }
     */
    public static final long retry_backoff_max_ns$offset() {
        return retry_backoff_max_ns$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t retry_backoff_max_ns
     * }
     */
    public static long retry_backoff_max_ns(MemorySegment struct) {
        return struct.get(retry_backoff_max_ns$LAYOUT, retry_backoff_max_ns$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t retry_backoff_max_ns
     * }
     */
    public static void retry_backoff_max_ns(MemorySegment struct, long fieldValue) {
        struct.set(retry_backoff_max_ns$LAYOUT, retry_backoff_max_ns$OFFSET, fieldValue);
    }

    private static final OfLong input_bytes$LAYOUT = (OfLong)$LAYOUT.select(groupElement("input_bytes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t input_bytes
     * }
     */
    public static final OfLong input_bytes$layout() {
        return input_bytes$LAYOUT;
    }

    private static final long input_bytes$OFFSET = $LAYOUT.byteOffset(groupElement("input_bytes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t input_bytes
     * }
     */
    public static final long input_bytes$offset() {
        return input_bytes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t input_bytes
     * }
     */
    public static long input_bytes(MemorySegment struct) {
        return struct.get(input_bytes$LAYOUT, input_bytes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t input_bytes
     * }
     */
    public static void input_bytes(MemorySegment struct, long fieldValue) {
        struct.set(input_bytes$LAYOUT, input_bytes$OFFSET, fieldValue);
    }

    private static final OfLong compressed_bytes$LAYOUT = (OfLong)$LAYOUT.select(groupElement("compressed_bytes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t compressed_bytes
     * }
     */
    public static final OfLong compressed_bytes$layout() {
        return compressed_bytes$LAYOUT;
    }

    private static final long compressed_bytes$OFFSET = $LAYOUT.byteOffset(groupElement("compressed_bytes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t compressed_bytes
     * }
     */
    public static final long compressed_bytes$offset() {
        return compressed_bytes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t compressed_bytes
     * }
     */
    public static long compressed_bytes(MemorySegment struct) {
        return struct.get(compressed_bytes$LAYOUT, compressed_bytes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t compressed_bytes
     * }
     */
    public static void compressed_bytes(MemorySegment struct, long fieldValue) {
        struct.set(compressed_bytes$LAYOUT, compressed_bytes$OFFSET, fieldValue);
    }

    private static final OfLong control_reserve_bytes$LAYOUT = (OfLong)$LAYOUT.select(groupElement("control_reserve_bytes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t control_reserve_bytes
     * }
     */
    public static final OfLong control_reserve_bytes$layout() {
        return control_reserve_bytes$LAYOUT;
    }

    private static final long control_reserve_bytes$OFFSET = $LAYOUT.byteOffset(groupElement("control_reserve_bytes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t control_reserve_bytes
     * }
     */
    public static final long control_reserve_bytes$offset() {
        return control_reserve_bytes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t control_reserve_bytes
     * }
     */
    public static long control_reserve_bytes(MemorySegment struct) {
        return struct.get(control_reserve_bytes$LAYOUT, control_reserve_bytes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t control_reserve_bytes
     * }
     */
    public static void control_reserve_bytes(MemorySegment struct, long fieldValue) {
        struct.set(control_reserve_bytes$LAYOUT, control_reserve_bytes$OFFSET, fieldValue);
    }

    private static final OfLong codec_workspace_bytes$LAYOUT = (OfLong)$LAYOUT.select(groupElement("codec_workspace_bytes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t codec_workspace_bytes
     * }
     */
    public static final OfLong codec_workspace_bytes$layout() {
        return codec_workspace_bytes$LAYOUT;
    }

    private static final long codec_workspace_bytes$OFFSET = $LAYOUT.byteOffset(groupElement("codec_workspace_bytes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t codec_workspace_bytes
     * }
     */
    public static final long codec_workspace_bytes$offset() {
        return codec_workspace_bytes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t codec_workspace_bytes
     * }
     */
    public static long codec_workspace_bytes(MemorySegment struct) {
        return struct.get(codec_workspace_bytes$LAYOUT, codec_workspace_bytes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t codec_workspace_bytes
     * }
     */
    public static void codec_workspace_bytes(MemorySegment struct, long fieldValue) {
        struct.set(codec_workspace_bytes$LAYOUT, codec_workspace_bytes$OFFSET, fieldValue);
    }

    private static final OfInt max_in_flight_per_connection$LAYOUT = (OfInt)$LAYOUT.select(groupElement("max_in_flight_per_connection"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t max_in_flight_per_connection
     * }
     */
    public static final OfInt max_in_flight_per_connection$layout() {
        return max_in_flight_per_connection$LAYOUT;
    }

    private static final long max_in_flight_per_connection$OFFSET = $LAYOUT.byteOffset(groupElement("max_in_flight_per_connection"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t max_in_flight_per_connection
     * }
     */
    public static final long max_in_flight_per_connection$offset() {
        return max_in_flight_per_connection$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t max_in_flight_per_connection
     * }
     */
    public static int max_in_flight_per_connection(MemorySegment struct) {
        return struct.get(max_in_flight_per_connection$LAYOUT, max_in_flight_per_connection$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t max_in_flight_per_connection
     * }
     */
    public static void max_in_flight_per_connection(MemorySegment struct, int fieldValue) {
        struct.set(max_in_flight_per_connection$LAYOUT, max_in_flight_per_connection$OFFSET, fieldValue);
    }

    private static final OfInt lanes$LAYOUT = (OfInt)$LAYOUT.select(groupElement("lanes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t lanes
     * }
     */
    public static final OfInt lanes$layout() {
        return lanes$LAYOUT;
    }

    private static final long lanes$OFFSET = $LAYOUT.byteOffset(groupElement("lanes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t lanes
     * }
     */
    public static final long lanes$offset() {
        return lanes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t lanes
     * }
     */
    public static int lanes(MemorySegment struct) {
        return struct.get(lanes$LAYOUT, lanes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t lanes
     * }
     */
    public static void lanes(MemorySegment struct, int fieldValue) {
        struct.set(lanes$LAYOUT, lanes$OFFSET, fieldValue);
    }

    private static final OfInt codec_contexts$LAYOUT = (OfInt)$LAYOUT.select(groupElement("codec_contexts"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t codec_contexts
     * }
     */
    public static final OfInt codec_contexts$layout() {
        return codec_contexts$LAYOUT;
    }

    private static final long codec_contexts$OFFSET = $LAYOUT.byteOffset(groupElement("codec_contexts"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t codec_contexts
     * }
     */
    public static final long codec_contexts$offset() {
        return codec_contexts$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t codec_contexts
     * }
     */
    public static int codec_contexts(MemorySegment struct) {
        return struct.get(codec_contexts$LAYOUT, codec_contexts$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t codec_contexts
     * }
     */
    public static void codec_contexts(MemorySegment struct, int fieldValue) {
        struct.set(codec_contexts$LAYOUT, codec_contexts$OFFSET, fieldValue);
    }

    private static final OfInt max_attempts$LAYOUT = (OfInt)$LAYOUT.select(groupElement("max_attempts"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t max_attempts
     * }
     */
    public static final OfInt max_attempts$layout() {
        return max_attempts$LAYOUT;
    }

    private static final long max_attempts$OFFSET = $LAYOUT.byteOffset(groupElement("max_attempts"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t max_attempts
     * }
     */
    public static final long max_attempts$offset() {
        return max_attempts$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t max_attempts
     * }
     */
    public static int max_attempts(MemorySegment struct) {
        return struct.get(max_attempts$LAYOUT, max_attempts$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t max_attempts
     * }
     */
    public static void max_attempts(MemorySegment struct, int fieldValue) {
        struct.set(max_attempts$LAYOUT, max_attempts$OFFSET, fieldValue);
    }

    private static final OfInt request_max_partitions$LAYOUT = (OfInt)$LAYOUT.select(groupElement("request_max_partitions"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t request_max_partitions
     * }
     */
    public static final OfInt request_max_partitions$layout() {
        return request_max_partitions$LAYOUT;
    }

    private static final long request_max_partitions$OFFSET = $LAYOUT.byteOffset(groupElement("request_max_partitions"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t request_max_partitions
     * }
     */
    public static final long request_max_partitions$offset() {
        return request_max_partitions$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t request_max_partitions
     * }
     */
    public static int request_max_partitions(MemorySegment struct) {
        return struct.get(request_max_partitions$LAYOUT, request_max_partitions$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t request_max_partitions
     * }
     */
    public static void request_max_partitions(MemorySegment struct, int fieldValue) {
        struct.set(request_max_partitions$LAYOUT, request_max_partitions$OFFSET, fieldValue);
    }

    private static final OfInt brokers_max$LAYOUT = (OfInt)$LAYOUT.select(groupElement("brokers_max"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t brokers_max
     * }
     */
    public static final OfInt brokers_max$layout() {
        return brokers_max$LAYOUT;
    }

    private static final long brokers_max$OFFSET = $LAYOUT.byteOffset(groupElement("brokers_max"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t brokers_max
     * }
     */
    public static final long brokers_max$offset() {
        return brokers_max$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t brokers_max
     * }
     */
    public static int brokers_max(MemorySegment struct) {
        return struct.get(brokers_max$LAYOUT, brokers_max$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t brokers_max
     * }
     */
    public static void brokers_max(MemorySegment struct, int fieldValue) {
        struct.set(brokers_max$LAYOUT, brokers_max$OFFSET, fieldValue);
    }

    private static final OfInt worker_jobs$LAYOUT = (OfInt)$LAYOUT.select(groupElement("worker_jobs"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t worker_jobs
     * }
     */
    public static final OfInt worker_jobs$layout() {
        return worker_jobs$LAYOUT;
    }

    private static final long worker_jobs$OFFSET = $LAYOUT.byteOffset(groupElement("worker_jobs"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t worker_jobs
     * }
     */
    public static final long worker_jobs$offset() {
        return worker_jobs$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t worker_jobs
     * }
     */
    public static int worker_jobs(MemorySegment struct) {
        return struct.get(worker_jobs$LAYOUT, worker_jobs$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t worker_jobs
     * }
     */
    public static void worker_jobs(MemorySegment struct, int fieldValue) {
        struct.set(worker_jobs$LAYOUT, worker_jobs$OFFSET, fieldValue);
    }

    private static final OfInt connection_wire_window_bytes$LAYOUT = (OfInt)$LAYOUT.select(groupElement("connection_wire_window_bytes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t connection_wire_window_bytes
     * }
     */
    public static final OfInt connection_wire_window_bytes$layout() {
        return connection_wire_window_bytes$LAYOUT;
    }

    private static final long connection_wire_window_bytes$OFFSET = $LAYOUT.byteOffset(groupElement("connection_wire_window_bytes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t connection_wire_window_bytes
     * }
     */
    public static final long connection_wire_window_bytes$offset() {
        return connection_wire_window_bytes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t connection_wire_window_bytes
     * }
     */
    public static int connection_wire_window_bytes(MemorySegment struct) {
        return struct.get(connection_wire_window_bytes$LAYOUT, connection_wire_window_bytes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t connection_wire_window_bytes
     * }
     */
    public static void connection_wire_window_bytes(MemorySegment struct, int fieldValue) {
        struct.set(connection_wire_window_bytes$LAYOUT, connection_wire_window_bytes$OFFSET, fieldValue);
    }

    private static final OfInt batch_target_bytes$LAYOUT = (OfInt)$LAYOUT.select(groupElement("batch_target_bytes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t batch_target_bytes
     * }
     */
    public static final OfInt batch_target_bytes$layout() {
        return batch_target_bytes$LAYOUT;
    }

    private static final long batch_target_bytes$OFFSET = $LAYOUT.byteOffset(groupElement("batch_target_bytes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t batch_target_bytes
     * }
     */
    public static final long batch_target_bytes$offset() {
        return batch_target_bytes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t batch_target_bytes
     * }
     */
    public static int batch_target_bytes(MemorySegment struct) {
        return struct.get(batch_target_bytes$LAYOUT, batch_target_bytes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t batch_target_bytes
     * }
     */
    public static void batch_target_bytes(MemorySegment struct, int fieldValue) {
        struct.set(batch_target_bytes$LAYOUT, batch_target_bytes$OFFSET, fieldValue);
    }

    private static final OfInt batch_hard_bytes$LAYOUT = (OfInt)$LAYOUT.select(groupElement("batch_hard_bytes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t batch_hard_bytes
     * }
     */
    public static final OfInt batch_hard_bytes$layout() {
        return batch_hard_bytes$LAYOUT;
    }

    private static final long batch_hard_bytes$OFFSET = $LAYOUT.byteOffset(groupElement("batch_hard_bytes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t batch_hard_bytes
     * }
     */
    public static final long batch_hard_bytes$offset() {
        return batch_hard_bytes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t batch_hard_bytes
     * }
     */
    public static int batch_hard_bytes(MemorySegment struct) {
        return struct.get(batch_hard_bytes$LAYOUT, batch_hard_bytes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t batch_hard_bytes
     * }
     */
    public static void batch_hard_bytes(MemorySegment struct, int fieldValue) {
        struct.set(batch_hard_bytes$LAYOUT, batch_hard_bytes$OFFSET, fieldValue);
    }

    private static final OfInt request_target_bytes$LAYOUT = (OfInt)$LAYOUT.select(groupElement("request_target_bytes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t request_target_bytes
     * }
     */
    public static final OfInt request_target_bytes$layout() {
        return request_target_bytes$LAYOUT;
    }

    private static final long request_target_bytes$OFFSET = $LAYOUT.byteOffset(groupElement("request_target_bytes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t request_target_bytes
     * }
     */
    public static final long request_target_bytes$offset() {
        return request_target_bytes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t request_target_bytes
     * }
     */
    public static int request_target_bytes(MemorySegment struct) {
        return struct.get(request_target_bytes$LAYOUT, request_target_bytes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t request_target_bytes
     * }
     */
    public static void request_target_bytes(MemorySegment struct, int fieldValue) {
        struct.set(request_target_bytes$LAYOUT, request_target_bytes$OFFSET, fieldValue);
    }

    private static final OfInt request_hard_bytes$LAYOUT = (OfInt)$LAYOUT.select(groupElement("request_hard_bytes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t request_hard_bytes
     * }
     */
    public static final OfInt request_hard_bytes$layout() {
        return request_hard_bytes$LAYOUT;
    }

    private static final long request_hard_bytes$OFFSET = $LAYOUT.byteOffset(groupElement("request_hard_bytes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t request_hard_bytes
     * }
     */
    public static final long request_hard_bytes$offset() {
        return request_hard_bytes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t request_hard_bytes
     * }
     */
    public static int request_hard_bytes(MemorySegment struct) {
        return struct.get(request_hard_bytes$LAYOUT, request_hard_bytes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t request_hard_bytes
     * }
     */
    public static void request_hard_bytes(MemorySegment struct, int fieldValue) {
        struct.set(request_hard_bytes$LAYOUT, request_hard_bytes$OFFSET, fieldValue);
    }

    private static final OfInt record_descriptors$LAYOUT = (OfInt)$LAYOUT.select(groupElement("record_descriptors"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t record_descriptors
     * }
     */
    public static final OfInt record_descriptors$layout() {
        return record_descriptors$LAYOUT;
    }

    private static final long record_descriptors$OFFSET = $LAYOUT.byteOffset(groupElement("record_descriptors"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t record_descriptors
     * }
     */
    public static final long record_descriptors$offset() {
        return record_descriptors$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t record_descriptors
     * }
     */
    public static int record_descriptors(MemorySegment struct) {
        return struct.get(record_descriptors$LAYOUT, record_descriptors$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t record_descriptors
     * }
     */
    public static void record_descriptors(MemorySegment struct, int fieldValue) {
        struct.set(record_descriptors$LAYOUT, record_descriptors$OFFSET, fieldValue);
    }

    private static final OfInt staging_bytes_per_connection$LAYOUT = (OfInt)$LAYOUT.select(groupElement("staging_bytes_per_connection"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t staging_bytes_per_connection
     * }
     */
    public static final OfInt staging_bytes_per_connection$layout() {
        return staging_bytes_per_connection$LAYOUT;
    }

    private static final long staging_bytes_per_connection$OFFSET = $LAYOUT.byteOffset(groupElement("staging_bytes_per_connection"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t staging_bytes_per_connection
     * }
     */
    public static final long staging_bytes_per_connection$offset() {
        return staging_bytes_per_connection$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t staging_bytes_per_connection
     * }
     */
    public static int staging_bytes_per_connection(MemorySegment struct) {
        return struct.get(staging_bytes_per_connection$LAYOUT, staging_bytes_per_connection$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t staging_bytes_per_connection
     * }
     */
    public static void staging_bytes_per_connection(MemorySegment struct, int fieldValue) {
        struct.set(staging_bytes_per_connection$LAYOUT, staging_bytes_per_connection$OFFSET, fieldValue);
    }

    private static final OfInt rx_bytes_per_connection$LAYOUT = (OfInt)$LAYOUT.select(groupElement("rx_bytes_per_connection"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t rx_bytes_per_connection
     * }
     */
    public static final OfInt rx_bytes_per_connection$layout() {
        return rx_bytes_per_connection$LAYOUT;
    }

    private static final long rx_bytes_per_connection$OFFSET = $LAYOUT.byteOffset(groupElement("rx_bytes_per_connection"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t rx_bytes_per_connection
     * }
     */
    public static final long rx_bytes_per_connection$offset() {
        return rx_bytes_per_connection$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t rx_bytes_per_connection
     * }
     */
    public static int rx_bytes_per_connection(MemorySegment struct) {
        return struct.get(rx_bytes_per_connection$LAYOUT, rx_bytes_per_connection$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t rx_bytes_per_connection
     * }
     */
    public static void rx_bytes_per_connection(MemorySegment struct, int fieldValue) {
        struct.set(rx_bytes_per_connection$LAYOUT, rx_bytes_per_connection$OFFSET, fieldValue);
    }

    private static final OfInt delivery_event_capacity$LAYOUT = (OfInt)$LAYOUT.select(groupElement("delivery_event_capacity"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t delivery_event_capacity
     * }
     */
    public static final OfInt delivery_event_capacity$layout() {
        return delivery_event_capacity$LAYOUT;
    }

    private static final long delivery_event_capacity$OFFSET = $LAYOUT.byteOffset(groupElement("delivery_event_capacity"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t delivery_event_capacity
     * }
     */
    public static final long delivery_event_capacity$offset() {
        return delivery_event_capacity$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t delivery_event_capacity
     * }
     */
    public static int delivery_event_capacity(MemorySegment struct) {
        return struct.get(delivery_event_capacity$LAYOUT, delivery_event_capacity$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t delivery_event_capacity
     * }
     */
    public static void delivery_event_capacity(MemorySegment struct, int fieldValue) {
        struct.set(delivery_event_capacity$LAYOUT, delivery_event_capacity$OFFSET, fieldValue);
    }

    private static final OfInt release_event_capacity$LAYOUT = (OfInt)$LAYOUT.select(groupElement("release_event_capacity"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t release_event_capacity
     * }
     */
    public static final OfInt release_event_capacity$layout() {
        return release_event_capacity$LAYOUT;
    }

    private static final long release_event_capacity$OFFSET = $LAYOUT.byteOffset(groupElement("release_event_capacity"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t release_event_capacity
     * }
     */
    public static final long release_event_capacity$offset() {
        return release_event_capacity$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t release_event_capacity
     * }
     */
    public static int release_event_capacity(MemorySegment struct) {
        return struct.get(release_event_capacity$LAYOUT, release_event_capacity$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t release_event_capacity
     * }
     */
    public static void release_event_capacity(MemorySegment struct, int fieldValue) {
        struct.set(release_event_capacity$LAYOUT, release_event_capacity$OFFSET, fieldValue);
    }

    private static final OfInt mailbox_capacity$LAYOUT = (OfInt)$LAYOUT.select(groupElement("mailbox_capacity"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t mailbox_capacity
     * }
     */
    public static final OfInt mailbox_capacity$layout() {
        return mailbox_capacity$LAYOUT;
    }

    private static final long mailbox_capacity$OFFSET = $LAYOUT.byteOffset(groupElement("mailbox_capacity"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t mailbox_capacity
     * }
     */
    public static final long mailbox_capacity$offset() {
        return mailbox_capacity$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t mailbox_capacity
     * }
     */
    public static int mailbox_capacity(MemorySegment struct) {
        return struct.get(mailbox_capacity$LAYOUT, mailbox_capacity$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t mailbox_capacity
     * }
     */
    public static void mailbox_capacity(MemorySegment struct, int fieldValue) {
        struct.set(mailbox_capacity$LAYOUT, mailbox_capacity$OFFSET, fieldValue);
    }

    private static final OfInt max_open_topics$LAYOUT = (OfInt)$LAYOUT.select(groupElement("max_open_topics"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t max_open_topics
     * }
     */
    public static final OfInt max_open_topics$layout() {
        return max_open_topics$LAYOUT;
    }

    private static final long max_open_topics$OFFSET = $LAYOUT.byteOffset(groupElement("max_open_topics"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t max_open_topics
     * }
     */
    public static final long max_open_topics$offset() {
        return max_open_topics$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t max_open_topics
     * }
     */
    public static int max_open_topics(MemorySegment struct) {
        return struct.get(max_open_topics$LAYOUT, max_open_topics$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t max_open_topics
     * }
     */
    public static void max_open_topics(MemorySegment struct, int fieldValue) {
        struct.set(max_open_topics$LAYOUT, max_open_topics$OFFSET, fieldValue);
    }

    private static final OfInt pending_records_per_topic$LAYOUT = (OfInt)$LAYOUT.select(groupElement("pending_records_per_topic"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t pending_records_per_topic
     * }
     */
    public static final OfInt pending_records_per_topic$layout() {
        return pending_records_per_topic$LAYOUT;
    }

    private static final long pending_records_per_topic$OFFSET = $LAYOUT.byteOffset(groupElement("pending_records_per_topic"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t pending_records_per_topic
     * }
     */
    public static final long pending_records_per_topic$offset() {
        return pending_records_per_topic$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t pending_records_per_topic
     * }
     */
    public static int pending_records_per_topic(MemorySegment struct) {
        return struct.get(pending_records_per_topic$LAYOUT, pending_records_per_topic$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t pending_records_per_topic
     * }
     */
    public static void pending_records_per_topic(MemorySegment struct, int fieldValue) {
        struct.set(pending_records_per_topic$LAYOUT, pending_records_per_topic$OFFSET, fieldValue);
    }

    private static final OfInt max_live_leases$LAYOUT = (OfInt)$LAYOUT.select(groupElement("max_live_leases"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t max_live_leases
     * }
     */
    public static final OfInt max_live_leases$layout() {
        return max_live_leases$LAYOUT;
    }

    private static final long max_live_leases$OFFSET = $LAYOUT.byteOffset(groupElement("max_live_leases"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t max_live_leases
     * }
     */
    public static final long max_live_leases$offset() {
        return max_live_leases$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t max_live_leases
     * }
     */
    public static int max_live_leases(MemorySegment struct) {
        return struct.get(max_live_leases$LAYOUT, max_live_leases$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t max_live_leases
     * }
     */
    public static void max_live_leases(MemorySegment struct, int fieldValue) {
        struct.set(max_live_leases$LAYOUT, max_live_leases$OFFSET, fieldValue);
    }

    private static final OfInt max_batches$LAYOUT = (OfInt)$LAYOUT.select(groupElement("max_batches"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t max_batches
     * }
     */
    public static final OfInt max_batches$layout() {
        return max_batches$LAYOUT;
    }

    private static final long max_batches$OFFSET = $LAYOUT.byteOffset(groupElement("max_batches"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t max_batches
     * }
     */
    public static final long max_batches$offset() {
        return max_batches$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t max_batches
     * }
     */
    public static int max_batches(MemorySegment struct) {
        return struct.get(max_batches$LAYOUT, max_batches$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t max_batches
     * }
     */
    public static void max_batches(MemorySegment struct, int fieldValue) {
        struct.set(max_batches$LAYOUT, max_batches$OFFSET, fieldValue);
    }

    private static final OfInt codec_window_log$LAYOUT = (OfInt)$LAYOUT.select(groupElement("codec_window_log"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t codec_window_log
     * }
     */
    public static final OfInt codec_window_log$layout() {
        return codec_window_log$LAYOUT;
    }

    private static final long codec_window_log$OFFSET = $LAYOUT.byteOffset(groupElement("codec_window_log"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t codec_window_log
     * }
     */
    public static final long codec_window_log$offset() {
        return codec_window_log$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t codec_window_log
     * }
     */
    public static int codec_window_log(MemorySegment struct) {
        return struct.get(codec_window_log$LAYOUT, codec_window_log$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t codec_window_log
     * }
     */
    public static void codec_window_log(MemorySegment struct, int fieldValue) {
        struct.set(codec_window_log$LAYOUT, codec_window_log$OFFSET, fieldValue);
    }

    private static final OfInt output_chunk_bytes$LAYOUT = (OfInt)$LAYOUT.select(groupElement("output_chunk_bytes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t output_chunk_bytes
     * }
     */
    public static final OfInt output_chunk_bytes$layout() {
        return output_chunk_bytes$LAYOUT;
    }

    private static final long output_chunk_bytes$OFFSET = $LAYOUT.byteOffset(groupElement("output_chunk_bytes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t output_chunk_bytes
     * }
     */
    public static final long output_chunk_bytes$offset() {
        return output_chunk_bytes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t output_chunk_bytes
     * }
     */
    public static int output_chunk_bytes(MemorySegment struct) {
        return struct.get(output_chunk_bytes$LAYOUT, output_chunk_bytes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t output_chunk_bytes
     * }
     */
    public static void output_chunk_bytes(MemorySegment struct, int fieldValue) {
        struct.set(output_chunk_bytes$LAYOUT, output_chunk_bytes$OFFSET, fieldValue);
    }

    private static final OfInt progressive_threshold$LAYOUT = (OfInt)$LAYOUT.select(groupElement("progressive_threshold"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t progressive_threshold
     * }
     */
    public static final OfInt progressive_threshold$layout() {
        return progressive_threshold$LAYOUT;
    }

    private static final long progressive_threshold$OFFSET = $LAYOUT.byteOffset(groupElement("progressive_threshold"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t progressive_threshold
     * }
     */
    public static final long progressive_threshold$offset() {
        return progressive_threshold$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t progressive_threshold
     * }
     */
    public static int progressive_threshold(MemorySegment struct) {
        return struct.get(progressive_threshold$LAYOUT, progressive_threshold$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t progressive_threshold
     * }
     */
    public static void progressive_threshold(MemorySegment struct, int fieldValue) {
        struct.set(progressive_threshold$LAYOUT, progressive_threshold$OFFSET, fieldValue);
    }

    private static final OfInt tls_plaintext_bytes$LAYOUT = (OfInt)$LAYOUT.select(groupElement("tls_plaintext_bytes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t tls_plaintext_bytes
     * }
     */
    public static final OfInt tls_plaintext_bytes$layout() {
        return tls_plaintext_bytes$LAYOUT;
    }

    private static final long tls_plaintext_bytes$OFFSET = $LAYOUT.byteOffset(groupElement("tls_plaintext_bytes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t tls_plaintext_bytes
     * }
     */
    public static final long tls_plaintext_bytes$offset() {
        return tls_plaintext_bytes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t tls_plaintext_bytes
     * }
     */
    public static int tls_plaintext_bytes(MemorySegment struct) {
        return struct.get(tls_plaintext_bytes$LAYOUT, tls_plaintext_bytes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t tls_plaintext_bytes
     * }
     */
    public static void tls_plaintext_bytes(MemorySegment struct, int fieldValue) {
        struct.set(tls_plaintext_bytes$LAYOUT, tls_plaintext_bytes$OFFSET, fieldValue);
    }

    private static final OfInt tls_ciphertext_bytes$LAYOUT = (OfInt)$LAYOUT.select(groupElement("tls_ciphertext_bytes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t tls_ciphertext_bytes
     * }
     */
    public static final OfInt tls_ciphertext_bytes$layout() {
        return tls_ciphertext_bytes$LAYOUT;
    }

    private static final long tls_ciphertext_bytes$OFFSET = $LAYOUT.byteOffset(groupElement("tls_ciphertext_bytes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t tls_ciphertext_bytes
     * }
     */
    public static final long tls_ciphertext_bytes$offset() {
        return tls_ciphertext_bytes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t tls_ciphertext_bytes
     * }
     */
    public static int tls_ciphertext_bytes(MemorySegment struct) {
        return struct.get(tls_ciphertext_bytes$LAYOUT, tls_ciphertext_bytes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t tls_ciphertext_bytes
     * }
     */
    public static void tls_ciphertext_bytes(MemorySegment struct, int fieldValue) {
        struct.set(tls_ciphertext_bytes$LAYOUT, tls_ciphertext_bytes$OFFSET, fieldValue);
    }

    private static final OfInt max_header_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("max_header_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t max_header_count
     * }
     */
    public static final OfInt max_header_count$layout() {
        return max_header_count$LAYOUT;
    }

    private static final long max_header_count$OFFSET = $LAYOUT.byteOffset(groupElement("max_header_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t max_header_count
     * }
     */
    public static final long max_header_count$offset() {
        return max_header_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t max_header_count
     * }
     */
    public static int max_header_count(MemorySegment struct) {
        return struct.get(max_header_count$LAYOUT, max_header_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t max_header_count
     * }
     */
    public static void max_header_count(MemorySegment struct, int fieldValue) {
        struct.set(max_header_count$LAYOUT, max_header_count$OFFSET, fieldValue);
    }

    private static final OfInt max_submissions_per_poll$LAYOUT = (OfInt)$LAYOUT.select(groupElement("max_submissions_per_poll"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t max_submissions_per_poll
     * }
     */
    public static final OfInt max_submissions_per_poll$layout() {
        return max_submissions_per_poll$LAYOUT;
    }

    private static final long max_submissions_per_poll$OFFSET = $LAYOUT.byteOffset(groupElement("max_submissions_per_poll"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t max_submissions_per_poll
     * }
     */
    public static final long max_submissions_per_poll$offset() {
        return max_submissions_per_poll$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t max_submissions_per_poll
     * }
     */
    public static int max_submissions_per_poll(MemorySegment struct) {
        return struct.get(max_submissions_per_poll$LAYOUT, max_submissions_per_poll$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t max_submissions_per_poll
     * }
     */
    public static void max_submissions_per_poll(MemorySegment struct, int fieldValue) {
        struct.set(max_submissions_per_poll$LAYOUT, max_submissions_per_poll$OFFSET, fieldValue);
    }

    private static final OfInt max_submission_records$LAYOUT = (OfInt)$LAYOUT.select(groupElement("max_submission_records"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t max_submission_records
     * }
     */
    public static final OfInt max_submission_records$layout() {
        return max_submission_records$LAYOUT;
    }

    private static final long max_submission_records$OFFSET = $LAYOUT.byteOffset(groupElement("max_submission_records"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t max_submission_records
     * }
     */
    public static final long max_submission_records$offset() {
        return max_submission_records$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t max_submission_records
     * }
     */
    public static int max_submission_records(MemorySegment struct) {
        return struct.get(max_submission_records$LAYOUT, max_submission_records$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t max_submission_records
     * }
     */
    public static void max_submission_records(MemorySegment struct, int fieldValue) {
        struct.set(max_submission_records$LAYOUT, max_submission_records$OFFSET, fieldValue);
    }

    private static final OfInt max_completions_per_poll$LAYOUT = (OfInt)$LAYOUT.select(groupElement("max_completions_per_poll"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t max_completions_per_poll
     * }
     */
    public static final OfInt max_completions_per_poll$layout() {
        return max_completions_per_poll$LAYOUT;
    }

    private static final long max_completions_per_poll$OFFSET = $LAYOUT.byteOffset(groupElement("max_completions_per_poll"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t max_completions_per_poll
     * }
     */
    public static final long max_completions_per_poll$offset() {
        return max_completions_per_poll$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t max_completions_per_poll
     * }
     */
    public static int max_completions_per_poll(MemorySegment struct) {
        return struct.get(max_completions_per_poll$LAYOUT, max_completions_per_poll$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t max_completions_per_poll
     * }
     */
    public static void max_completions_per_poll(MemorySegment struct, int fieldValue) {
        struct.set(max_completions_per_poll$LAYOUT, max_completions_per_poll$OFFSET, fieldValue);
    }

    private static final OfInt sim_encode_bytes_per_poll$LAYOUT = (OfInt)$LAYOUT.select(groupElement("sim_encode_bytes_per_poll"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t sim_encode_bytes_per_poll
     * }
     */
    public static final OfInt sim_encode_bytes_per_poll$layout() {
        return sim_encode_bytes_per_poll$LAYOUT;
    }

    private static final long sim_encode_bytes_per_poll$OFFSET = $LAYOUT.byteOffset(groupElement("sim_encode_bytes_per_poll"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t sim_encode_bytes_per_poll
     * }
     */
    public static final long sim_encode_bytes_per_poll$offset() {
        return sim_encode_bytes_per_poll$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t sim_encode_bytes_per_poll
     * }
     */
    public static int sim_encode_bytes_per_poll(MemorySegment struct) {
        return struct.get(sim_encode_bytes_per_poll$LAYOUT, sim_encode_bytes_per_poll$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t sim_encode_bytes_per_poll
     * }
     */
    public static void sim_encode_bytes_per_poll(MemorySegment struct, int fieldValue) {
        struct.set(sim_encode_bytes_per_poll$LAYOUT, sim_encode_bytes_per_poll$OFFSET, fieldValue);
    }

    private static final OfInt target_poll_ms$LAYOUT = (OfInt)$LAYOUT.select(groupElement("target_poll_ms"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t target_poll_ms
     * }
     */
    public static final OfInt target_poll_ms$layout() {
        return target_poll_ms$LAYOUT;
    }

    private static final long target_poll_ms$OFFSET = $LAYOUT.byteOffset(groupElement("target_poll_ms"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t target_poll_ms
     * }
     */
    public static final long target_poll_ms$offset() {
        return target_poll_ms$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t target_poll_ms
     * }
     */
    public static int target_poll_ms(MemorySegment struct) {
        return struct.get(target_poll_ms$LAYOUT, target_poll_ms$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t target_poll_ms
     * }
     */
    public static void target_poll_ms(MemorySegment struct, int fieldValue) {
        struct.set(target_poll_ms$LAYOUT, target_poll_ms$OFFSET, fieldValue);
    }

    private static final OfInt coalesce_below_bytes$LAYOUT = (OfInt)$LAYOUT.select(groupElement("coalesce_below_bytes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t coalesce_below_bytes
     * }
     */
    public static final OfInt coalesce_below_bytes$layout() {
        return coalesce_below_bytes$LAYOUT;
    }

    private static final long coalesce_below_bytes$OFFSET = $LAYOUT.byteOffset(groupElement("coalesce_below_bytes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t coalesce_below_bytes
     * }
     */
    public static final long coalesce_below_bytes$offset() {
        return coalesce_below_bytes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t coalesce_below_bytes
     * }
     */
    public static int coalesce_below_bytes(MemorySegment struct) {
        return struct.get(coalesce_below_bytes$LAYOUT, coalesce_below_bytes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t coalesce_below_bytes
     * }
     */
    public static void coalesce_below_bytes(MemorySegment struct, int fieldValue) {
        struct.set(coalesce_below_bytes$LAYOUT, coalesce_below_bytes$OFFSET, fieldValue);
    }

    private static final OfInt linger_skip_below_rate$LAYOUT = (OfInt)$LAYOUT.select(groupElement("linger_skip_below_rate"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t linger_skip_below_rate
     * }
     */
    public static final OfInt linger_skip_below_rate$layout() {
        return linger_skip_below_rate$LAYOUT;
    }

    private static final long linger_skip_below_rate$OFFSET = $LAYOUT.byteOffset(groupElement("linger_skip_below_rate"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t linger_skip_below_rate
     * }
     */
    public static final long linger_skip_below_rate$offset() {
        return linger_skip_below_rate$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t linger_skip_below_rate
     * }
     */
    public static int linger_skip_below_rate(MemorySegment struct) {
        return struct.get(linger_skip_below_rate$LAYOUT, linger_skip_below_rate$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t linger_skip_below_rate
     * }
     */
    public static void linger_skip_below_rate(MemorySegment struct, int fieldValue) {
        struct.set(linger_skip_below_rate$LAYOUT, linger_skip_below_rate$OFFSET, fieldValue);
    }

    private static final OfInt unkeyed_policy$LAYOUT = (OfInt)$LAYOUT.select(groupElement("unkeyed_policy"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t unkeyed_policy
     * }
     */
    public static final OfInt unkeyed_policy$layout() {
        return unkeyed_policy$LAYOUT;
    }

    private static final long unkeyed_policy$OFFSET = $LAYOUT.byteOffset(groupElement("unkeyed_policy"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t unkeyed_policy
     * }
     */
    public static final long unkeyed_policy$offset() {
        return unkeyed_policy$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t unkeyed_policy
     * }
     */
    public static int unkeyed_policy(MemorySegment struct) {
        return struct.get(unkeyed_policy$LAYOUT, unkeyed_policy$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t unkeyed_policy
     * }
     */
    public static void unkeyed_policy(MemorySegment struct, int fieldValue) {
        struct.set(unkeyed_policy$LAYOUT, unkeyed_policy$OFFSET, fieldValue);
    }

    private static final OfInt unkeyed_run_bytes$LAYOUT = (OfInt)$LAYOUT.select(groupElement("unkeyed_run_bytes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t unkeyed_run_bytes
     * }
     */
    public static final OfInt unkeyed_run_bytes$layout() {
        return unkeyed_run_bytes$LAYOUT;
    }

    private static final long unkeyed_run_bytes$OFFSET = $LAYOUT.byteOffset(groupElement("unkeyed_run_bytes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t unkeyed_run_bytes
     * }
     */
    public static final long unkeyed_run_bytes$offset() {
        return unkeyed_run_bytes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t unkeyed_run_bytes
     * }
     */
    public static int unkeyed_run_bytes(MemorySegment struct) {
        return struct.get(unkeyed_run_bytes$LAYOUT, unkeyed_run_bytes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t unkeyed_run_bytes
     * }
     */
    public static void unkeyed_run_bytes(MemorySegment struct, int fieldValue) {
        struct.set(unkeyed_run_bytes$LAYOUT, unkeyed_run_bytes$OFFSET, fieldValue);
    }

    private static final OfInt partitioner$LAYOUT = (OfInt)$LAYOUT.select(groupElement("partitioner"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t partitioner
     * }
     */
    public static final OfInt partitioner$layout() {
        return partitioner$LAYOUT;
    }

    private static final long partitioner$OFFSET = $LAYOUT.byteOffset(groupElement("partitioner"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t partitioner
     * }
     */
    public static final long partitioner$offset() {
        return partitioner$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t partitioner
     * }
     */
    public static int partitioner(MemorySegment struct) {
        return struct.get(partitioner$LAYOUT, partitioner$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t partitioner
     * }
     */
    public static void partitioner(MemorySegment struct, int fieldValue) {
        struct.set(partitioner$LAYOUT, partitioner$OFFSET, fieldValue);
    }

    private static final OfInt compression$LAYOUT = (OfInt)$LAYOUT.select(groupElement("compression"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t compression
     * }
     */
    public static final OfInt compression$layout() {
        return compression$LAYOUT;
    }

    private static final long compression$OFFSET = $LAYOUT.byteOffset(groupElement("compression"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t compression
     * }
     */
    public static final long compression$offset() {
        return compression$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t compression
     * }
     */
    public static int compression(MemorySegment struct) {
        return struct.get(compression$LAYOUT, compression$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t compression
     * }
     */
    public static void compression(MemorySegment struct, int fieldValue) {
        struct.set(compression$LAYOUT, compression$OFFSET, fieldValue);
    }

    private static final OfInt compression_level$LAYOUT = (OfInt)$LAYOUT.select(groupElement("compression_level"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t compression_level
     * }
     */
    public static final OfInt compression_level$layout() {
        return compression_level$LAYOUT;
    }

    private static final long compression_level$OFFSET = $LAYOUT.byteOffset(groupElement("compression_level"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t compression_level
     * }
     */
    public static final long compression_level$offset() {
        return compression_level$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t compression_level
     * }
     */
    public static int compression_level(MemorySegment struct) {
        return struct.get(compression_level$LAYOUT, compression_level$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t compression_level
     * }
     */
    public static void compression_level(MemorySegment struct, int fieldValue) {
        struct.set(compression_level$LAYOUT, compression_level$OFFSET, fieldValue);
    }

    private static final OfInt transport$LAYOUT = (OfInt)$LAYOUT.select(groupElement("transport"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t transport
     * }
     */
    public static final OfInt transport$layout() {
        return transport$LAYOUT;
    }

    private static final long transport$OFFSET = $LAYOUT.byteOffset(groupElement("transport"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t transport
     * }
     */
    public static final long transport$offset() {
        return transport$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t transport
     * }
     */
    public static int transport(MemorySegment struct) {
        return struct.get(transport$LAYOUT, transport$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t transport
     * }
     */
    public static void transport(MemorySegment struct, int fieldValue) {
        struct.set(transport$LAYOUT, transport$OFFSET, fieldValue);
    }

    private static final OfInt security$LAYOUT = (OfInt)$LAYOUT.select(groupElement("security"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t security
     * }
     */
    public static final OfInt security$layout() {
        return security$LAYOUT;
    }

    private static final long security$OFFSET = $LAYOUT.byteOffset(groupElement("security"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t security
     * }
     */
    public static final long security$offset() {
        return security$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t security
     * }
     */
    public static int security(MemorySegment struct) {
        return struct.get(security$LAYOUT, security$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t security
     * }
     */
    public static void security(MemorySegment struct, int fieldValue) {
        struct.set(security$LAYOUT, security$OFFSET, fieldValue);
    }

    private static final OfInt sasl_mechanism$LAYOUT = (OfInt)$LAYOUT.select(groupElement("sasl_mechanism"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t sasl_mechanism
     * }
     */
    public static final OfInt sasl_mechanism$layout() {
        return sasl_mechanism$LAYOUT;
    }

    private static final long sasl_mechanism$OFFSET = $LAYOUT.byteOffset(groupElement("sasl_mechanism"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t sasl_mechanism
     * }
     */
    public static final long sasl_mechanism$offset() {
        return sasl_mechanism$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t sasl_mechanism
     * }
     */
    public static int sasl_mechanism(MemorySegment struct) {
        return struct.get(sasl_mechanism$LAYOUT, sasl_mechanism$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t sasl_mechanism
     * }
     */
    public static void sasl_mechanism(MemorySegment struct, int fieldValue) {
        struct.set(sasl_mechanism$LAYOUT, sasl_mechanism$OFFSET, fieldValue);
    }

    private static final OfInt tls_system_roots$LAYOUT = (OfInt)$LAYOUT.select(groupElement("tls_system_roots"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t tls_system_roots
     * }
     */
    public static final OfInt tls_system_roots$layout() {
        return tls_system_roots$LAYOUT;
    }

    private static final long tls_system_roots$OFFSET = $LAYOUT.byteOffset(groupElement("tls_system_roots"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t tls_system_roots
     * }
     */
    public static final long tls_system_roots$offset() {
        return tls_system_roots$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t tls_system_roots
     * }
     */
    public static int tls_system_roots(MemorySegment struct) {
        return struct.get(tls_system_roots$LAYOUT, tls_system_roots$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t tls_system_roots
     * }
     */
    public static void tls_system_roots(MemorySegment struct, int fieldValue) {
        struct.set(tls_system_roots$LAYOUT, tls_system_roots$OFFSET, fieldValue);
    }

    private static final GroupLayout client_id$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("client_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * kr_span client_id
     * }
     */
    public static final GroupLayout client_id$layout() {
        return client_id$LAYOUT;
    }

    private static final long client_id$OFFSET = $LAYOUT.byteOffset(groupElement("client_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * kr_span client_id
     * }
     */
    public static final long client_id$offset() {
        return client_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * kr_span client_id
     * }
     */
    public static MemorySegment client_id(MemorySegment struct) {
        return struct.asSlice(client_id$OFFSET, client_id$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * kr_span client_id
     * }
     */
    public static void client_id(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, client_id$OFFSET, client_id$LAYOUT.byteSize());
    }

    private static final AddressLayout bootstrap$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("bootstrap"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const kr_broker *bootstrap
     * }
     */
    public static final AddressLayout bootstrap$layout() {
        return bootstrap$LAYOUT;
    }

    private static final long bootstrap$OFFSET = $LAYOUT.byteOffset(groupElement("bootstrap"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const kr_broker *bootstrap
     * }
     */
    public static final long bootstrap$offset() {
        return bootstrap$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const kr_broker *bootstrap
     * }
     */
    public static MemorySegment bootstrap(MemorySegment struct) {
        return struct.get(bootstrap$LAYOUT, bootstrap$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const kr_broker *bootstrap
     * }
     */
    public static void bootstrap(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(bootstrap$LAYOUT, bootstrap$OFFSET, fieldValue);
    }

    private static final OfInt bootstrap_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("bootstrap_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t bootstrap_count
     * }
     */
    public static final OfInt bootstrap_count$layout() {
        return bootstrap_count$LAYOUT;
    }

    private static final long bootstrap_count$OFFSET = $LAYOUT.byteOffset(groupElement("bootstrap_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t bootstrap_count
     * }
     */
    public static final long bootstrap_count$offset() {
        return bootstrap_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t bootstrap_count
     * }
     */
    public static int bootstrap_count(MemorySegment struct) {
        return struct.get(bootstrap_count$LAYOUT, bootstrap_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t bootstrap_count
     * }
     */
    public static void bootstrap_count(MemorySegment struct, int fieldValue) {
        struct.set(bootstrap_count$LAYOUT, bootstrap_count$OFFSET, fieldValue);
    }

    private static final AddressLayout tls_roots$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("tls_roots"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const kr_span *tls_roots
     * }
     */
    public static final AddressLayout tls_roots$layout() {
        return tls_roots$LAYOUT;
    }

    private static final long tls_roots$OFFSET = $LAYOUT.byteOffset(groupElement("tls_roots"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const kr_span *tls_roots
     * }
     */
    public static final long tls_roots$offset() {
        return tls_roots$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const kr_span *tls_roots
     * }
     */
    public static MemorySegment tls_roots(MemorySegment struct) {
        return struct.get(tls_roots$LAYOUT, tls_roots$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const kr_span *tls_roots
     * }
     */
    public static void tls_roots(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(tls_roots$LAYOUT, tls_roots$OFFSET, fieldValue);
    }

    private static final OfInt tls_root_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("tls_root_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t tls_root_count
     * }
     */
    public static final OfInt tls_root_count$layout() {
        return tls_root_count$LAYOUT;
    }

    private static final long tls_root_count$OFFSET = $LAYOUT.byteOffset(groupElement("tls_root_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t tls_root_count
     * }
     */
    public static final long tls_root_count$offset() {
        return tls_root_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t tls_root_count
     * }
     */
    public static int tls_root_count(MemorySegment struct) {
        return struct.get(tls_root_count$LAYOUT, tls_root_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t tls_root_count
     * }
     */
    public static void tls_root_count(MemorySegment struct, int fieldValue) {
        struct.set(tls_root_count$LAYOUT, tls_root_count$OFFSET, fieldValue);
    }

    private static final GroupLayout tls_server_name$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("tls_server_name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * kr_span tls_server_name
     * }
     */
    public static final GroupLayout tls_server_name$layout() {
        return tls_server_name$LAYOUT;
    }

    private static final long tls_server_name$OFFSET = $LAYOUT.byteOffset(groupElement("tls_server_name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * kr_span tls_server_name
     * }
     */
    public static final long tls_server_name$offset() {
        return tls_server_name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * kr_span tls_server_name
     * }
     */
    public static MemorySegment tls_server_name(MemorySegment struct) {
        return struct.asSlice(tls_server_name$OFFSET, tls_server_name$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * kr_span tls_server_name
     * }
     */
    public static void tls_server_name(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, tls_server_name$OFFSET, tls_server_name$LAYOUT.byteSize());
    }

    private static final GroupLayout username$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("username"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * kr_span username
     * }
     */
    public static final GroupLayout username$layout() {
        return username$LAYOUT;
    }

    private static final long username$OFFSET = $LAYOUT.byteOffset(groupElement("username"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * kr_span username
     * }
     */
    public static final long username$offset() {
        return username$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * kr_span username
     * }
     */
    public static MemorySegment username(MemorySegment struct) {
        return struct.asSlice(username$OFFSET, username$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * kr_span username
     * }
     */
    public static void username(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, username$OFFSET, username$LAYOUT.byteSize());
    }

    private static final GroupLayout password$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("password"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * kr_span password
     * }
     */
    public static final GroupLayout password$layout() {
        return password$LAYOUT;
    }

    private static final long password$OFFSET = $LAYOUT.byteOffset(groupElement("password"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * kr_span password
     * }
     */
    public static final long password$offset() {
        return password$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * kr_span password
     * }
     */
    public static MemorySegment password(MemorySegment struct) {
        return struct.asSlice(password$OFFSET, password$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * kr_span password
     * }
     */
    public static void password(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, password$OFFSET, password$LAYOUT.byteSize());
    }

    private static final OfInt batch_target_mode$LAYOUT = (OfInt)$LAYOUT.select(groupElement("batch_target_mode"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t batch_target_mode
     * }
     */
    public static final OfInt batch_target_mode$layout() {
        return batch_target_mode$LAYOUT;
    }

    private static final long batch_target_mode$OFFSET = $LAYOUT.byteOffset(groupElement("batch_target_mode"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t batch_target_mode
     * }
     */
    public static final long batch_target_mode$offset() {
        return batch_target_mode$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t batch_target_mode
     * }
     */
    public static int batch_target_mode(MemorySegment struct) {
        return struct.get(batch_target_mode$LAYOUT, batch_target_mode$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t batch_target_mode
     * }
     */
    public static void batch_target_mode(MemorySegment struct, int fieldValue) {
        struct.set(batch_target_mode$LAYOUT, batch_target_mode$OFFSET, fieldValue);
    }

    private static final OfInt request_batching_policy$LAYOUT = (OfInt)$LAYOUT.select(groupElement("request_batching_policy"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t request_batching_policy
     * }
     */
    public static final OfInt request_batching_policy$layout() {
        return request_batching_policy$LAYOUT;
    }

    private static final long request_batching_policy$OFFSET = $LAYOUT.byteOffset(groupElement("request_batching_policy"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t request_batching_policy
     * }
     */
    public static final long request_batching_policy$offset() {
        return request_batching_policy$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t request_batching_policy
     * }
     */
    public static int request_batching_policy(MemorySegment struct) {
        return struct.get(request_batching_policy$LAYOUT, request_batching_policy$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t request_batching_policy
     * }
     */
    public static void request_batching_policy(MemorySegment struct, int fieldValue) {
        struct.set(request_batching_policy$LAYOUT, request_batching_policy$OFFSET, fieldValue);
    }

    private static final OfInt reserved_request_policy$LAYOUT = (OfInt)$LAYOUT.select(groupElement("reserved_request_policy"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t reserved_request_policy
     * }
     */
    public static final OfInt reserved_request_policy$layout() {
        return reserved_request_policy$LAYOUT;
    }

    private static final long reserved_request_policy$OFFSET = $LAYOUT.byteOffset(groupElement("reserved_request_policy"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t reserved_request_policy
     * }
     */
    public static final long reserved_request_policy$offset() {
        return reserved_request_policy$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t reserved_request_policy
     * }
     */
    public static int reserved_request_policy(MemorySegment struct) {
        return struct.get(reserved_request_policy$LAYOUT, reserved_request_policy$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t reserved_request_policy
     * }
     */
    public static void reserved_request_policy(MemorySegment struct, int fieldValue) {
        struct.set(reserved_request_policy$LAYOUT, reserved_request_policy$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

