// Generated by jextract

package io.krkafka.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     uint32_t struct_size;
 *     uint32_t topic;
 *     int32_t partition_hint;
 *     int32_t lane_hint;
 *     kr_span key;
 *     uint32_t key_is_null;
 *     kr_span value;
 *     uint32_t value_is_null;
 *     const kr_header *headers;
 *     uint32_t header_count;
 *     int64_t timestamp_ms;
 *     uint64_t user_token;
 *     uint64_t delivery_timeout_ns;
 * }
 * }
 */
public class kr_record {

    kr_record() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        kr_kafka_h.C_INT.withName("struct_size"),
        kr_kafka_h.C_INT.withName("topic"),
        kr_kafka_h.C_INT.withName("partition_hint"),
        kr_kafka_h.C_INT.withName("lane_hint"),
        kr_span.layout().withName("key"),
        kr_kafka_h.C_INT.withName("key_is_null"),
        MemoryLayout.paddingLayout(4),
        kr_span.layout().withName("value"),
        kr_kafka_h.C_INT.withName("value_is_null"),
        MemoryLayout.paddingLayout(4),
        kr_kafka_h.C_POINTER.withName("headers"),
        kr_kafka_h.C_INT.withName("header_count"),
        MemoryLayout.paddingLayout(4),
        kr_kafka_h.C_LONG_LONG.withName("timestamp_ms"),
        kr_kafka_h.C_LONG_LONG.withName("user_token"),
        kr_kafka_h.C_LONG_LONG.withName("delivery_timeout_ns")
    ).withName("$anon$82:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt struct_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("struct_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final OfInt struct_size$layout() {
        return struct_size$LAYOUT;
    }

    private static final long struct_size$OFFSET = $LAYOUT.byteOffset(groupElement("struct_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final long struct_size$offset() {
        return struct_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static int struct_size(MemorySegment struct) {
        return struct.get(struct_size$LAYOUT, struct_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static void struct_size(MemorySegment struct, int fieldValue) {
        struct.set(struct_size$LAYOUT, struct_size$OFFSET, fieldValue);
    }

    private static final OfInt topic$LAYOUT = (OfInt)$LAYOUT.select(groupElement("topic"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t topic
     * }
     */
    public static final OfInt topic$layout() {
        return topic$LAYOUT;
    }

    private static final long topic$OFFSET = $LAYOUT.byteOffset(groupElement("topic"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t topic
     * }
     */
    public static final long topic$offset() {
        return topic$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t topic
     * }
     */
    public static int topic(MemorySegment struct) {
        return struct.get(topic$LAYOUT, topic$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t topic
     * }
     */
    public static void topic(MemorySegment struct, int fieldValue) {
        struct.set(topic$LAYOUT, topic$OFFSET, fieldValue);
    }

    private static final OfInt partition_hint$LAYOUT = (OfInt)$LAYOUT.select(groupElement("partition_hint"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t partition_hint
     * }
     */
    public static final OfInt partition_hint$layout() {
        return partition_hint$LAYOUT;
    }

    private static final long partition_hint$OFFSET = $LAYOUT.byteOffset(groupElement("partition_hint"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t partition_hint
     * }
     */
    public static final long partition_hint$offset() {
        return partition_hint$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t partition_hint
     * }
     */
    public static int partition_hint(MemorySegment struct) {
        return struct.get(partition_hint$LAYOUT, partition_hint$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t partition_hint
     * }
     */
    public static void partition_hint(MemorySegment struct, int fieldValue) {
        struct.set(partition_hint$LAYOUT, partition_hint$OFFSET, fieldValue);
    }

    private static final OfInt lane_hint$LAYOUT = (OfInt)$LAYOUT.select(groupElement("lane_hint"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t lane_hint
     * }
     */
    public static final OfInt lane_hint$layout() {
        return lane_hint$LAYOUT;
    }

    private static final long lane_hint$OFFSET = $LAYOUT.byteOffset(groupElement("lane_hint"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t lane_hint
     * }
     */
    public static final long lane_hint$offset() {
        return lane_hint$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t lane_hint
     * }
     */
    public static int lane_hint(MemorySegment struct) {
        return struct.get(lane_hint$LAYOUT, lane_hint$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t lane_hint
     * }
     */
    public static void lane_hint(MemorySegment struct, int fieldValue) {
        struct.set(lane_hint$LAYOUT, lane_hint$OFFSET, fieldValue);
    }

    private static final GroupLayout key$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("key"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * kr_span key
     * }
     */
    public static final GroupLayout key$layout() {
        return key$LAYOUT;
    }

    private static final long key$OFFSET = $LAYOUT.byteOffset(groupElement("key"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * kr_span key
     * }
     */
    public static final long key$offset() {
        return key$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * kr_span key
     * }
     */
    public static MemorySegment key(MemorySegment struct) {
        return struct.asSlice(key$OFFSET, key$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * kr_span key
     * }
     */
    public static void key(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, key$OFFSET, key$LAYOUT.byteSize());
    }

    private static final OfInt key_is_null$LAYOUT = (OfInt)$LAYOUT.select(groupElement("key_is_null"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t key_is_null
     * }
     */
    public static final OfInt key_is_null$layout() {
        return key_is_null$LAYOUT;
    }

    private static final long key_is_null$OFFSET = $LAYOUT.byteOffset(groupElement("key_is_null"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t key_is_null
     * }
     */
    public static final long key_is_null$offset() {
        return key_is_null$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t key_is_null
     * }
     */
    public static int key_is_null(MemorySegment struct) {
        return struct.get(key_is_null$LAYOUT, key_is_null$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t key_is_null
     * }
     */
    public static void key_is_null(MemorySegment struct, int fieldValue) {
        struct.set(key_is_null$LAYOUT, key_is_null$OFFSET, fieldValue);
    }

    private static final GroupLayout value$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("value"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * kr_span value
     * }
     */
    public static final GroupLayout value$layout() {
        return value$LAYOUT;
    }

    private static final long value$OFFSET = $LAYOUT.byteOffset(groupElement("value"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * kr_span value
     * }
     */
    public static final long value$offset() {
        return value$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * kr_span value
     * }
     */
    public static MemorySegment value(MemorySegment struct) {
        return struct.asSlice(value$OFFSET, value$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * kr_span value
     * }
     */
    public static void value(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, value$OFFSET, value$LAYOUT.byteSize());
    }

    private static final OfInt value_is_null$LAYOUT = (OfInt)$LAYOUT.select(groupElement("value_is_null"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t value_is_null
     * }
     */
    public static final OfInt value_is_null$layout() {
        return value_is_null$LAYOUT;
    }

    private static final long value_is_null$OFFSET = $LAYOUT.byteOffset(groupElement("value_is_null"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t value_is_null
     * }
     */
    public static final long value_is_null$offset() {
        return value_is_null$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t value_is_null
     * }
     */
    public static int value_is_null(MemorySegment struct) {
        return struct.get(value_is_null$LAYOUT, value_is_null$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t value_is_null
     * }
     */
    public static void value_is_null(MemorySegment struct, int fieldValue) {
        struct.set(value_is_null$LAYOUT, value_is_null$OFFSET, fieldValue);
    }

    private static final AddressLayout headers$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("headers"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const kr_header *headers
     * }
     */
    public static final AddressLayout headers$layout() {
        return headers$LAYOUT;
    }

    private static final long headers$OFFSET = $LAYOUT.byteOffset(groupElement("headers"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const kr_header *headers
     * }
     */
    public static final long headers$offset() {
        return headers$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const kr_header *headers
     * }
     */
    public static MemorySegment headers(MemorySegment struct) {
        return struct.get(headers$LAYOUT, headers$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const kr_header *headers
     * }
     */
    public static void headers(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(headers$LAYOUT, headers$OFFSET, fieldValue);
    }

    private static final OfInt header_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("header_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t header_count
     * }
     */
    public static final OfInt header_count$layout() {
        return header_count$LAYOUT;
    }

    private static final long header_count$OFFSET = $LAYOUT.byteOffset(groupElement("header_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t header_count
     * }
     */
    public static final long header_count$offset() {
        return header_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t header_count
     * }
     */
    public static int header_count(MemorySegment struct) {
        return struct.get(header_count$LAYOUT, header_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t header_count
     * }
     */
    public static void header_count(MemorySegment struct, int fieldValue) {
        struct.set(header_count$LAYOUT, header_count$OFFSET, fieldValue);
    }

    private static final OfLong timestamp_ms$LAYOUT = (OfLong)$LAYOUT.select(groupElement("timestamp_ms"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t timestamp_ms
     * }
     */
    public static final OfLong timestamp_ms$layout() {
        return timestamp_ms$LAYOUT;
    }

    private static final long timestamp_ms$OFFSET = $LAYOUT.byteOffset(groupElement("timestamp_ms"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t timestamp_ms
     * }
     */
    public static final long timestamp_ms$offset() {
        return timestamp_ms$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t timestamp_ms
     * }
     */
    public static long timestamp_ms(MemorySegment struct) {
        return struct.get(timestamp_ms$LAYOUT, timestamp_ms$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t timestamp_ms
     * }
     */
    public static void timestamp_ms(MemorySegment struct, long fieldValue) {
        struct.set(timestamp_ms$LAYOUT, timestamp_ms$OFFSET, fieldValue);
    }

    private static final OfLong user_token$LAYOUT = (OfLong)$LAYOUT.select(groupElement("user_token"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t user_token
     * }
     */
    public static final OfLong user_token$layout() {
        return user_token$LAYOUT;
    }

    private static final long user_token$OFFSET = $LAYOUT.byteOffset(groupElement("user_token"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t user_token
     * }
     */
    public static final long user_token$offset() {
        return user_token$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t user_token
     * }
     */
    public static long user_token(MemorySegment struct) {
        return struct.get(user_token$LAYOUT, user_token$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t user_token
     * }
     */
    public static void user_token(MemorySegment struct, long fieldValue) {
        struct.set(user_token$LAYOUT, user_token$OFFSET, fieldValue);
    }

    private static final OfLong delivery_timeout_ns$LAYOUT = (OfLong)$LAYOUT.select(groupElement("delivery_timeout_ns"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t delivery_timeout_ns
     * }
     */
    public static final OfLong delivery_timeout_ns$layout() {
        return delivery_timeout_ns$LAYOUT;
    }

    private static final long delivery_timeout_ns$OFFSET = $LAYOUT.byteOffset(groupElement("delivery_timeout_ns"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t delivery_timeout_ns
     * }
     */
    public static final long delivery_timeout_ns$offset() {
        return delivery_timeout_ns$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t delivery_timeout_ns
     * }
     */
    public static long delivery_timeout_ns(MemorySegment struct) {
        return struct.get(delivery_timeout_ns$LAYOUT, delivery_timeout_ns$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t delivery_timeout_ns
     * }
     */
    public static void delivery_timeout_ns(MemorySegment struct, long fieldValue) {
        struct.set(delivery_timeout_ns$LAYOUT, delivery_timeout_ns$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

