// Generated by jextract

package io.krkafka.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     uint32_t struct_size;
 *     uint32_t status;
 *     uint64_t generation;
 *     uint8_t topic_id[16];
 *     uint32_t partition_count;
 *     uint32_t reason;
 * }
 * }
 */
public class kr_topic_status {

    kr_topic_status() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        kr_kafka_h.C_INT.withName("struct_size"),
        kr_kafka_h.C_INT.withName("status"),
        kr_kafka_h.C_LONG_LONG.withName("generation"),
        MemoryLayout.sequenceLayout(16, kr_kafka_h.C_CHAR).withName("topic_id"),
        kr_kafka_h.C_INT.withName("partition_count"),
        kr_kafka_h.C_INT.withName("reason")
    ).withName("$anon$63:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt struct_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("struct_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final OfInt struct_size$layout() {
        return struct_size$LAYOUT;
    }

    private static final long struct_size$OFFSET = $LAYOUT.byteOffset(groupElement("struct_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static final long struct_size$offset() {
        return struct_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static int struct_size(MemorySegment struct) {
        return struct.get(struct_size$LAYOUT, struct_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t struct_size
     * }
     */
    public static void struct_size(MemorySegment struct, int fieldValue) {
        struct.set(struct_size$LAYOUT, struct_size$OFFSET, fieldValue);
    }

    private static final OfInt status$LAYOUT = (OfInt)$LAYOUT.select(groupElement("status"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t status
     * }
     */
    public static final OfInt status$layout() {
        return status$LAYOUT;
    }

    private static final long status$OFFSET = $LAYOUT.byteOffset(groupElement("status"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t status
     * }
     */
    public static final long status$offset() {
        return status$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t status
     * }
     */
    public static int status(MemorySegment struct) {
        return struct.get(status$LAYOUT, status$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t status
     * }
     */
    public static void status(MemorySegment struct, int fieldValue) {
        struct.set(status$LAYOUT, status$OFFSET, fieldValue);
    }

    private static final OfLong generation$LAYOUT = (OfLong)$LAYOUT.select(groupElement("generation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t generation
     * }
     */
    public static final OfLong generation$layout() {
        return generation$LAYOUT;
    }

    private static final long generation$OFFSET = $LAYOUT.byteOffset(groupElement("generation"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t generation
     * }
     */
    public static final long generation$offset() {
        return generation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t generation
     * }
     */
    public static long generation(MemorySegment struct) {
        return struct.get(generation$LAYOUT, generation$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t generation
     * }
     */
    public static void generation(MemorySegment struct, long fieldValue) {
        struct.set(generation$LAYOUT, generation$OFFSET, fieldValue);
    }

    private static final SequenceLayout topic_id$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("topic_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t topic_id[16]
     * }
     */
    public static final SequenceLayout topic_id$layout() {
        return topic_id$LAYOUT;
    }

    private static final long topic_id$OFFSET = $LAYOUT.byteOffset(groupElement("topic_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t topic_id[16]
     * }
     */
    public static final long topic_id$offset() {
        return topic_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t topic_id[16]
     * }
     */
    public static MemorySegment topic_id(MemorySegment struct) {
        return struct.asSlice(topic_id$OFFSET, topic_id$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t topic_id[16]
     * }
     */
    public static void topic_id(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, topic_id$OFFSET, topic_id$LAYOUT.byteSize());
    }

    private static long[] topic_id$DIMS = { 16 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint8_t topic_id[16]
     * }
     */
    public static long[] topic_id$dimensions() {
        return topic_id$DIMS;
    }
    private static final VarHandle topic_id$ELEM_HANDLE = topic_id$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint8_t topic_id[16]
     * }
     */
    public static byte topic_id(MemorySegment struct, long index0) {
        return (byte)topic_id$ELEM_HANDLE.get(struct, topic_id$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint8_t topic_id[16]
     * }
     */
    public static void topic_id(MemorySegment struct, long index0, byte fieldValue) {
        topic_id$ELEM_HANDLE.set(struct, topic_id$OFFSET, index0, fieldValue);
    }

    private static final OfInt partition_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("partition_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t partition_count
     * }
     */
    public static final OfInt partition_count$layout() {
        return partition_count$LAYOUT;
    }

    private static final long partition_count$OFFSET = $LAYOUT.byteOffset(groupElement("partition_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t partition_count
     * }
     */
    public static final long partition_count$offset() {
        return partition_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t partition_count
     * }
     */
    public static int partition_count(MemorySegment struct) {
        return struct.get(partition_count$LAYOUT, partition_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t partition_count
     * }
     */
    public static void partition_count(MemorySegment struct, int fieldValue) {
        struct.set(partition_count$LAYOUT, partition_count$OFFSET, fieldValue);
    }

    private static final OfInt reason$LAYOUT = (OfInt)$LAYOUT.select(groupElement("reason"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t reason
     * }
     */
    public static final OfInt reason$layout() {
        return reason$LAYOUT;
    }

    private static final long reason$OFFSET = $LAYOUT.byteOffset(groupElement("reason"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t reason
     * }
     */
    public static final long reason$offset() {
        return reason$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t reason
     * }
     */
    public static int reason(MemorySegment struct) {
        return struct.get(reason$LAYOUT, reason$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t reason
     * }
     */
    public static void reason(MemorySegment struct, int fieldValue) {
        struct.set(reason$LAYOUT, reason$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

