// Schema input SHA-256: 0924453c55999993509bfe8bc346955d2b1e731078df2ae1c7ccb6054fa02d7f
// @generated by kr-kafka-codegen. Do not edit.
#![allow(clippy::needless_borrow)]
use kr_kafka_protocol::{
    generated::*,
    wire::{DecodeLimits, EncodeLimits, Wire},
};
use serde_json::{Value, json};

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}
fn unhex(text: &str) -> Vec<u8> {
    assert_eq!(text.len() % 2, 0);
    (0..text.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&text[i..i + 2], 16).unwrap())
        .collect()
}
fn uuid(bytes: &[u8; 16]) -> String {
    let s = hex(bytes);
    format!(
        "{}-{}-{}-{}-{}",
        &s[..8],
        &s[8..12],
        &s[12..16],
        &s[16..20],
        &s[20..]
    )
}
fn check_fields(actual: &Value, expected: &Value) {
    match expected {
        Value::Object(fields) => {
            for (name, value) in fields {
                let actual = actual
                    .get(name)
                    .unwrap_or_else(|| panic!("missing decoded field {name}"));
                check_fields(actual, value);
            }
        }
        Value::Array(items) => {
            let actual = actual.as_array().unwrap();
            assert_eq!(actual.len(), items.len());
            for (a, e) in actual.iter().zip(items) {
                check_fields(a, e);
            }
        }
        _ => assert_eq!(actual, expected),
    }
}
#[test]
fn fixture_field_oracle_rejects_missing_mutated_and_truncated_values() {
    let expected = json!({"Topics":[{"Name":"topic","Id":7}]});
    for actual in [
        json!({}),
        json!({"Topics":[]}),
        json!({"Topics":[{"Name":"wrong","Id":7}]}),
        json!({"Topics":[{"Name":"topic"}]}),
    ] {
        assert!(std::panic::catch_unwind(|| check_fields(&actual, &expected)).is_err());
    }
    check_fields(&expected, &expected);
}
#[test]
fn java_fixtures_match_fields_defaults_and_wire_bytes_for_every_supported_version() {
    let source: Value = serde_json::from_str(include_str!("fixtures/java-wire.json")).unwrap();
    let cases = source["cases"].as_array().unwrap();
    let mut covered = std::collections::BTreeSet::new();
    for case in cases {
        let name = case["message"].as_str().unwrap();
        let version = case["version"].as_i64().unwrap() as i16;
        let bytes = unhex(case["hex"].as_str().unwrap());
        covered.insert((name, version));
        let mut expected = case["fields"].clone();
        // The Java v0 negotiation fixture deliberately populates two fields absent
        // from that wire version. Per-layout Rust types cannot represent them.
        if name == "ApiVersionsRequest" && version == 0 {
            expected
                .as_object_mut()
                .unwrap()
                .remove("ClientSoftwareName");
            expected
                .as_object_mut()
                .unwrap()
                .remove("ClientSoftwareVersion");
        }
        let result = std::panic::catch_unwind(|| match name {
            "ApiVersionsRequest" => {
                let decoded =
                    api_versions_request::decode(&bytes, version, DecodeLimits::default()).unwrap();
                let (fields, is_default, default_bytes) = match &decoded {
                    api_versions_request::View::V0(value) => {
                        let default = api_versions_request::View::V0(Default::default());
                        (
                            api_versions_request_v0_api_versions_request(value),
                            value.is_default(),
                            default
                                .plan(version, EncodeLimits::default())
                                .unwrap()
                                .to_vec()
                                .unwrap(),
                        )
                    }
                    api_versions_request::View::V3(value) => {
                        let default = api_versions_request::View::V3(Default::default());
                        (
                            api_versions_request_v3_api_versions_request(value),
                            value.is_default(),
                            default
                                .plan(version, EncodeLimits::default())
                                .unwrap()
                                .to_vec()
                                .unwrap(),
                        )
                    }
                };
                check_fields(&fields, &expected);
                if case["name"].as_str().unwrap().ends_with("-default") {
                    assert!(is_default);
                    assert_eq!(default_bytes, bytes);
                }
                assert_eq!(
                    decoded
                        .plan(version, EncodeLimits::default())
                        .unwrap()
                        .to_vec()
                        .unwrap(),
                    bytes
                );
                for end in 0..bytes.len() {
                    assert!(
                        api_versions_request::decode(
                            &bytes[..end],
                            version,
                            DecodeLimits::default()
                        )
                        .is_err(),
                        "accepted prefix {end}"
                    );
                }
                let mut trailing = bytes.clone();
                trailing.push(0);
                assert!(
                    api_versions_request::decode(&trailing, version, DecodeLimits::default())
                        .is_err()
                );
            }
            "ApiVersionsResponse" => {
                let decoded =
                    api_versions_response::decode(&bytes, version, DecodeLimits::default())
                        .unwrap();
                let (fields, is_default, default_bytes) = match &decoded {
                    api_versions_response::View::V0(value) => {
                        let default = api_versions_response::View::V0(Default::default());
                        (
                            api_versions_response_v0_api_versions_response(value),
                            value.is_default(),
                            default
                                .plan(version, EncodeLimits::default())
                                .unwrap()
                                .to_vec()
                                .unwrap(),
                        )
                    }
                    api_versions_response::View::V3(value) => {
                        let default = api_versions_response::View::V3(Default::default());
                        (
                            api_versions_response_v3_api_versions_response(value),
                            value.is_default(),
                            default
                                .plan(version, EncodeLimits::default())
                                .unwrap()
                                .to_vec()
                                .unwrap(),
                        )
                    }
                };
                check_fields(&fields, &expected);
                if case["name"].as_str().unwrap().ends_with("-default") {
                    assert!(is_default);
                    assert_eq!(default_bytes, bytes);
                }
                assert_eq!(
                    decoded
                        .plan(version, EncodeLimits::default())
                        .unwrap()
                        .to_vec()
                        .unwrap(),
                    bytes
                );
                for end in 0..bytes.len() {
                    assert!(
                        api_versions_response::decode(
                            &bytes[..end],
                            version,
                            DecodeLimits::default()
                        )
                        .is_err(),
                        "accepted prefix {end}"
                    );
                }
                let mut trailing = bytes.clone();
                trailing.push(0);
                assert!(
                    api_versions_response::decode(&trailing, version, DecodeLimits::default())
                        .is_err()
                );
            }
            "MetadataRequest" => {
                let decoded =
                    metadata_request::decode(&bytes, version, DecodeLimits::default()).unwrap();
                let (fields, is_default, default_bytes) = match &decoded {
                    metadata_request::View::V12(value) => {
                        let default = metadata_request::View::V12(Default::default());
                        (
                            metadata_request_v12_metadata_request(value),
                            value.is_default(),
                            default
                                .plan(version, EncodeLimits::default())
                                .unwrap()
                                .to_vec()
                                .unwrap(),
                        )
                    }
                };
                check_fields(&fields, &expected);
                if case["name"].as_str().unwrap().ends_with("-default") {
                    assert!(is_default);
                    assert_eq!(default_bytes, bytes);
                }
                assert_eq!(
                    decoded
                        .plan(version, EncodeLimits::default())
                        .unwrap()
                        .to_vec()
                        .unwrap(),
                    bytes
                );
                for end in 0..bytes.len() {
                    assert!(
                        metadata_request::decode(&bytes[..end], version, DecodeLimits::default())
                            .is_err(),
                        "accepted prefix {end}"
                    );
                }
                let mut trailing = bytes.clone();
                trailing.push(0);
                assert!(
                    metadata_request::decode(&trailing, version, DecodeLimits::default()).is_err()
                );
            }
            "MetadataResponse" => {
                let decoded =
                    metadata_response::decode(&bytes, version, DecodeLimits::default()).unwrap();
                let (fields, is_default, default_bytes) = match &decoded {
                    metadata_response::View::V12(value) => {
                        let default = metadata_response::View::V12(Default::default());
                        (
                            metadata_response_v12_metadata_response(value),
                            value.is_default(),
                            default
                                .plan(version, EncodeLimits::default())
                                .unwrap()
                                .to_vec()
                                .unwrap(),
                        )
                    }
                };
                check_fields(&fields, &expected);
                if case["name"].as_str().unwrap().ends_with("-default") {
                    assert!(is_default);
                    assert_eq!(default_bytes, bytes);
                }
                assert_eq!(
                    decoded
                        .plan(version, EncodeLimits::default())
                        .unwrap()
                        .to_vec()
                        .unwrap(),
                    bytes
                );
                for end in 0..bytes.len() {
                    assert!(
                        metadata_response::decode(&bytes[..end], version, DecodeLimits::default())
                            .is_err(),
                        "accepted prefix {end}"
                    );
                }
                let mut trailing = bytes.clone();
                trailing.push(0);
                assert!(
                    metadata_response::decode(&trailing, version, DecodeLimits::default()).is_err()
                );
            }
            "FetchRequest" => {
                let decoded =
                    fetch_request::decode(&bytes, version, DecodeLimits::default()).unwrap();
                let (fields, is_default, default_bytes) = match &decoded {
                    fetch_request::View::V13(value) => {
                        let default = fetch_request::View::V13(Default::default());
                        (
                            fetch_request_v13_fetch_request(value),
                            value.is_default(),
                            default
                                .plan(version, EncodeLimits::default())
                                .unwrap()
                                .to_vec()
                                .unwrap(),
                        )
                    }
                };
                check_fields(&fields, &expected);
                if case["name"].as_str().unwrap().ends_with("-default") {
                    assert!(is_default);
                    assert_eq!(default_bytes, bytes);
                }
                assert_eq!(
                    decoded
                        .plan(version, EncodeLimits::default())
                        .unwrap()
                        .to_vec()
                        .unwrap(),
                    bytes
                );
                for end in 0..bytes.len() {
                    assert!(
                        fetch_request::decode(&bytes[..end], version, DecodeLimits::default())
                            .is_err(),
                        "accepted prefix {end}"
                    );
                }
                let mut trailing = bytes.clone();
                trailing.push(0);
                assert!(
                    fetch_request::decode(&trailing, version, DecodeLimits::default()).is_err()
                );
            }
            "FetchResponse" => {
                let decoded =
                    fetch_response::decode(&bytes, version, DecodeLimits::default()).unwrap();
                let (fields, is_default, default_bytes) = match &decoded {
                    fetch_response::View::V13(value) => {
                        let default = fetch_response::View::V13(Default::default());
                        (
                            fetch_response_v13_fetch_response(value),
                            value.is_default(),
                            default
                                .plan(version, EncodeLimits::default())
                                .unwrap()
                                .to_vec()
                                .unwrap(),
                        )
                    }
                };
                check_fields(&fields, &expected);
                if case["name"].as_str().unwrap().ends_with("-default") {
                    assert!(is_default);
                    assert_eq!(default_bytes, bytes);
                }
                assert_eq!(
                    decoded
                        .plan(version, EncodeLimits::default())
                        .unwrap()
                        .to_vec()
                        .unwrap(),
                    bytes
                );
                for end in 0..bytes.len() {
                    assert!(
                        fetch_response::decode(&bytes[..end], version, DecodeLimits::default())
                            .is_err(),
                        "accepted prefix {end}"
                    );
                }
                let mut trailing = bytes.clone();
                trailing.push(0);
                assert!(
                    fetch_response::decode(&trailing, version, DecodeLimits::default()).is_err()
                );
            }
            "ProduceRequest" => {
                let decoded =
                    produce_request::decode(&bytes, version, DecodeLimits::default()).unwrap();
                let (fields, is_default, default_bytes) = match &decoded {
                    produce_request::View::V9(value) => {
                        let default = produce_request::View::V9(Default::default());
                        (
                            produce_request_v9_produce_request(value),
                            value.is_default(),
                            default
                                .plan(version, EncodeLimits::default())
                                .unwrap()
                                .to_vec()
                                .unwrap(),
                        )
                    }
                    produce_request::View::V13(value) => {
                        let default = produce_request::View::V13(Default::default());
                        (
                            produce_request_v13_produce_request(value),
                            value.is_default(),
                            default
                                .plan(version, EncodeLimits::default())
                                .unwrap()
                                .to_vec()
                                .unwrap(),
                        )
                    }
                };
                check_fields(&fields, &expected);
                if case["name"].as_str().unwrap().ends_with("-default") {
                    assert!(is_default);
                    assert_eq!(default_bytes, bytes);
                }
                assert_eq!(
                    decoded
                        .plan(version, EncodeLimits::default())
                        .unwrap()
                        .to_vec()
                        .unwrap(),
                    bytes
                );
                for end in 0..bytes.len() {
                    assert!(
                        produce_request::decode(&bytes[..end], version, DecodeLimits::default())
                            .is_err(),
                        "accepted prefix {end}"
                    );
                }
                let mut trailing = bytes.clone();
                trailing.push(0);
                assert!(
                    produce_request::decode(&trailing, version, DecodeLimits::default()).is_err()
                );
            }
            "ProduceResponse" => {
                let decoded =
                    produce_response::decode(&bytes, version, DecodeLimits::default()).unwrap();
                let (fields, is_default, default_bytes) = match &decoded {
                    produce_response::View::V9(value) => {
                        let default = produce_response::View::V9(Default::default());
                        (
                            produce_response_v9_produce_response(value),
                            value.is_default(),
                            default
                                .plan(version, EncodeLimits::default())
                                .unwrap()
                                .to_vec()
                                .unwrap(),
                        )
                    }
                    produce_response::View::V10(value) => {
                        let default = produce_response::View::V10(Default::default());
                        (
                            produce_response_v10_produce_response(value),
                            value.is_default(),
                            default
                                .plan(version, EncodeLimits::default())
                                .unwrap()
                                .to_vec()
                                .unwrap(),
                        )
                    }
                    produce_response::View::V13(value) => {
                        let default = produce_response::View::V13(Default::default());
                        (
                            produce_response_v13_produce_response(value),
                            value.is_default(),
                            default
                                .plan(version, EncodeLimits::default())
                                .unwrap()
                                .to_vec()
                                .unwrap(),
                        )
                    }
                };
                check_fields(&fields, &expected);
                if case["name"].as_str().unwrap().ends_with("-default") {
                    assert!(is_default);
                    assert_eq!(default_bytes, bytes);
                }
                assert_eq!(
                    decoded
                        .plan(version, EncodeLimits::default())
                        .unwrap()
                        .to_vec()
                        .unwrap(),
                    bytes
                );
                for end in 0..bytes.len() {
                    assert!(
                        produce_response::decode(&bytes[..end], version, DecodeLimits::default())
                            .is_err(),
                        "accepted prefix {end}"
                    );
                }
                let mut trailing = bytes.clone();
                trailing.push(0);
                assert!(
                    produce_response::decode(&trailing, version, DecodeLimits::default()).is_err()
                );
            }
            "InitProducerIdRequest" => {
                let decoded =
                    init_producer_id_request::decode(&bytes, version, DecodeLimits::default())
                        .unwrap();
                let (fields, is_default, default_bytes) = match &decoded {
                    init_producer_id_request::View::V4(value) => {
                        let default = init_producer_id_request::View::V4(Default::default());
                        (
                            init_producer_id_request_v4_init_producer_id_request(value),
                            value.is_default(),
                            default
                                .plan(version, EncodeLimits::default())
                                .unwrap()
                                .to_vec()
                                .unwrap(),
                        )
                    }
                };
                check_fields(&fields, &expected);
                if case["name"].as_str().unwrap().ends_with("-default") {
                    assert!(is_default);
                    assert_eq!(default_bytes, bytes);
                }
                assert_eq!(
                    decoded
                        .plan(version, EncodeLimits::default())
                        .unwrap()
                        .to_vec()
                        .unwrap(),
                    bytes
                );
                for end in 0..bytes.len() {
                    assert!(
                        init_producer_id_request::decode(
                            &bytes[..end],
                            version,
                            DecodeLimits::default()
                        )
                        .is_err(),
                        "accepted prefix {end}"
                    );
                }
                let mut trailing = bytes.clone();
                trailing.push(0);
                assert!(
                    init_producer_id_request::decode(&trailing, version, DecodeLimits::default())
                        .is_err()
                );
            }
            "InitProducerIdResponse" => {
                let decoded =
                    init_producer_id_response::decode(&bytes, version, DecodeLimits::default())
                        .unwrap();
                let (fields, is_default, default_bytes) = match &decoded {
                    init_producer_id_response::View::V4(value) => {
                        let default = init_producer_id_response::View::V4(Default::default());
                        (
                            init_producer_id_response_v4_init_producer_id_response(value),
                            value.is_default(),
                            default
                                .plan(version, EncodeLimits::default())
                                .unwrap()
                                .to_vec()
                                .unwrap(),
                        )
                    }
                };
                check_fields(&fields, &expected);
                if case["name"].as_str().unwrap().ends_with("-default") {
                    assert!(is_default);
                    assert_eq!(default_bytes, bytes);
                }
                assert_eq!(
                    decoded
                        .plan(version, EncodeLimits::default())
                        .unwrap()
                        .to_vec()
                        .unwrap(),
                    bytes
                );
                for end in 0..bytes.len() {
                    assert!(
                        init_producer_id_response::decode(
                            &bytes[..end],
                            version,
                            DecodeLimits::default()
                        )
                        .is_err(),
                        "accepted prefix {end}"
                    );
                }
                let mut trailing = bytes.clone();
                trailing.push(0);
                assert!(
                    init_producer_id_response::decode(&trailing, version, DecodeLimits::default())
                        .is_err()
                );
            }
            "SaslHandshakeRequest" => {
                let decoded =
                    sasl_handshake_request::decode(&bytes, version, DecodeLimits::default())
                        .unwrap();
                let (fields, is_default, default_bytes) = match &decoded {
                    sasl_handshake_request::View::V1(value) => {
                        let default = sasl_handshake_request::View::V1(Default::default());
                        (
                            sasl_handshake_request_v1_sasl_handshake_request(value),
                            value.is_default(),
                            default
                                .plan(version, EncodeLimits::default())
                                .unwrap()
                                .to_vec()
                                .unwrap(),
                        )
                    }
                };
                check_fields(&fields, &expected);
                if case["name"].as_str().unwrap().ends_with("-default") {
                    assert!(is_default);
                    assert_eq!(default_bytes, bytes);
                }
                assert_eq!(
                    decoded
                        .plan(version, EncodeLimits::default())
                        .unwrap()
                        .to_vec()
                        .unwrap(),
                    bytes
                );
                for end in 0..bytes.len() {
                    assert!(
                        sasl_handshake_request::decode(
                            &bytes[..end],
                            version,
                            DecodeLimits::default()
                        )
                        .is_err(),
                        "accepted prefix {end}"
                    );
                }
                let mut trailing = bytes.clone();
                trailing.push(0);
                assert!(
                    sasl_handshake_request::decode(&trailing, version, DecodeLimits::default())
                        .is_err()
                );
            }
            "SaslHandshakeResponse" => {
                let decoded =
                    sasl_handshake_response::decode(&bytes, version, DecodeLimits::default())
                        .unwrap();
                let (fields, is_default, default_bytes) = match &decoded {
                    sasl_handshake_response::View::V1(value) => {
                        let default = sasl_handshake_response::View::V1(Default::default());
                        (
                            sasl_handshake_response_v1_sasl_handshake_response(value),
                            value.is_default(),
                            default
                                .plan(version, EncodeLimits::default())
                                .unwrap()
                                .to_vec()
                                .unwrap(),
                        )
                    }
                };
                check_fields(&fields, &expected);
                if case["name"].as_str().unwrap().ends_with("-default") {
                    assert!(is_default);
                    assert_eq!(default_bytes, bytes);
                }
                assert_eq!(
                    decoded
                        .plan(version, EncodeLimits::default())
                        .unwrap()
                        .to_vec()
                        .unwrap(),
                    bytes
                );
                for end in 0..bytes.len() {
                    assert!(
                        sasl_handshake_response::decode(
                            &bytes[..end],
                            version,
                            DecodeLimits::default()
                        )
                        .is_err(),
                        "accepted prefix {end}"
                    );
                }
                let mut trailing = bytes.clone();
                trailing.push(0);
                assert!(
                    sasl_handshake_response::decode(&trailing, version, DecodeLimits::default())
                        .is_err()
                );
            }
            "SaslAuthenticateRequest" => {
                let decoded =
                    sasl_authenticate_request::decode(&bytes, version, DecodeLimits::default())
                        .unwrap();
                let (fields, is_default, default_bytes) = match &decoded {
                    sasl_authenticate_request::View::V2(value) => {
                        let default = sasl_authenticate_request::View::V2(Default::default());
                        (
                            sasl_authenticate_request_v2_sasl_authenticate_request(value),
                            value.is_default(),
                            default
                                .plan(version, EncodeLimits::default())
                                .unwrap()
                                .to_vec()
                                .unwrap(),
                        )
                    }
                };
                check_fields(&fields, &expected);
                if case["name"].as_str().unwrap().ends_with("-default") {
                    assert!(is_default);
                    assert_eq!(default_bytes, bytes);
                }
                assert_eq!(
                    decoded
                        .plan(version, EncodeLimits::default())
                        .unwrap()
                        .to_vec()
                        .unwrap(),
                    bytes
                );
                for end in 0..bytes.len() {
                    assert!(
                        sasl_authenticate_request::decode(
                            &bytes[..end],
                            version,
                            DecodeLimits::default()
                        )
                        .is_err(),
                        "accepted prefix {end}"
                    );
                }
                let mut trailing = bytes.clone();
                trailing.push(0);
                assert!(
                    sasl_authenticate_request::decode(&trailing, version, DecodeLimits::default())
                        .is_err()
                );
            }
            "SaslAuthenticateResponse" => {
                let decoded =
                    sasl_authenticate_response::decode(&bytes, version, DecodeLimits::default())
                        .unwrap();
                let (fields, is_default, default_bytes) = match &decoded {
                    sasl_authenticate_response::View::V2(value) => {
                        let default = sasl_authenticate_response::View::V2(Default::default());
                        (
                            sasl_authenticate_response_v2_sasl_authenticate_response(value),
                            value.is_default(),
                            default
                                .plan(version, EncodeLimits::default())
                                .unwrap()
                                .to_vec()
                                .unwrap(),
                        )
                    }
                };
                check_fields(&fields, &expected);
                if case["name"].as_str().unwrap().ends_with("-default") {
                    assert!(is_default);
                    assert_eq!(default_bytes, bytes);
                }
                assert_eq!(
                    decoded
                        .plan(version, EncodeLimits::default())
                        .unwrap()
                        .to_vec()
                        .unwrap(),
                    bytes
                );
                for end in 0..bytes.len() {
                    assert!(
                        sasl_authenticate_response::decode(
                            &bytes[..end],
                            version,
                            DecodeLimits::default()
                        )
                        .is_err(),
                        "accepted prefix {end}"
                    );
                }
                let mut trailing = bytes.clone();
                trailing.push(0);
                assert!(
                    sasl_authenticate_response::decode(&trailing, version, DecodeLimits::default())
                        .is_err()
                );
            }
            "RequestHeader" => {
                let decoded =
                    request_header::decode(&bytes, version, DecodeLimits::default()).unwrap();
                let (fields, is_default, default_bytes) = match &decoded {
                    request_header::View::V1(value) => {
                        let default = request_header::View::V1(Default::default());
                        (
                            request_header_v1_request_header(value),
                            value.is_default(),
                            default
                                .plan(version, EncodeLimits::default())
                                .unwrap()
                                .to_vec()
                                .unwrap(),
                        )
                    }
                    request_header::View::V2(value) => {
                        let default = request_header::View::V2(Default::default());
                        (
                            request_header_v2_request_header(value),
                            value.is_default(),
                            default
                                .plan(version, EncodeLimits::default())
                                .unwrap()
                                .to_vec()
                                .unwrap(),
                        )
                    }
                };
                check_fields(&fields, &expected);
                if case["name"].as_str().unwrap().ends_with("-default") {
                    assert!(is_default);
                    assert_eq!(default_bytes, bytes);
                }
                assert_eq!(
                    decoded
                        .plan(version, EncodeLimits::default())
                        .unwrap()
                        .to_vec()
                        .unwrap(),
                    bytes
                );
                for end in 0..bytes.len() {
                    assert!(
                        request_header::decode(&bytes[..end], version, DecodeLimits::default())
                            .is_err(),
                        "accepted prefix {end}"
                    );
                }
                let mut trailing = bytes.clone();
                trailing.push(0);
                assert!(
                    request_header::decode(&trailing, version, DecodeLimits::default()).is_err()
                );
            }
            "ResponseHeader" => {
                let decoded =
                    response_header::decode(&bytes, version, DecodeLimits::default()).unwrap();
                let (fields, is_default, default_bytes) = match &decoded {
                    response_header::View::V0(value) => {
                        let default = response_header::View::V0(Default::default());
                        (
                            response_header_v0_response_header(value),
                            value.is_default(),
                            default
                                .plan(version, EncodeLimits::default())
                                .unwrap()
                                .to_vec()
                                .unwrap(),
                        )
                    }
                    response_header::View::V1(value) => {
                        let default = response_header::View::V1(Default::default());
                        (
                            response_header_v1_response_header(value),
                            value.is_default(),
                            default
                                .plan(version, EncodeLimits::default())
                                .unwrap()
                                .to_vec()
                                .unwrap(),
                        )
                    }
                };
                check_fields(&fields, &expected);
                if case["name"].as_str().unwrap().ends_with("-default") {
                    assert!(is_default);
                    assert_eq!(default_bytes, bytes);
                }
                assert_eq!(
                    decoded
                        .plan(version, EncodeLimits::default())
                        .unwrap()
                        .to_vec()
                        .unwrap(),
                    bytes
                );
                for end in 0..bytes.len() {
                    assert!(
                        response_header::decode(&bytes[..end], version, DecodeLimits::default())
                            .is_err(),
                        "accepted prefix {end}"
                    );
                }
                let mut trailing = bytes.clone();
                trailing.push(0);
                assert!(
                    response_header::decode(&trailing, version, DecodeLimits::default()).is_err()
                );
            }
            _ => panic!("unexpected fixture message {name}"),
        });
        assert!(result.is_ok(), "fixture {} failed", case["name"]);
    }
    assert!(
        covered.contains(&("ApiVersionsRequest", 0)),
        "missing Java fixture"
    );
    assert!(
        covered.contains(&("ApiVersionsRequest", 3)),
        "missing Java fixture"
    );
    assert!(
        covered.contains(&("ApiVersionsResponse", 0)),
        "missing Java fixture"
    );
    assert!(
        covered.contains(&("ApiVersionsResponse", 3)),
        "missing Java fixture"
    );
    assert!(
        covered.contains(&("MetadataRequest", 12)),
        "missing Java fixture"
    );
    assert!(
        covered.contains(&("MetadataResponse", 12)),
        "missing Java fixture"
    );
    assert!(
        covered.contains(&("FetchRequest", 13)),
        "missing Java fixture"
    );
    assert!(
        covered.contains(&("FetchResponse", 13)),
        "missing Java fixture"
    );
    assert!(
        covered.contains(&("ProduceRequest", 9)),
        "missing Java fixture"
    );
    assert!(
        covered.contains(&("ProduceRequest", 10)),
        "missing Java fixture"
    );
    assert!(
        covered.contains(&("ProduceRequest", 11)),
        "missing Java fixture"
    );
    assert!(
        covered.contains(&("ProduceRequest", 12)),
        "missing Java fixture"
    );
    assert!(
        covered.contains(&("ProduceRequest", 13)),
        "missing Java fixture"
    );
    assert!(
        covered.contains(&("ProduceResponse", 9)),
        "missing Java fixture"
    );
    assert!(
        covered.contains(&("ProduceResponse", 10)),
        "missing Java fixture"
    );
    assert!(
        covered.contains(&("ProduceResponse", 11)),
        "missing Java fixture"
    );
    assert!(
        covered.contains(&("ProduceResponse", 12)),
        "missing Java fixture"
    );
    assert!(
        covered.contains(&("ProduceResponse", 13)),
        "missing Java fixture"
    );
    assert!(
        covered.contains(&("InitProducerIdRequest", 4)),
        "missing Java fixture"
    );
    assert!(
        covered.contains(&("InitProducerIdResponse", 4)),
        "missing Java fixture"
    );
    assert!(
        covered.contains(&("SaslHandshakeRequest", 1)),
        "missing Java fixture"
    );
    assert!(
        covered.contains(&("SaslHandshakeResponse", 1)),
        "missing Java fixture"
    );
    assert!(
        covered.contains(&("SaslAuthenticateRequest", 2)),
        "missing Java fixture"
    );
    assert!(
        covered.contains(&("SaslAuthenticateResponse", 2)),
        "missing Java fixture"
    );
    assert!(
        covered.contains(&("RequestHeader", 1)),
        "missing Java fixture"
    );
    assert!(
        covered.contains(&("RequestHeader", 2)),
        "missing Java fixture"
    );
    assert!(
        covered.contains(&("ResponseHeader", 0)),
        "missing Java fixture"
    );
    assert!(
        covered.contains(&("ResponseHeader", 1)),
        "missing Java fixture"
    );
}
fn api_versions_request_v0_api_versions_request(
    value: &api_versions_request::v0::ApiVersionsRequest<'_>,
) -> Value {
    json!({
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn api_versions_request_v3_api_versions_request(
    value: &api_versions_request::v3::ApiVersionsRequest<'_>,
) -> Value {
    json!({
    "ClientSoftwareName": json!(&value.client_software_name),
    "ClientSoftwareVersion": json!(&value.client_software_version),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn api_versions_response_v0_api_versions_response(
    value: &api_versions_response::v0::ApiVersionsResponse<'_>,
) -> Value {
    json!({
    "ErrorCode": json!(&value.error_code),
    "ApiKeys": (&value.api_keys).iter().map(|item| { let item=item.unwrap(); api_versions_response_v0_api_version(&item) }).collect::<Vec<_>>(),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn api_versions_response_v0_api_version(
    value: &api_versions_response::v0::ApiVersion<'_>,
) -> Value {
    json!({
    "ApiKey": json!(&value.api_key),
    "MinVersion": json!(&value.min_version),
    "MaxVersion": json!(&value.max_version),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn api_versions_response_v3_api_versions_response(
    value: &api_versions_response::v3::ApiVersionsResponse<'_>,
) -> Value {
    json!({
    "ErrorCode": json!(&value.error_code),
    "ApiKeys": (&value.api_keys).iter().map(|item| { let item=item.unwrap(); api_versions_response_v3_api_version(&item) }).collect::<Vec<_>>(),
    "ThrottleTimeMs": json!(&value.throttle_time_ms),
    "SupportedFeatures": (&value.supported_features).iter().map(|item| { let item=item.unwrap(); api_versions_response_v3_supported_feature_key(&item) }).collect::<Vec<_>>(),
    "FinalizedFeaturesEpoch": json!(&value.finalized_features_epoch),
    "FinalizedFeatures": (&value.finalized_features).iter().map(|item| { let item=item.unwrap(); api_versions_response_v3_finalized_feature_key(&item) }).collect::<Vec<_>>(),
    "ZkMigrationReady": json!(&value.zk_migration_ready),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn api_versions_response_v3_api_version(
    value: &api_versions_response::v3::ApiVersion<'_>,
) -> Value {
    json!({
    "ApiKey": json!(&value.api_key),
    "MinVersion": json!(&value.min_version),
    "MaxVersion": json!(&value.max_version),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn api_versions_response_v3_supported_feature_key(
    value: &api_versions_response::v3::SupportedFeatureKey<'_>,
) -> Value {
    json!({
    "Name": json!(&value.name),
    "MinVersion": json!(&value.min_version),
    "MaxVersion": json!(&value.max_version),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn api_versions_response_v3_finalized_feature_key(
    value: &api_versions_response::v3::FinalizedFeatureKey<'_>,
) -> Value {
    json!({
    "Name": json!(&value.name),
    "MaxVersionLevel": json!(&value.max_version_level),
    "MinVersionLevel": json!(&value.min_version_level),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn metadata_request_v12_metadata_request(
    value: &metadata_request::v12::MetadataRequest<'_>,
) -> Value {
    json!({
    "Topics": value.topics.as_ref().map(|v| (v).iter().map(|item| { let item=item.unwrap(); metadata_request_v12_metadata_request_topic(&item) }).collect::<Vec<_>>()),
    "AllowAutoTopicCreation": json!(&value.allow_auto_topic_creation),
    "IncludeTopicAuthorizedOperations": json!(&value.include_topic_authorized_operations),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn metadata_request_v12_metadata_request_topic(
    value: &metadata_request::v12::MetadataRequestTopic<'_>,
) -> Value {
    json!({
    "TopicId": uuid(&value.topic_id),
    "Name": value.name.as_ref().map(|v| json!(v)),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn metadata_response_v12_metadata_response(
    value: &metadata_response::v12::MetadataResponse<'_>,
) -> Value {
    json!({
    "ThrottleTimeMs": json!(&value.throttle_time_ms),
    "Brokers": (&value.brokers).iter().map(|item| { let item=item.unwrap(); metadata_response_v12_metadata_response_broker(&item) }).collect::<Vec<_>>(),
    "ClusterId": value.cluster_id.as_ref().map(|v| json!(v)),
    "ControllerId": json!(&value.controller_id),
    "Topics": (&value.topics).iter().map(|item| { let item=item.unwrap(); metadata_response_v12_metadata_response_topic(&item) }).collect::<Vec<_>>(),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn metadata_response_v12_metadata_response_broker(
    value: &metadata_response::v12::MetadataResponseBroker<'_>,
) -> Value {
    json!({
    "NodeId": json!(&value.node_id),
    "Host": json!(&value.host),
    "Port": json!(&value.port),
    "Rack": value.rack.as_ref().map(|v| json!(v)),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn metadata_response_v12_metadata_response_topic(
    value: &metadata_response::v12::MetadataResponseTopic<'_>,
) -> Value {
    json!({
    "ErrorCode": json!(&value.error_code),
    "Name": value.name.as_ref().map(|v| json!(v)),
    "TopicId": uuid(&value.topic_id),
    "IsInternal": json!(&value.is_internal),
    "Partitions": (&value.partitions).iter().map(|item| { let item=item.unwrap(); metadata_response_v12_metadata_response_partition(&item) }).collect::<Vec<_>>(),
    "TopicAuthorizedOperations": json!(&value.topic_authorized_operations),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn metadata_response_v12_metadata_response_partition(
    value: &metadata_response::v12::MetadataResponsePartition<'_>,
) -> Value {
    json!({
    "ErrorCode": json!(&value.error_code),
    "PartitionIndex": json!(&value.partition_index),
    "LeaderId": json!(&value.leader_id),
    "LeaderEpoch": json!(&value.leader_epoch),
    "ReplicaNodes": (&value.replica_nodes).iter().map(|item| { let item=item.unwrap(); json!(&item) }).collect::<Vec<_>>(),
    "IsrNodes": (&value.isr_nodes).iter().map(|item| { let item=item.unwrap(); json!(&item) }).collect::<Vec<_>>(),
    "OfflineReplicas": (&value.offline_replicas).iter().map(|item| { let item=item.unwrap(); json!(&item) }).collect::<Vec<_>>(),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn fetch_request_v13_fetch_request(value: &fetch_request::v13::FetchRequest<'_>) -> Value {
    json!({
    "ClusterId": value.cluster_id.as_ref().map(|v| json!(v)),
    "ReplicaId": json!(&value.replica_id),
    "MaxWaitMs": json!(&value.max_wait_ms),
    "MinBytes": json!(&value.min_bytes),
    "MaxBytes": json!(&value.max_bytes),
    "IsolationLevel": json!(&value.isolation_level),
    "SessionId": json!(&value.session_id),
    "SessionEpoch": json!(&value.session_epoch),
    "Topics": (&value.topics).iter().map(|item| { let item=item.unwrap(); fetch_request_v13_fetch_topic(&item) }).collect::<Vec<_>>(),
    "ForgottenTopicsData": (&value.forgotten_topics_data).iter().map(|item| { let item=item.unwrap(); fetch_request_v13_forgotten_topic(&item) }).collect::<Vec<_>>(),
    "RackId": json!(&value.rack_id),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn fetch_request_v13_fetch_topic(value: &fetch_request::v13::FetchTopic<'_>) -> Value {
    json!({
    "TopicId": uuid(&value.topic_id),
    "Partitions": (&value.partitions).iter().map(|item| { let item=item.unwrap(); fetch_request_v13_fetch_partition(&item) }).collect::<Vec<_>>(),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn fetch_request_v13_fetch_partition(value: &fetch_request::v13::FetchPartition<'_>) -> Value {
    json!({
    "Partition": json!(&value.partition),
    "CurrentLeaderEpoch": json!(&value.current_leader_epoch),
    "FetchOffset": json!(&value.fetch_offset),
    "LastFetchedEpoch": json!(&value.last_fetched_epoch),
    "LogStartOffset": json!(&value.log_start_offset),
    "PartitionMaxBytes": json!(&value.partition_max_bytes),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn fetch_request_v13_forgotten_topic(value: &fetch_request::v13::ForgottenTopic<'_>) -> Value {
    json!({
    "TopicId": uuid(&value.topic_id),
    "Partitions": (&value.partitions).iter().map(|item| { let item=item.unwrap(); json!(&item) }).collect::<Vec<_>>(),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn fetch_response_v13_fetch_response(value: &fetch_response::v13::FetchResponse<'_>) -> Value {
    json!({
    "ThrottleTimeMs": json!(&value.throttle_time_ms),
    "ErrorCode": json!(&value.error_code),
    "SessionId": json!(&value.session_id),
    "Responses": (&value.responses).iter().map(|item| { let item=item.unwrap(); fetch_response_v13_fetchable_topic_response(&item) }).collect::<Vec<_>>(),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn fetch_response_v13_fetchable_topic_response(
    value: &fetch_response::v13::FetchableTopicResponse<'_>,
) -> Value {
    json!({
    "TopicId": uuid(&value.topic_id),
    "Partitions": (&value.partitions).iter().map(|item| { let item=item.unwrap(); fetch_response_v13_partition_data(&item) }).collect::<Vec<_>>(),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn fetch_response_v13_partition_data(value: &fetch_response::v13::PartitionData<'_>) -> Value {
    json!({
    "PartitionIndex": json!(&value.partition_index),
    "ErrorCode": json!(&value.error_code),
    "HighWatermark": json!(&value.high_watermark),
    "LastStableOffset": json!(&value.last_stable_offset),
    "LogStartOffset": json!(&value.log_start_offset),
    "DivergingEpoch": fetch_response_v13_epoch_end_offset(&value.diverging_epoch),
    "CurrentLeader": fetch_response_v13_leader_id_and_epoch(&value.current_leader),
    "SnapshotId": fetch_response_v13_snapshot_id(&value.snapshot_id),
    "AbortedTransactions": value.aborted_transactions.as_ref().map(|v| (v).iter().map(|item| { let item=item.unwrap(); fetch_response_v13_aborted_transaction(&item) }).collect::<Vec<_>>()),
    "PreferredReadReplica": json!(&value.preferred_read_replica),
    "Records": value.records.as_ref().map(|v| json!({"hex": match v { kr_kafka_protocol::wire::Records::Borrowed(bytes) => hex(bytes), _ => panic!("decoded records must borrow") } })),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn fetch_response_v13_epoch_end_offset(value: &fetch_response::v13::EpochEndOffset<'_>) -> Value {
    json!({
    "Epoch": json!(&value.epoch),
    "EndOffset": json!(&value.end_offset),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn fetch_response_v13_leader_id_and_epoch(
    value: &fetch_response::v13::LeaderIdAndEpoch<'_>,
) -> Value {
    json!({
    "LeaderId": json!(&value.leader_id),
    "LeaderEpoch": json!(&value.leader_epoch),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn fetch_response_v13_snapshot_id(value: &fetch_response::v13::SnapshotId<'_>) -> Value {
    json!({
    "EndOffset": json!(&value.end_offset),
    "Epoch": json!(&value.epoch),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn fetch_response_v13_aborted_transaction(
    value: &fetch_response::v13::AbortedTransaction<'_>,
) -> Value {
    json!({
    "ProducerId": json!(&value.producer_id),
    "FirstOffset": json!(&value.first_offset),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn produce_request_v9_produce_request(value: &produce_request::v9::ProduceRequest<'_>) -> Value {
    json!({
    "TransactionalId": value.transactional_id.as_ref().map(|v| json!(v)),
    "Acks": json!(&value.acks),
    "TimeoutMs": json!(&value.timeout_ms),
    "TopicData": (&value.topic_data).iter().map(|item| { let item=item.unwrap(); produce_request_v9_topic_produce_data(&item) }).collect::<Vec<_>>(),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn produce_request_v9_topic_produce_data(
    value: &produce_request::v9::TopicProduceData<'_>,
) -> Value {
    json!({
    "Name": json!(&value.name),
    "PartitionData": (&value.partition_data).iter().map(|item| { let item=item.unwrap(); produce_request_v9_partition_produce_data(&item) }).collect::<Vec<_>>(),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn produce_request_v9_partition_produce_data(
    value: &produce_request::v9::PartitionProduceData<'_>,
) -> Value {
    json!({
    "Index": json!(&value.index),
    "Records": value.records.as_ref().map(|v| json!({"hex": match v { kr_kafka_protocol::wire::Records::Borrowed(bytes) => hex(bytes), _ => panic!("decoded records must borrow") } })),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn produce_request_v13_produce_request(value: &produce_request::v13::ProduceRequest<'_>) -> Value {
    json!({
    "TransactionalId": value.transactional_id.as_ref().map(|v| json!(v)),
    "Acks": json!(&value.acks),
    "TimeoutMs": json!(&value.timeout_ms),
    "TopicData": (&value.topic_data).iter().map(|item| { let item=item.unwrap(); produce_request_v13_topic_produce_data(&item) }).collect::<Vec<_>>(),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn produce_request_v13_topic_produce_data(
    value: &produce_request::v13::TopicProduceData<'_>,
) -> Value {
    json!({
    "TopicId": uuid(&value.topic_id),
    "PartitionData": (&value.partition_data).iter().map(|item| { let item=item.unwrap(); produce_request_v13_partition_produce_data(&item) }).collect::<Vec<_>>(),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn produce_request_v13_partition_produce_data(
    value: &produce_request::v13::PartitionProduceData<'_>,
) -> Value {
    json!({
    "Index": json!(&value.index),
    "Records": value.records.as_ref().map(|v| json!({"hex": match v { kr_kafka_protocol::wire::Records::Borrowed(bytes) => hex(bytes), _ => panic!("decoded records must borrow") } })),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn produce_response_v9_produce_response(
    value: &produce_response::v9::ProduceResponse<'_>,
) -> Value {
    json!({
    "Responses": (&value.responses).iter().map(|item| { let item=item.unwrap(); produce_response_v9_topic_produce_response(&item) }).collect::<Vec<_>>(),
    "ThrottleTimeMs": json!(&value.throttle_time_ms),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn produce_response_v9_topic_produce_response(
    value: &produce_response::v9::TopicProduceResponse<'_>,
) -> Value {
    json!({
    "Name": json!(&value.name),
    "PartitionResponses": (&value.partition_responses).iter().map(|item| { let item=item.unwrap(); produce_response_v9_partition_produce_response(&item) }).collect::<Vec<_>>(),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn produce_response_v9_partition_produce_response(
    value: &produce_response::v9::PartitionProduceResponse<'_>,
) -> Value {
    json!({
    "Index": json!(&value.index),
    "ErrorCode": json!(&value.error_code),
    "BaseOffset": json!(&value.base_offset),
    "LogAppendTimeMs": json!(&value.log_append_time_ms),
    "LogStartOffset": json!(&value.log_start_offset),
    "RecordErrors": (&value.record_errors).iter().map(|item| { let item=item.unwrap(); produce_response_v9_batch_index_and_error_message(&item) }).collect::<Vec<_>>(),
    "ErrorMessage": value.error_message.as_ref().map(|v| json!(v)),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn produce_response_v9_batch_index_and_error_message(
    value: &produce_response::v9::BatchIndexAndErrorMessage<'_>,
) -> Value {
    json!({
    "BatchIndex": json!(&value.batch_index),
    "BatchIndexErrorMessage": value.batch_index_error_message.as_ref().map(|v| json!(v)),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn produce_response_v10_produce_response(
    value: &produce_response::v10::ProduceResponse<'_>,
) -> Value {
    json!({
    "Responses": (&value.responses).iter().map(|item| { let item=item.unwrap(); produce_response_v10_topic_produce_response(&item) }).collect::<Vec<_>>(),
    "ThrottleTimeMs": json!(&value.throttle_time_ms),
    "NodeEndpoints": (&value.node_endpoints).iter().map(|item| { let item=item.unwrap(); produce_response_v10_node_endpoint(&item) }).collect::<Vec<_>>(),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn produce_response_v10_topic_produce_response(
    value: &produce_response::v10::TopicProduceResponse<'_>,
) -> Value {
    json!({
    "Name": json!(&value.name),
    "PartitionResponses": (&value.partition_responses).iter().map(|item| { let item=item.unwrap(); produce_response_v10_partition_produce_response(&item) }).collect::<Vec<_>>(),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn produce_response_v10_partition_produce_response(
    value: &produce_response::v10::PartitionProduceResponse<'_>,
) -> Value {
    json!({
    "Index": json!(&value.index),
    "ErrorCode": json!(&value.error_code),
    "BaseOffset": json!(&value.base_offset),
    "LogAppendTimeMs": json!(&value.log_append_time_ms),
    "LogStartOffset": json!(&value.log_start_offset),
    "RecordErrors": (&value.record_errors).iter().map(|item| { let item=item.unwrap(); produce_response_v10_batch_index_and_error_message(&item) }).collect::<Vec<_>>(),
    "ErrorMessage": value.error_message.as_ref().map(|v| json!(v)),
    "CurrentLeader": produce_response_v10_leader_id_and_epoch(&value.current_leader),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn produce_response_v10_batch_index_and_error_message(
    value: &produce_response::v10::BatchIndexAndErrorMessage<'_>,
) -> Value {
    json!({
    "BatchIndex": json!(&value.batch_index),
    "BatchIndexErrorMessage": value.batch_index_error_message.as_ref().map(|v| json!(v)),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn produce_response_v10_leader_id_and_epoch(
    value: &produce_response::v10::LeaderIdAndEpoch<'_>,
) -> Value {
    json!({
    "LeaderId": json!(&value.leader_id),
    "LeaderEpoch": json!(&value.leader_epoch),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn produce_response_v10_node_endpoint(value: &produce_response::v10::NodeEndpoint<'_>) -> Value {
    json!({
    "NodeId": json!(&value.node_id),
    "Host": json!(&value.host),
    "Port": json!(&value.port),
    "Rack": value.rack.as_ref().map(|v| json!(v)),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn produce_response_v13_produce_response(
    value: &produce_response::v13::ProduceResponse<'_>,
) -> Value {
    json!({
    "Responses": (&value.responses).iter().map(|item| { let item=item.unwrap(); produce_response_v13_topic_produce_response(&item) }).collect::<Vec<_>>(),
    "ThrottleTimeMs": json!(&value.throttle_time_ms),
    "NodeEndpoints": (&value.node_endpoints).iter().map(|item| { let item=item.unwrap(); produce_response_v13_node_endpoint(&item) }).collect::<Vec<_>>(),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn produce_response_v13_topic_produce_response(
    value: &produce_response::v13::TopicProduceResponse<'_>,
) -> Value {
    json!({
    "TopicId": uuid(&value.topic_id),
    "PartitionResponses": (&value.partition_responses).iter().map(|item| { let item=item.unwrap(); produce_response_v13_partition_produce_response(&item) }).collect::<Vec<_>>(),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn produce_response_v13_partition_produce_response(
    value: &produce_response::v13::PartitionProduceResponse<'_>,
) -> Value {
    json!({
    "Index": json!(&value.index),
    "ErrorCode": json!(&value.error_code),
    "BaseOffset": json!(&value.base_offset),
    "LogAppendTimeMs": json!(&value.log_append_time_ms),
    "LogStartOffset": json!(&value.log_start_offset),
    "RecordErrors": (&value.record_errors).iter().map(|item| { let item=item.unwrap(); produce_response_v13_batch_index_and_error_message(&item) }).collect::<Vec<_>>(),
    "ErrorMessage": value.error_message.as_ref().map(|v| json!(v)),
    "CurrentLeader": produce_response_v13_leader_id_and_epoch(&value.current_leader),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn produce_response_v13_batch_index_and_error_message(
    value: &produce_response::v13::BatchIndexAndErrorMessage<'_>,
) -> Value {
    json!({
    "BatchIndex": json!(&value.batch_index),
    "BatchIndexErrorMessage": value.batch_index_error_message.as_ref().map(|v| json!(v)),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn produce_response_v13_leader_id_and_epoch(
    value: &produce_response::v13::LeaderIdAndEpoch<'_>,
) -> Value {
    json!({
    "LeaderId": json!(&value.leader_id),
    "LeaderEpoch": json!(&value.leader_epoch),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn produce_response_v13_node_endpoint(value: &produce_response::v13::NodeEndpoint<'_>) -> Value {
    json!({
    "NodeId": json!(&value.node_id),
    "Host": json!(&value.host),
    "Port": json!(&value.port),
    "Rack": value.rack.as_ref().map(|v| json!(v)),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn init_producer_id_request_v4_init_producer_id_request(
    value: &init_producer_id_request::v4::InitProducerIdRequest<'_>,
) -> Value {
    json!({
    "TransactionalId": value.transactional_id.as_ref().map(|v| json!(v)),
    "TransactionTimeoutMs": json!(&value.transaction_timeout_ms),
    "ProducerId": json!(&value.producer_id),
    "ProducerEpoch": json!(&value.producer_epoch),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn init_producer_id_response_v4_init_producer_id_response(
    value: &init_producer_id_response::v4::InitProducerIdResponse<'_>,
) -> Value {
    json!({
    "ThrottleTimeMs": json!(&value.throttle_time_ms),
    "ErrorCode": json!(&value.error_code),
    "ProducerId": json!(&value.producer_id),
    "ProducerEpoch": json!(&value.producer_epoch),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn sasl_handshake_request_v1_sasl_handshake_request(
    value: &sasl_handshake_request::v1::SaslHandshakeRequest<'_>,
) -> Value {
    json!({
    "Mechanism": json!(&value.mechanism),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn sasl_handshake_response_v1_sasl_handshake_response(
    value: &sasl_handshake_response::v1::SaslHandshakeResponse<'_>,
) -> Value {
    json!({
    "ErrorCode": json!(&value.error_code),
    "Mechanisms": (&value.mechanisms).iter().map(|item| { let item=item.unwrap(); json!(&item) }).collect::<Vec<_>>(),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn sasl_authenticate_request_v2_sasl_authenticate_request(
    value: &sasl_authenticate_request::v2::SaslAuthenticateRequest<'_>,
) -> Value {
    json!({
    "AuthBytes": json!({"hex":hex(&value.auth_bytes)}),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn sasl_authenticate_response_v2_sasl_authenticate_response(
    value: &sasl_authenticate_response::v2::SaslAuthenticateResponse<'_>,
) -> Value {
    json!({
    "ErrorCode": json!(&value.error_code),
    "ErrorMessage": value.error_message.as_ref().map(|v| json!(v)),
    "AuthBytes": json!({"hex":hex(&value.auth_bytes)}),
    "SessionLifetimeMs": json!(&value.session_lifetime_ms),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn request_header_v1_request_header(value: &request_header::v1::RequestHeader<'_>) -> Value {
    json!({
    "RequestApiKey": json!(&value.request_api_key),
    "RequestApiVersion": json!(&value.request_api_version),
    "CorrelationId": json!(&value.correlation_id),
    "ClientId": value.client_id.as_ref().map(|v| json!(v)),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn request_header_v2_request_header(value: &request_header::v2::RequestHeader<'_>) -> Value {
    json!({
    "RequestApiKey": json!(&value.request_api_key),
    "RequestApiVersion": json!(&value.request_api_version),
    "CorrelationId": json!(&value.correlation_id),
    "ClientId": value.client_id.as_ref().map(|v| json!(v)),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn response_header_v0_response_header(value: &response_header::v0::ResponseHeader<'_>) -> Value {
    json!({
    "CorrelationId": json!(&value.correlation_id),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
fn response_header_v1_response_header(value: &response_header::v1::ResponseHeader<'_>) -> Value {
    json!({
    "CorrelationId": json!(&value.correlation_id),
    "_unknownTaggedFields": value.unknown_tags.iter().map(|tag| json!({"tag": tag.id, "dataHex": hex(tag.payload)})).collect::<Vec<_>>()
    })
}
#[test]
fn malformed_seeded_inputs_are_bounded_and_never_panic() {
    let limits = DecodeLimits {
        max_bytes: 128,
        max_array_elements: 32,
        max_tags: 16,
        max_depth: 16,
    };
    let mut state = 0x726b_6166_6b61_u64;
    for seed in 0..2048 {
        let mut bytes = [0u8; 128];
        for byte in &mut bytes {
            state ^= state << 13;
            state ^= state >> 7;
            state ^= state << 17;
            *byte = state as u8;
        }
        let bytes = &bytes[..seed % 129];
        let _ = api_versions_request::decode(bytes, 0, limits);
        let _ = api_versions_request::decode(bytes, 3, limits);
        let _ = api_versions_response::decode(bytes, 0, limits);
        let _ = api_versions_response::decode(bytes, 3, limits);
        let _ = metadata_request::decode(bytes, 12, limits);
        let _ = metadata_response::decode(bytes, 12, limits);
        let _ = fetch_request::decode(bytes, 13, limits);
        let _ = fetch_response::decode(bytes, 13, limits);
        let _ = produce_request::decode(bytes, 9, limits);
        let _ = produce_request::decode(bytes, 13, limits);
        let _ = produce_response::decode(bytes, 9, limits);
        let _ = produce_response::decode(bytes, 10, limits);
        let _ = produce_response::decode(bytes, 13, limits);
        let _ = init_producer_id_request::decode(bytes, 4, limits);
        let _ = init_producer_id_response::decode(bytes, 4, limits);
        let _ = sasl_handshake_request::decode(bytes, 1, limits);
        let _ = sasl_handshake_response::decode(bytes, 1, limits);
        let _ = sasl_authenticate_request::decode(bytes, 2, limits);
        let _ = sasl_authenticate_response::decode(bytes, 2, limits);
        let _ = request_header::decode(bytes, 1, limits);
        let _ = request_header::decode(bytes, 2, limits);
        let _ = response_header::decode(bytes, 0, limits);
        let _ = response_header::decode(bytes, 1, limits);
    }
}
