//! Shared plumbing for the JSON trace-artifact generator examples.

use std::error::Error;
use std::io::Write;

use kr_runtime::CompletionCertainty;
use serde::Serialize;

/// A `u64` serialized as a decimal string so JavaScript consumers never
/// round values past `Number.MAX_SAFE_INTEGER`.
#[derive(Clone, Copy)]
pub(crate) struct DecimalU64(pub(crate) u64);

impl Serialize for DecimalU64 {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.collect_str(&self.0)
    }
}

/// Writes `artifact` as a pretty-printed JSON assignment to a global.
///
/// The wrapper names the generating example so the committed data file
/// carries its own regeneration command.
pub(crate) fn write_javascript<W: Write, T: Serialize>(
    mut writer: W,
    example: &str,
    global: &str,
    artifact: &T,
) -> Result<(), Box<dyn Error>> {
    writeln!(
        writer,
        "// Generated by `cargo run -p kr-runtime-trace-tool --example {example}`."
    )?;
    write!(writer, "globalThis.{global} = ")?;
    serde_json::to_writer_pretty(&mut writer, artifact)?;
    writer.write_all(b";\n")?;
    Ok(())
}

/// Names a completion certainty in the stable artifact vocabulary.
///
/// # Panics
///
/// Panics on a certainty variant the artifact schemas do not name yet;
/// artifacts strict-reject unknown vocabulary instead of defaulting.
pub(crate) fn certainty_name(certainty: CompletionCertainty) -> &'static str {
    match certainty {
        CompletionCertainty::NotApplied => "not_applied",
        CompletionCertainty::Applied => "applied",
        CompletionCertainty::MayHaveApplied => "may_have_applied",
        _ => panic!("trace artifact schemas do not support this completion certainty"),
    }
}
