//! Rust emission from the fully resolved, version-free wire layout.
use crate::schema::{
    CompiledMessage, DefaultValue, FieldLayout, FieldType, MessageKind, StructLayout,
};
use std::collections::BTreeSet;
use std::fmt::Write;

/// Generate a deterministic Rust module for the selected messages.
///
/// # Errors
/// Returns an error if Rust identifiers collide or a layout uses an encoding
/// which this backend cannot represent.
pub fn emit(messages: &[CompiledMessage], fingerprint: &str) -> Result<String, String> {
    validate_inputs(messages, fingerprint)?;
    let mut out = String::from("// @generated by kr-kafka-codegen. Do not edit.\n");
    writeln!(out, "// Schema input SHA-256: {fingerprint}").unwrap();
    // Uniform schema-driven expressions are clearer to audit than special cases
    // for every singleton/empty/default combination that these lints prefer.
    out.push_str("#![allow(clippy::derivable_impls, clippy::needless_question_mark, clippy::redundant_closure, clippy::comparison_to_empty, clippy::nonminimal_bool, clippy::needless_borrow, clippy::single_match, clippy::bool_comparison, clippy::field_reassign_with_default, clippy::manual_range_patterns, unused_imports, unused_mut, unused_variables)]\n");
    writeln!(out, "pub const SCHEMA_SHA256: &str = {fingerprint:?};").unwrap();
    for message in messages {
        emit_message(&mut out, message)?;
    }
    Ok(out)
}

// IR structs are public, so the backend must not assume they still contain the
// validated parser output. In particular, never interpolate unchecked names.
fn validate_inputs(messages: &[CompiledMessage], fingerprint: &str) -> Result<(), String> {
    if fingerprint.len() != 64
        || !fingerprint
            .bytes()
            .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
    {
        return Err("schema fingerprint must be 64 lowercase hexadecimal digits".into());
    }
    validate_messages(messages)
}

pub(crate) fn validate_messages(messages: &[CompiledMessage]) -> Result<(), String> {
    let mut modules = BTreeSet::new();
    let mut budget = 100_000_usize;
    for message in messages {
        validate_identifier(&message.name)?;
        match (message.kind, message.api_key) {
            (MessageKind::Request | MessageKind::Response, None) => {
                return Err("request and response IR requires apiKey".into());
            }
            (_, Some(key)) if key < 0 => return Err("IR apiKey cannot be negative".into()),
            (MessageKind::Header | MessageKind::Data, Some(_)) => {
                return Err("header and data IR cannot specify apiKey".into());
            }
            _ => {}
        }
        if !modules.insert(snake(&message.name)) {
            return Err(format!(
                "Rust message module name collision: {}",
                message.name
            ));
        }
        if message.layouts.is_empty() {
            return Err(format!("message {} has no layouts", message.name));
        }
        let mut versions = BTreeSet::new();
        for layout in &message.layouts {
            if layout.versions.is_empty()
                || layout.versions.iter().any(|v| *v < 0)
                || layout.versions.windows(2).any(|p| p[0] >= p[1])
            {
                return Err(format!("invalid layout versions in {}", message.name));
            }
            for version in &layout.versions {
                if !versions.insert(version) {
                    return Err(format!(
                        "duplicate layout version {version} in {}",
                        message.name
                    ));
                }
            }
            if layout.root.name != message.name {
                return Err("layout root does not match message name".into());
            }
            validate_struct(&layout.root, 0, &mut budget)?;
        }
    }
    Ok(())
}

fn validate_identifier(name: &str) -> Result<(), String> {
    if !name.as_bytes().first().is_some_and(u8::is_ascii_alphabetic)
        || !name.bytes().all(|b| b.is_ascii_alphanumeric())
    {
        return Err(format!("invalid Rust schema identifier {name:?}"));
    }
    Ok(())
}

fn validate_struct(st: &StructLayout, depth: usize, budget: &mut usize) -> Result<(), String> {
    if depth > 128 {
        return Err("generated layout nesting exceeds 128".into());
    }
    *budget = budget
        .checked_sub(1 + st.fields.len())
        .ok_or("generated layout size exceeds 100000 nodes")?;
    validate_identifier(&st.name)?;
    if reserved_type_name(&st.name) {
        return Err(format!("reserved generated type name {}", st.name));
    }
    let mut names = BTreeSet::from(["unknown_tags".to_owned()]);
    let mut tags = BTreeSet::new();
    for f in &st.fields {
        validate_identifier(&f.name)?;
        if !names.insert(snake(&f.name)) {
            return Err(format!(
                "Rust field name collision in {}: {}",
                st.name, f.name
            ));
        }
        if let Some(tag) = f.tag {
            if !st.flexible || tag > i32::MAX as u32 || !tags.insert(tag) {
                return Err(format!(
                    "invalid or duplicate tag in {}.{}",
                    st.name, f.name
                ));
            }
            if matches!(f.ty, FieldType::Records) {
                return Err("Kafka does not support tagged records fields".into());
            }
            if matches!(
                f.ty,
                FieldType::String | FieldType::Bytes | FieldType::Array(_)
            ) && !f.compact
            {
                return Err("tagged variable-length fields require compact encoding".into());
            }
        }
        if f.compact
            && (!st.flexible
                || !matches!(
                    f.ty,
                    FieldType::String | FieldType::Bytes | FieldType::Records | FieldType::Array(_)
                ))
        {
            return Err(format!(
                "invalid compact encoding for {}.{}",
                st.name, f.name
            ));
        }
        if f.nullable
            && !matches!(
                f.ty,
                FieldType::String
                    | FieldType::Bytes
                    | FieldType::Records
                    | FieldType::Array(_)
                    | FieldType::Struct(_)
            )
        {
            return Err(format!("invalid nullable type for {}.{}", st.name, f.name));
        }
        validate_default(f)?;
        validate_type(&f.ty, depth + 1, budget)?;
    }
    Ok(())
}

fn validate_type(ty: &FieldType, depth: usize, budget: &mut usize) -> Result<(), String> {
    match ty {
        FieldType::Struct(st) => validate_struct(st, depth, budget),
        FieldType::Array(element) => {
            if matches!(**element, FieldType::Array(_)) {
                return Err("Kafka does not support arrays of arrays".into());
            }
            validate_type(element, depth, budget)
        }
        _ => Ok(()),
    }
}

fn validate_default(f: &FieldLayout) -> Result<(), String> {
    use DefaultValue as D;
    use FieldType as T;
    if matches!(f.ty, T::Records) && !f.nullable {
        return Err("nonnullable records cannot represent Kafka's null constructor default".into());
    }
    let valid = match (&f.ty, &f.default) {
        (_, D::Null) => f.nullable,
        (T::Bool, D::Bool(_))
        | (T::String, D::String(_))
        | (T::Uuid, D::ZeroUuid)
        | (T::Bytes, D::EmptyBytes)
        | (T::Array(_), D::EmptyArray)
        | (T::Struct(_), D::Struct) => true,
        (T::Int8, D::Signed(v)) => i8::try_from(*v).is_ok(),
        (T::Int16, D::Signed(v)) => i16::try_from(*v).is_ok(),
        (T::Int32, D::Signed(v)) => i32::try_from(*v).is_ok(),
        (T::Int64, D::Signed(_)) => true,
        (T::Uint16, D::Unsigned(v)) => u16::try_from(*v).is_ok(),
        (T::Uint32, D::Unsigned(v)) => u32::try_from(*v).is_ok(),
        (T::Float64, D::Float(bits)) => f64::from_bits(*bits).is_finite(),
        _ => false,
    };
    if valid {
        Ok(())
    } else {
        Err(format!("invalid typed default for field {}", f.name))
    }
}

fn reserved_type_name(name: &str) -> bool {
    rust_keyword(name)
        || [
            "Self",
            "Wire",
            "Reader",
            "Writer",
            "Error",
            "Sequence",
            "Records",
            "TaggedFields",
            "SendPlan",
            "Default",
            "Result",
            "Option",
            "Some",
            "None",
            "Ok",
            "Err",
            "alloc",
            "core",
            "bool",
            "char",
            "str",
            "i8",
            "i16",
            "i32",
            "i64",
            "i128",
            "isize",
            "u8",
            "u16",
            "u32",
            "u64",
            "u128",
            "usize",
            "f32",
            "f64",
        ]
        .contains(&name)
}

fn rust_keyword(name: &str) -> bool {
    [
        "type", "match", "ref", "self", "super", "crate", "mod", "loop", "move", "fn", "pub",
        "use", "in", "as", "where", "async", "await", "dyn", "const", "enum", "struct", "impl",
        "trait", "static", "return", "break", "continue", "let", "for", "while", "if", "else",
        "true", "false", "unsafe", "extern", "mut", "box", "do", "final", "macro", "override",
        "priv", "typeof", "unsized", "virtual", "yield", "try", "gen", "abstract", "become",
    ]
    .contains(&name)
}

pub fn snake(name: &str) -> String {
    let chars: Vec<_> = name.chars().collect();
    let mut out = String::new();
    for (i, &c) in chars.iter().enumerate() {
        if c.is_ascii_uppercase()
            && i > 0
            && (chars[i - 1].is_ascii_lowercase()
                || chars[i - 1].is_ascii_digit()
                || chars.get(i + 1).is_some_and(char::is_ascii_lowercase))
        {
            out.push('_');
        }
        out.push(c.to_ascii_lowercase());
    }
    if rust_keyword(&out) {
        out.push('_');
    }
    out
}

fn emit_message(out: &mut String, message: &CompiledMessage) -> Result<(), String> {
    writeln!(out, "pub mod {} {{", snake(&message.name)).unwrap();
    out.push_str("use crate::wire::{Wire, Reader, Writer, Error, DecodeLimits, EncodeLimits};\nuse crate::plan::SendPlan;\n");
    writeln!(
        out,
        "pub const API_KEY: Option<i16> = {:?};",
        message.api_key
    )
    .unwrap();
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub enum Layout {\n");
    for layout in &message.layouts {
        writeln!(out, "V{},", layout.versions[0]).unwrap();
    }
    out.push_str("}\nimpl Layout {\n pub fn for_version(version: i16) -> Result<Self, Error> { match version {\n");
    for layout in &message.layouts {
        writeln!(
            out,
            "{} => Ok(Self::V{}),",
            versions(&layout.versions),
            layout.versions[0]
        )
        .unwrap();
    }
    out.push_str("_ => Err(Error::InvalidValue(\"unsupported message version\")),\n}}}\n");
    out.push_str("#[derive(Debug, Clone)]\npub enum View<'a> {\n");
    for layout in &message.layouts {
        let v = layout.versions[0];
        writeln!(out, "V{v}(v{v}::{}<'a>),", message.name).unwrap();
    }
    out.push_str("}\nimpl<'a> View<'a> {\n");
    out.push_str("pub fn read(r: &mut Reader<'a>, version: i16) -> Result<Self, Error> { match Layout::for_version(version)? {\n");
    for layout in &message.layouts {
        let v = layout.versions[0];
        writeln!(
            out,
            "Layout::V{v} => Ok(Self::V{v}(v{v}::{}::read(r)?)),",
            message.name
        )
        .unwrap();
    }
    out.push_str("}}\npub fn write(&self, w: &mut Writer<'a>, version: i16) -> Result<(), Error> { match (Layout::for_version(version)?, self) {\n");
    for layout in &message.layouts {
        let v = layout.versions[0];
        writeln!(out, "(Layout::V{v}, Self::V{v}(value)) => value.write(w),").unwrap();
    }
    if message.layouts.len() > 1 {
        out.push_str("_ => Err(Error::InvalidValue(\"value belongs to another wire layout\")),\n");
    }
    out.push_str("}}\npub fn plan(&self, version: i16, limits: EncodeLimits) -> Result<SendPlan<'a>, Error> { let mut w = Writer::new(version, false, limits); self.write(&mut w, version)?; w.finish() }\n}\n");
    out.push_str("pub fn decode(bytes: &[u8], version: i16, limits: DecodeLimits) -> Result<View<'_>, Error> { let mut r = Reader::new(bytes, version, false, limits)?; let value = View::read(&mut r, version)?; r.finish()?; Ok(value) }\n");
    for layout in &message.layouts {
        writeln!(out, "pub mod v{} {{", layout.versions[0]).unwrap();
        out.push_str(
            "use crate::wire::{Wire, Reader, Writer, Error, Sequence, Records, TaggedFields};\n",
        );
        out.push_str("#[allow(unused_imports)] use crate::plan::SendPlan;\n");
        let mut structs = Vec::new();
        collect_structs(&layout.root, &mut structs)?;
        for st in structs {
            emit_struct(out, st)?;
        }
        out.push_str("}\n");
    }
    out.push_str("}\n");
    Ok(())
}

fn versions(values: &[i16]) -> String {
    values
        .iter()
        .map(ToString::to_string)
        .collect::<Vec<_>>()
        .join(" | ")
}

fn collect_structs<'a>(
    st: &'a StructLayout,
    out: &mut Vec<&'a StructLayout>,
) -> Result<(), String> {
    if let Some(previous) = out.iter().find(|s| s.name == st.name) {
        if *previous != st {
            return Err(format!("conflicting generated struct {}", st.name));
        }
        return Ok(());
    }
    out.push(st);
    for f in &st.fields {
        collect_type(&f.ty, out)?;
    }
    Ok(())
}
fn collect_type<'a>(ty: &'a FieldType, out: &mut Vec<&'a StructLayout>) -> Result<(), String> {
    match ty {
        FieldType::Struct(st) => collect_structs(st, out),
        FieldType::Array(t) => collect_type(t, out),
        _ => Ok(()),
    }
}
fn rust_type(ty: &FieldType) -> String {
    match ty {
        FieldType::Bool => "bool".into(),
        FieldType::Int8 => "i8".into(),
        FieldType::Int16 => "i16".into(),
        FieldType::Uint16 => "u16".into(),
        FieldType::Int32 => "i32".into(),
        FieldType::Uint32 => "u32".into(),
        FieldType::Int64 => "i64".into(),
        FieldType::Float64 => "f64".into(),
        FieldType::String => "&'a str".into(),
        FieldType::Uuid => "[u8; 16]".into(),
        FieldType::Bytes => "&'a [u8]".into(),
        FieldType::Records => "Records<'a>".into(),
        FieldType::Struct(st) => format!("{}<'a>", st.name),
        FieldType::Array(t) => format!("Sequence<'a, {}>", rust_type(t)),
    }
}
fn default_expr(f: &FieldLayout) -> String {
    let inner = match &f.default {
        DefaultValue::Bool(v) => v.to_string(),
        DefaultValue::Signed(v) => v.to_string(),
        DefaultValue::Unsigned(v) => v.to_string(),
        DefaultValue::Float(v) => format!("f64::from_bits({v})"),
        DefaultValue::String(v) => format!("{v:?}"),
        DefaultValue::ZeroUuid => "[0; 16]".into(),
        DefaultValue::EmptyBytes => "&[]".into(),
        DefaultValue::EmptyArray => "Sequence::from_slice(&[])".into(),
        DefaultValue::Null => return "None".into(),
        DefaultValue::Struct => "Default::default()".into(),
    };
    if f.nullable {
        format!("Some({inner})")
    } else {
        inner
    }
}
fn is_default_expr(f: &FieldLayout, value: &str) -> String {
    match &f.default {
        DefaultValue::EmptyArray | DefaultValue::EmptyBytes => {
            if f.nullable {
                format!("{value}.as_ref().is_some_and(|v| v.is_empty())")
            } else {
                format!("{value}.is_empty()")
            }
        }
        DefaultValue::Struct => {
            if f.nullable {
                format!("{value}.as_ref().is_some_and(Wire::is_default)")
            } else {
                format!("{value}.is_default()")
            }
        }
        DefaultValue::Null => format!("{value}.is_none()"),
        _ => format!("{value} == {}", default_expr(f)),
    }
}
fn emit_struct(out: &mut String, st: &StructLayout) -> Result<(), String> {
    writeln!(
        out,
        "#[derive(Debug, Clone)]\npub struct {}<'a> {{",
        st.name
    )
    .unwrap();
    for f in &st.fields {
        let ty = rust_type(&f.ty);
        writeln!(
            out,
            "pub {}: {},",
            snake(&f.name),
            if f.nullable {
                format!("Option<{ty}>")
            } else {
                ty
            }
        )
        .unwrap();
    }
    out.push_str("pub unknown_tags: TaggedFields<'a>,\n}\n");
    writeln!(
        out,
        "impl Default for {}<'_> {{ fn default() -> Self {{ Self {{",
        st.name
    )
    .unwrap();
    for f in &st.fields {
        writeln!(out, "{}: {},", snake(&f.name), default_expr(f)).unwrap();
    }
    out.push_str("unknown_tags: TaggedFields::default(),\n}}}\n");
    writeln!(out, "impl<'a> Wire<'a> for {}<'a> {{\nfn read(r: &mut Reader<'a>) -> Result<Self, Error> {{ r.with_struct(|r| r.with_flexible({}, |r| {{", st.name, st.flexible).unwrap();
    out.push_str("let mut value = Self::default();\n");
    for f in &st.fields {
        if f.tag.is_none() {
            writeln!(out, "value.{} = {}?;", snake(&f.name), read_expr(f, "r")).unwrap();
        }
    }
    let mut tags: Vec<_> = st.fields.iter().filter(|f| f.tag.is_some()).collect();
    tags.sort_by_key(|f| f.tag);
    if st.flexible {
        out.push_str("let tags = TaggedFields::read(r)?;\n");
        if !tags.is_empty() {
            out.push_str("for tag in tags.iter() { match tag.id {\n");
            for f in &tags {
                writeln!(
                    out,
                    "{} => {{ value.{} = r.with_subreader(tag.payload, |sub| {})?; }},",
                    f.tag.unwrap(),
                    snake(&f.name),
                    read_expr(f, "sub")
                )
                .unwrap();
            }
            out.push_str("_ => {}\n}}\n");
        }
        writeln!(
            out,
            "value.unknown_tags = tags.excluding(&{:?});",
            tags.iter().map(|f| f.tag.unwrap()).collect::<Vec<_>>()
        )
        .unwrap();
    }
    out.push_str("Ok(value)\n}))}\nfn write(&self, w: &mut Writer<'a>) -> Result<(), Error> {\n");
    writeln!(
        out,
        "w.with_struct(|w| w.with_flexible({}, |w| {{",
        st.flexible
    )
    .unwrap();
    if !tags.is_empty() {
        writeln!(out, "for tag in self.unknown_tags.iter() {{ if matches!(tag.id, {}) {{ return Err(Error::InvalidValue(\"unknown tag collides with a schema field\")); }} }}", tags.iter().map(|f| f.tag.unwrap().to_string()).collect::<Vec<_>>().join(" | ")).unwrap();
    }
    for f in &st.fields {
        if f.tag.is_none() {
            writeln!(
                out,
                "{}?;",
                write_expr(f, &format!("self.{}", snake(&f.name)), "w")
            )
            .unwrap();
        }
    }
    if st.flexible {
        if tags.is_empty() {
            out.push_str("w.write_tagged_fields(&self.unknown_tags, &[])?;\n");
        } else {
            out.push_str("let mut known = alloc::vec::Vec::new();\n");
            writeln!(out, "known.try_reserve({}).map_err(|_| Error::InvalidValue(\"tag allocation failed\"))?;", tags.len()).unwrap();
            for f in &tags {
                let value = format!("self.{}", snake(&f.name));
                writeln!(out, "if !({}) {{ let mut sub = w.child_after(&known)?; {}?; known.push(({}, sub.finish()?)); }}", is_default_expr(f, &value), write_expr(f, &value, "&mut sub"), f.tag.unwrap()).unwrap();
            }
            out.push_str("w.write_tagged_fields(&self.unknown_tags, &known)?;\n");
        }
    } else {
        out.push_str("if !self.unknown_tags.is_empty() { return Err(Error::InvalidValue(\"tags in classic layout\")); }\n");
    }
    out.push_str("Ok(())\n}))}\nfn is_default(&self) -> bool { self.unknown_tags.is_empty()\n");
    for f in &st.fields {
        writeln!(
            out,
            "&& ({})",
            is_default_expr(f, &format!("self.{}", snake(&f.name)))
        )
        .unwrap();
    }
    out.push_str("}\n}\n");
    Ok(())
}
fn read_expr(f: &FieldLayout, r: &str) -> String {
    if f.nullable && matches!(f.ty, FieldType::Struct(_)) {
        let (method, null) = if f.tag.is_some() {
            ("read_uvarint", "0")
        } else {
            ("read_i8", "-1")
        };
        return format!(
            "({r}).{method}().and_then(|marker| match marker {{ {null} => Ok(None), 1 => Wire::read({r}).map(Some), _ => Err(Error::InvalidValue(\"invalid nullable struct marker\")) }})"
        );
    }
    let method = match &f.ty {
        FieldType::String => Some("string"),
        FieldType::Bytes => Some("bytes"),
        FieldType::Records => Some("records"),
        _ => None,
    };
    if let Some(method) = method {
        return format!(
            "({r}).with_flexible({}, |r| r.read_{}{method}())",
            f.compact,
            if f.nullable { "nullable_" } else { "" }
        );
    }
    if matches!(f.ty, FieldType::Array(_)) {
        return format!(
            "({r}).with_flexible({}, |r| Sequence::read{}(r))",
            f.compact,
            if f.nullable { "_nullable" } else { "" }
        );
    }
    format!("Wire::read({r})")
}
fn write_expr(f: &FieldLayout, value: &str, w: &str) -> String {
    if f.nullable && matches!(f.ty, FieldType::Struct(_)) {
        let (method, null) = if f.tag.is_some() {
            ("write_uvarint", "0")
        } else {
            ("write_i8", "-1")
        };
        return format!(
            "match {value}.as_ref() {{ None => ({w}).{method}({null}), Some(value) => {{ ({w}).{method}(1)?; value.write({w}) }} }}"
        );
    }
    let method = match &f.ty {
        FieldType::String => Some("string"),
        FieldType::Bytes => Some("bytes"),
        FieldType::Records => Some("records"),
        _ => None,
    };
    if let Some(method) = method {
        let value = if matches!(f.ty, FieldType::Records) {
            if f.nullable {
                format!("{value}.as_ref()")
            } else {
                format!("&{value}")
            }
        } else {
            value.to_string()
        };
        return format!(
            "({w}).with_flexible({}, |w| w.write_{}{method}({value}))",
            f.compact,
            if f.nullable { "nullable_" } else { "" }
        );
    }
    if matches!(f.ty, FieldType::Array(_)) {
        let expr = if f.nullable {
            format!("Sequence::write_nullable({value}.as_ref(), w)")
        } else {
            format!("{value}.write(w)")
        };
        return format!("({w}).with_flexible({}, |w| {expr})", f.compact);
    }
    format!("{value}.write({w})")
}
