//! Java-oracle integration tests emitted alongside the production codecs.
use crate::{
    emit::snake,
    schema::{CompiledMessage, FieldType, StructLayout},
};
use std::fmt::Write;

/// Emits the independent Java-oracle checks for valid resolved layouts.
///
/// # Errors
/// Rejects malformed or unsupported public IR before generating Rust.
pub fn emit(messages: &[CompiledMessage]) -> Result<String, String> {
    crate::emit::validate_messages(messages)?;
    let mut out = String::from(
        "// @generated by kr-kafka-codegen. Do not edit.\n#![allow(clippy::needless_borrow)]\nuse kr_kafka_protocol::{generated::*, wire::{Wire, DecodeLimits, EncodeLimits}};\nuse serde_json::{Value, json};\n",
    );
    out.push_str(r#"
fn hex(bytes: &[u8]) -> String { bytes.iter().map(|b| format!("{b:02x}")).collect() }
fn unhex(text: &str) -> Vec<u8> { assert_eq!(text.len() % 2, 0); (0..text.len()).step_by(2).map(|i| u8::from_str_radix(&text[i..i+2], 16).unwrap()).collect() }
fn uuid(bytes: &[u8; 16]) -> String { let s=hex(bytes); format!("{}-{}-{}-{}-{}", &s[..8], &s[8..12], &s[12..16], &s[16..20], &s[20..]) }
fn check_fields(actual: &Value, expected: &Value) {
 match expected {
  Value::Object(fields) => for (name, value) in fields { let actual = actual.get(name).unwrap_or_else(|| panic!("missing decoded field {name}")); check_fields(actual,value); },
  Value::Array(items) => { let actual=actual.as_array().unwrap(); assert_eq!(actual.len(), items.len()); for (a,e) in actual.iter().zip(items) { check_fields(a,e); } },
  _ => assert_eq!(actual, expected),
 }
}
#[test]
fn fixture_field_oracle_rejects_missing_mutated_and_truncated_values() {
 let expected=json!({"Topics":[{"Name":"topic","Id":7}]});
 for actual in [json!({}),json!({"Topics":[]}),json!({"Topics":[{"Name":"wrong","Id":7}]}),json!({"Topics":[{"Name":"topic"}]})] {
  assert!(std::panic::catch_unwind(|| check_fields(&actual,&expected)).is_err());
 }
 check_fields(&expected,&expected);
}
#[test]
fn java_fixtures_match_fields_defaults_and_wire_bytes_for_every_supported_version() {
 let source: Value=serde_json::from_str(include_str!("fixtures/java-wire.json")).unwrap();
 let cases=source["cases"].as_array().unwrap();
 let mut covered=std::collections::BTreeSet::new();
 for case in cases {
  let name=case["message"].as_str().unwrap(); let version=case["version"].as_i64().unwrap() as i16;
  let bytes=unhex(case["hex"].as_str().unwrap());
  covered.insert((name,version));
  let mut expected = case["fields"].clone();
  // The Java v0 negotiation fixture deliberately populates two fields absent
  // from that wire version. Per-layout Rust types cannot represent them.
  if name == "ApiVersionsRequest" && version == 0 {
    expected.as_object_mut().unwrap().remove("ClientSoftwareName");
    expected.as_object_mut().unwrap().remove("ClientSoftwareVersion");
  }
  let result=std::panic::catch_unwind(|| match name {
"#);
    for message in messages {
        let module = snake(&message.name);
        writeln!(out, "{:?} => {{ let decoded = {module}::decode(&bytes, version, DecodeLimits::default()).unwrap();\n let (fields, is_default, default_bytes) = match &decoded {{", message.name).unwrap();
        for layout in &message.layouts {
            let v = layout.versions[0];
            writeln!(out, "{module}::View::V{v}(value) => {{ let default = {module}::View::V{v}(Default::default()); ({}_v{v}_{}(value), value.is_default(), default.plan(version, EncodeLimits::default()).unwrap().to_vec().unwrap()) }},", module, snake(&layout.root.name)).unwrap();
        }
        out.push_str("};\n check_fields(&fields, &expected);\n if case[\"name\"].as_str().unwrap().ends_with(\"-default\") { assert!(is_default); assert_eq!(default_bytes,bytes); }\n assert_eq!(decoded.plan(version,EncodeLimits::default()).unwrap().to_vec().unwrap(),bytes);\n");
        // Prefix truncation catches nested incomplete elements and tag payloads.
        writeln!(out,"for end in 0..bytes.len() {{ assert!({module}::decode(&bytes[..end],version,DecodeLimits::default()).is_err(), \"accepted prefix {{end}}\"); }}").unwrap();
        writeln!(out,"let mut trailing=bytes.clone(); trailing.push(0); assert!({module}::decode(&trailing,version,DecodeLimits::default()).is_err());\n}},").unwrap();
    }
    out.push_str("_ => panic!(\"unexpected fixture message {name}\"),\n });\n assert!(result.is_ok(), \"fixture {} failed\", case[\"name\"]);\n }\n");
    for message in messages {
        for layout in &message.layouts {
            for v in &layout.versions {
                writeln!(
                    out,
                    "assert!(covered.contains(&({:?},{v})), \"missing Java fixture\");",
                    message.name
                )
                .unwrap();
            }
        }
    }
    out.push_str("}\n");
    for message in messages {
        let module = snake(&message.name);
        for layout in &message.layouts {
            let mut structs = Vec::new();
            collect(&layout.root, &mut structs);
            for st in structs {
                let prefix = format!("{}_v{}", module, layout.versions[0]);
                writeln!(
                    out,
                    "fn {prefix}_{}(value: &{module}::v{}::{}<'_>) -> Value {{ json!({{",
                    snake(&st.name),
                    layout.versions[0],
                    st.name
                )
                .unwrap();
                for field in &st.fields {
                    let value = format!("value.{}", snake(&field.name));
                    let expression = if field.nullable {
                        format!(
                            "{value}.as_ref().map(|v| {})",
                            json_expr(&field.ty, "v", &prefix)
                        )
                    } else {
                        json_expr(&field.ty, &format!("&{value}"), &prefix)
                    };
                    writeln!(out, "{:?}: {expression},", field.name).unwrap();
                }
                out.push_str("\"_unknownTaggedFields\": value.unknown_tags.iter().map(|tag| json!({\"tag\": tag.id, \"dataHex\": hex(tag.payload)})).collect::<Vec<_>>()\n}) }\n");
            }
        }
    }
    out.push_str("#[test]\nfn malformed_seeded_inputs_are_bounded_and_never_panic() {\nlet limits = DecodeLimits { max_bytes: 128, max_array_elements: 32, max_tags: 16, max_depth: 16 };\nlet mut state = 0x726b_6166_6b61_u64;\nfor seed in 0..2048 { let mut bytes = [0u8; 128]; for byte in &mut bytes { state ^= state << 13; state ^= state >> 7; state ^= state << 17; *byte = state as u8; } let bytes = &bytes[..seed % 129];\n");
    for message in messages {
        for layout in &message.layouts {
            writeln!(
                out,
                "let _ = {}::decode(bytes, {}, limits);",
                snake(&message.name),
                layout.versions[0]
            )
            .unwrap();
        }
    }
    out.push_str("}\n}\n");
    Ok(out)
}
fn collect<'a>(st: &'a StructLayout, out: &mut Vec<&'a StructLayout>) {
    if out.iter().any(|s| s.name == st.name) {
        return;
    }
    out.push(st);
    for field in &st.fields {
        collect_type(&field.ty, out);
    }
}
fn collect_type<'a>(ty: &'a FieldType, out: &mut Vec<&'a StructLayout>) {
    match ty {
        FieldType::Struct(st) => collect(st, out),
        FieldType::Array(ty) => collect_type(ty, out),
        _ => {}
    }
}
fn json_expr(ty: &FieldType, value: &str, prefix: &str) -> String {
    match ty {
        FieldType::Struct(st) => format!("{prefix}_{}({value})", snake(&st.name)),
        FieldType::Array(ty) => format!(
            "({value}).iter().map(|item| {{ let item=item.unwrap(); {} }}).collect::<Vec<_>>()",
            json_expr(ty, "&item", prefix)
        ),
        FieldType::Bytes => format!("json!({{\"hex\":hex({value})}})"),
        FieldType::Records => format!(
            "json!({{\"hex\": match {value} {{ kr_kafka_protocol::wire::Records::Borrowed(bytes) => hex(bytes), _ => panic!(\"decoded records must borrow\") }} }})"
        ),
        FieldType::Uuid => format!("uuid({value})"),
        _ => format!("json!({value})"),
    }
}
