//! Explicit tested API registry and body-level version dispatch.
use crate::{
    emit::snake,
    schema::{CompiledMessage, MessageKind},
};
use std::fmt::Write;

/// Emits the tested request/response inventory and header-version rules.
///
/// # Errors
/// Rejects invalid IR, duplicate API keys, and incomplete request/response pairs.
pub fn emit(messages: &[CompiledMessage]) -> Result<String, String> {
    crate::emit::validate_messages(messages)?;
    let mut requests = std::collections::BTreeMap::new();
    let mut responses = std::collections::BTreeMap::new();
    for message in messages {
        let map = match message.kind {
            MessageKind::Request => &mut requests,
            MessageKind::Response => &mut responses,
            _ => continue,
        };
        let key = message.api_key.ok_or("request/response missing API key")?;
        if map.insert(key, message).is_some() {
            return Err(format!("duplicate {:?} API key {key}", message.kind));
        }
    }
    if requests.is_empty() || requests.keys().ne(responses.keys()) {
        return Err("registry requires complete request/response API pairs".into());
    }
    for (key, request) in &requests {
        let versions = |message: &CompiledMessage| {
            message
                .layouts
                .iter()
                .flat_map(|layout| layout.versions.iter().copied())
                .collect::<std::collections::BTreeSet<_>>()
        };
        if versions(request) != versions(responses[key]) {
            return Err(format!(
                "request/response version selection mismatch for API {key}"
            ));
        }
        if *key == 7 && versions(request).contains(&0) {
            return Err("ControlledShutdown v0 requires unsupported request header v0".into());
        }
    }
    let mut out = String::from(
        "// @generated by kr-kafka-codegen. Do not edit.\nuse crate::{generated::*, wire::{Reader, Writer, Error}};\n#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub struct ApiVersion { pub api_key: i16, pub version: i16, pub request_header_version: i16, pub response_header_version: i16 }\npub const SUPPORTED: &[ApiVersion] = &[\n",
    );
    for req in messages.iter().filter(|m| m.kind == MessageKind::Request) {
        let key = req.api_key.ok_or("request missing API key")?;
        let resp = messages
            .iter()
            .find(|m| m.kind == MessageKind::Response && m.api_key == Some(key))
            .ok_or("missing response")?;
        for layout in &req.layouts {
            for v in &layout.versions {
                let response_layout = resp
                    .layouts
                    .iter()
                    .find(|l| l.versions.contains(v))
                    .ok_or("missing response version")?;
                writeln!(out,"ApiVersion {{ api_key: {key}, version: {v}, request_header_version: {}, response_header_version: {} }},",if layout.root.flexible {2} else {1}, if key==18 {0} else {i16::from(response_layout.root.flexible)}).unwrap();
            }
        }
    }
    out.push_str("];\npub fn api_version(api_key: i16, version: i16) -> Result<&'static ApiVersion, Error> { SUPPORTED.iter().find(|v|v.api_key==api_key && v.version==version).ok_or(Error::UnsupportedVersion {api_key,version}) }\n");
    for (kind, name) in [
        (MessageKind::Request, "Request"),
        (MessageKind::Response, "Response"),
    ] {
        let selected: Vec<_> = messages.iter().filter(|m| m.kind == kind).collect();
        writeln!(out, "#[derive(Debug, Clone)]\npub enum {name}<'a> {{").unwrap();
        for m in &selected {
            writeln!(out, "{}({}::View<'a>),", m.name, snake(&m.name)).unwrap();
        }
        writeln!(
            out,
            "}}\nimpl<'a> {name}<'a> {{\npub const fn api_key(&self)->i16 {{ match self {{"
        )
        .unwrap();
        for m in &selected {
            writeln!(out, "Self::{}(_) => {},", m.name, m.api_key.unwrap()).unwrap();
        }
        out.push_str("}}\npub fn read_body(r:&mut Reader<'a>,api_key:i16,version:i16)->Result<Self,Error> { api_version(api_key,version)?; match api_key {\n");
        for m in &selected {
            writeln!(
                out,
                "{} => Ok(Self::{}({}::View::read(r,version)?)),",
                m.api_key.unwrap(),
                m.name,
                snake(&m.name)
            )
            .unwrap();
        }
        out.push_str("_ => Err(Error::UnsupportedVersion { api_key, version }),\n}}\npub fn write_body(&self,w:&mut Writer<'a>,version:i16)->Result<(),Error> { api_version(self.api_key(),version)?; match self {\n");
        for m in &selected {
            writeln!(out, "Self::{}(value) => value.write(w,version),", m.name).unwrap();
        }
        out.push_str("}}\n}\n");
    }
    Ok(out)
}
