use std::error::Error;
use std::fmt;
use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::PathBuf;

use kr_runtime::CompletionCertainty as RuntimeCompletionCertainty;
use kr_runtime_io::storage::test_support::{
    StorageDurabilityTrace, StorageTraceDetail, StorageTraceSnapshot, StorageTraceStep,
    run_storage_durability_trace,
};
use kr_runtime_io::{SimCrashModel, SimOutcome, StorageOperation as RuntimeStorageOperation};
use kr_runtime_ring_trace_wire::WriteBuf;
use kr_runtime_ring_trace_wire::completion_certainty::CompletionCertainty;
use kr_runtime_ring_trace_wire::message_header_codec::ENCODED_LENGTH as MESSAGE_HEADER_LENGTH;
use kr_runtime_ring_trace_wire::session_state::SessionState;
use kr_runtime_ring_trace_wire::storage_operation::StorageOperation;
use kr_runtime_ring_trace_wire::storage_outcome::StorageOutcome;
use kr_runtime_ring_trace_wire::storage_trace_artifact_codec::encoder::StepsEncoder;
use kr_runtime_ring_trace_wire::storage_trace_artifact_codec::{
    SBE_BLOCK_LENGTH, StorageTraceArtifactEncoder,
};

#[path = "support/base64.rs"]
mod base64;

use base64::base64;

const ARTIFACT_SCHEMA_VERSION: u32 = 1;
const MAX_STEPS: usize = 64;
const MAX_PROVENANCE_BYTES: usize = 512;
const MAX_PHASE_BYTES: usize = 64;
const MAX_DESCRIPTION_BYTES: usize = 512;
const MAX_SUMMARY_BYTES: usize = 1_024;
const MAX_DATA_BYTES: usize = 4_096;
const SOURCE_TEST: &str = "io/kr-runtime-io/src/storage/test_support.rs::tests::focused_storage_durability_trace_replays_and_covers_contract_edges";
const PROVIDER: &str = "SimStorage";
const GENERATOR: &str = "cargo run -p kr-runtime-trace-tool --example generate_storage_trace";
const GENERATED_COMMENT: &str =
    "// Generated by `cargo run -p kr-runtime-trace-tool --example generate_storage_trace`.\n";

#[derive(Debug)]
struct GenerateError(String);

impl fmt::Display for GenerateError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.0)
    }
}

impl Error for GenerateError {}

struct EncodedStep<'a> {
    source: &'a StorageTraceStep,
    operation: StorageOperation,
    outcome: StorageOutcome,
    certainty: CompletionCertainty,
    offset: Option<u64>,
    transfer_length: Option<u64>,
    result_length: Option<u64>,
    summary: String,
    request: &'a [u8],
    result: &'a [u8],
}

fn main() -> Result<(), Box<dyn Error>> {
    let destination = std::env::args_os().nth(1).map_or_else(
        || PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("storage-trace-data.js"),
        PathBuf::from,
    );
    let trace = run_storage_durability_trace();
    let bytes = encode_trace(&trace)?;
    let mut output = BufWriter::new(File::create(&destination)?);
    if destination
        .extension()
        .is_some_and(|extension| extension == "sbe")
    {
        output.write_all(&bytes)?;
    } else {
        write_javascript(&mut output, &bytes)?;
    }
    output.flush()?;
    Ok(())
}

fn encode_trace(trace: &StorageDurabilityTrace) -> Result<Vec<u8>, GenerateError> {
    validate_trace(trace)?;
    let steps = trace
        .steps
        .iter()
        .map(EncodedStep::from_source)
        .collect::<Result<Vec<_>, _>>()?;
    let encoded_length = encoded_length(trace, &steps)?;
    let mut bytes = vec![0_u8; encoded_length];
    let encoder = StorageTraceArtifactEncoder::default()
        .wrap(WriteBuf::new(&mut bytes), MESSAGE_HEADER_LENGTH);
    let mut header = encoder.header(0);
    let mut encoder = header
        .parent()
        .map_err(|error| generated_error("artifact header", error))?;
    encoder
        .artifact_schema_version(ARTIFACT_SCHEMA_VERSION)
        .started_at_ns(required_u64(trace.started_at.as_nanos(), "started_at_ns")?)
        .completed_at_ns(required_u64(
            trace.completed_at.as_nanos(),
            "completed_at_ns",
        )?);

    let mut config = encoder.config_encoder();
    config
        .max_file_bytes(exact_usize(trace.config.max_file_bytes, "max_file_bytes")?)
        .max_read_bytes(exact_usize(trace.config.max_read_bytes, "max_read_bytes")?)
        .max_write_bytes(exact_usize(
            trace.config.max_write_bytes,
            "max_write_bytes",
        )?)
        .max_read_chunk(exact_usize(trace.config.max_read_chunk, "max_read_chunk")?)
        .max_write_chunk(exact_usize(
            trace.config.max_write_chunk,
            "max_write_chunk",
        )?)
        .max_in_flight(exact_usize(trace.config.max_in_flight, "max_in_flight")?)
        .max_scripted_faults(exact_usize(
            trace.config.max_scripted_faults,
            "max_scripted_faults",
        )?)
        .default_latency_ns(required_u64(
            trace.config.default_latency.as_nanos(),
            "default_latency_ns",
        )?);
    let encoder = config
        .parent()
        .map_err(|error| generated_error("config", error))?;

    let checkpoint = trace.runtime.determinism_checkpoint();
    let mut runtime = encoder.runtime_encoder();
    runtime
        .reproduction_schema(required_u32(
            trace.runtime.reproduction.schema_version,
            "runtime reproduction schema",
        )?)
        .checkpoint_schema(required_u32(
            checkpoint.schema_version,
            "runtime checkpoint schema",
        )?)
        .rng_version(required_u32(
            trace.runtime.reproduction.rng_version,
            "runtime RNG version",
        )?)
        .stopped(u8::from(trace.runtime.stopped))
        .seed(required_u64(trace.seed, "runtime seed")?)
        .now_ns(required_u64(trace.runtime.now.as_nanos(), "runtime now")?)
        .total_steps(required_u64(
            trace.runtime.total_steps,
            "runtime total steps",
        )?)
        .next_enqueue_sequence(required_u64(
            trace.runtime.next_enqueue_sequence,
            "runtime next enqueue sequence",
        )?)
        .next_timer_sequence(required_u64(
            trace.runtime.next_timer_sequence,
            "runtime next timer sequence",
        )?)
        .next_timer_id(required_u64(
            trace.runtime.next_timer_id,
            "runtime next timer ID",
        )?)
        .ready_tasks(exact_usize(trace.runtime.ready_tasks, "ready_tasks")?)
        .live_timers(exact_usize(trace.runtime.live_timers, "live_timers")?)
        .live_tasks(exact_usize(trace.runtime.tasks.len(), "live_tasks")?);
    let encoder = runtime
        .parent()
        .map_err(|error| generated_error("runtime", error))?;

    let count = u16::try_from(steps.len())
        .map_err(|_| GenerateError("storage step count does not fit u16".into()))?;
    let mut group = encoder.steps_encoder(count, StepsEncoder::default());
    for step in &steps {
        if group
            .advance()
            .map_err(|error| generated_error("steps", error))?
            .is_none()
        {
            return Err(GenerateError("generated steps group ended early".into()));
        }
        group
            .sequence(required_u32(step.source.sequence, "step sequence")?)
            .started_at_ns(required_u64(
                step.source.started_at.as_nanos(),
                "step start time",
            )?)
            .completed_at_ns(required_u64(
                step.source.completed_at.as_nanos(),
                "step completion time",
            )?)
            .operation(step.operation)
            .outcome(step.outcome)
            .certainty(step.certainty)
            .offset_opt(step.offset)
            .transfer_length_opt(step.transfer_length)
            .result_length_opt(step.result_length);

        let mut before = group.before_encoder();
        encode_status(&mut before, &step.source.before)?;
        let group_after_before = before
            .parent()
            .map_err(|error| generated_error("before status", error))?;
        let mut after = group_after_before.after_encoder();
        encode_status(&mut after, &step.source.after)?;
        let mut group_after_status = after
            .parent()
            .map_err(|error| generated_error("after status", error))?;
        group_after_status
            .phase(step.source.phase)
            .description(step.source.description)
            .summary(&step.summary)
            .request_bytes(step.request)
            .result_bytes(step.result)
            .accepted_bytes_before(&step.source.before.image.accepted)
            .durable_bytes_before(&step.source.before.image.durable)
            .accepted_bytes_after(&step.source.after.image.accepted)
            .durable_bytes_after(&step.source.after.image.durable);
        group = group_after_status;
    }
    if group
        .advance()
        .map_err(|error| generated_error("steps", error))?
        .is_some()
    {
        return Err(GenerateError(
            "generated steps group has extra entries".into(),
        ));
    }
    let mut encoder = group
        .parent()
        .map_err(|error| generated_error("steps", error))?;
    encoder
        .scenario(trace.scenario)
        .source_test(SOURCE_TEST)
        .provider(PROVIDER)
        .generator(GENERATOR);
    let actual_length = MESSAGE_HEADER_LENGTH + encoder.encoded_length();
    if actual_length != encoded_length {
        return Err(GenerateError(format!(
            "encoded storage artifact length {actual_length} disagrees with preflight {encoded_length}"
        )));
    }
    Ok(bytes)
}

fn encode_status<'a, P>(
    encoder: &mut kr_runtime_ring_trace_wire::storage_status_snapshot_codec::StorageStatusSnapshotEncoder<
        P,
    >,
    snapshot: &StorageTraceSnapshot,
) -> Result<(), GenerateError>
where
    P: kr_runtime_ring_trace_wire::Writer<'a> + Default,
{
    encoder
        .session(if snapshot.status.closed {
            SessionState::Closed
        } else {
            SessionState::Open
        })
        .accepted_len(required_u64(
            snapshot.status.accepted_len,
            "status.accepted_len",
        )?)
        .durable_len(required_u64(
            snapshot.status.durable_len,
            "status.durable_len",
        )?)
        .fsync_gate_version(required_u32(
            snapshot.status.fsync_gate_version,
            "status.fsync_gate_version",
        )?)
        .has_fsync_gated_data(u8::from(snapshot.status.has_fsync_gated_data))
        .in_flight(exact_usize(snapshot.status.in_flight, "status.in_flight")?)
        .in_flight_limit(exact_usize(
            snapshot.status.in_flight_limit,
            "status.in_flight_limit",
        )?)
        .pending_faults(exact_usize(
            snapshot.status.pending_faults,
            "status.pending_faults",
        )?)
        .fault_hits(required_u64(
            snapshot.status.fault_hits,
            "status.fault_hits",
        )?)
        .closed(u8::from(snapshot.status.closed));
    Ok(())
}

impl<'a> EncodedStep<'a> {
    fn from_source(source: &'a StorageTraceStep) -> Result<Self, GenerateError> {
        let encoded = match &source.detail {
            StorageTraceDetail::WriteCompleted(observation) => Self {
                source,
                operation: StorageOperation::WriteAt,
                outcome: StorageOutcome::Success,
                certainty: CompletionCertainty::NotApplicable,
                offset: Some(observation.request.offset),
                transfer_length: Some(exact_usize(
                    observation.result.bytes_written,
                    "write bytes_written",
                )?),
                result_length: Some(exact_usize(
                    observation.result.buffer.len(),
                    "write result buffer length",
                )?),
                summary: format!(
                    "wrote {} byte(s) at offset {}",
                    observation.result.bytes_written, observation.request.offset
                ),
                request: &observation.request.buffer,
                result: &observation.result.buffer,
            },
            StorageTraceDetail::FaultInjected { fault } => Self {
                source,
                operation: StorageOperation::ScriptFault,
                outcome: StorageOutcome::Success,
                certainty: CompletionCertainty::NotApplicable,
                offset: None,
                transfer_length: None,
                result_length: None,
                summary: format!(
                    "scripted {} {} after {}ns",
                    runtime_operation_name(fault.operation),
                    sim_outcome_name(fault.outcome),
                    fault.delay.as_nanos()
                ),
                request: &[],
                result: &[],
            },
            StorageTraceDetail::SyncFailed { certainty, error } => Self {
                source,
                operation: StorageOperation::Sync,
                outcome: StorageOutcome::Failed,
                certainty: encode_certainty(*certainty)?,
                offset: None,
                transfer_length: None,
                result_length: None,
                summary: error.to_string(),
                request: &[],
                result: &[],
            },
            StorageTraceDetail::Crashed { model } => Self {
                source,
                operation: StorageOperation::Crash,
                outcome: StorageOutcome::Crash,
                certainty: CompletionCertainty::NotApplicable,
                offset: None,
                transfer_length: None,
                result_length: None,
                summary: format!("crashed using {}", crash_model_name(*model)?),
                request: &[],
                result: &[],
            },
            StorageTraceDetail::Reopened => Self {
                source,
                operation: StorageOperation::Reopen,
                outcome: StorageOutcome::Recovered,
                certainty: CompletionCertainty::NotApplicable,
                offset: None,
                transfer_length: None,
                result_length: None,
                summary: "reopened from durable bytes".into(),
                request: &[],
                result: &[],
            },
            StorageTraceDetail::SyncCompleted { result } => Self {
                source,
                operation: StorageOperation::Sync,
                outcome: StorageOutcome::Success,
                certainty: CompletionCertainty::NotApplicable,
                offset: None,
                transfer_length: None,
                result_length: Some(result.durable_len),
                summary: format!("synced {} durable byte(s)", result.durable_len),
                request: &[],
                result: &[],
            },
            StorageTraceDetail::ReadCompleted(observation) => Self {
                source,
                operation: StorageOperation::ReadAt,
                outcome: StorageOutcome::Success,
                certainty: CompletionCertainty::NotApplicable,
                offset: Some(observation.request.offset),
                transfer_length: Some(exact_usize(
                    observation.result.bytes_read,
                    "read bytes_read",
                )?),
                result_length: Some(exact_usize(
                    observation.result.buffer.len(),
                    "read result buffer length",
                )?),
                summary: format!(
                    "read {} byte(s) at offset {}",
                    observation.result.bytes_read, observation.request.offset
                ),
                request: &observation.request.buffer,
                result: &observation.result.buffer,
            },
            _ => {
                return Err(GenerateError(format!(
                    "artifact schema {ARTIFACT_SCHEMA_VERSION} does not support storage detail {source:?}"
                )));
            }
        };
        encoded.validate()?;
        Ok(encoded)
    }

    fn validate(&self) -> Result<(), GenerateError> {
        bounded_text(self.source.phase, MAX_PHASE_BYTES, "step phase")?;
        bounded_text(
            self.source.description,
            MAX_DESCRIPTION_BYTES,
            "step description",
        )?;
        bounded_text(&self.summary, MAX_SUMMARY_BYTES, "step summary")?;
        bounded_bytes(self.request, "step request bytes")?;
        bounded_bytes(self.result, "step result bytes")?;
        bounded_bytes(
            &self.source.before.image.accepted,
            "accepted bytes before step",
        )?;
        bounded_bytes(
            &self.source.before.image.durable,
            "durable bytes before step",
        )?;
        bounded_bytes(
            &self.source.after.image.accepted,
            "accepted bytes after step",
        )?;
        bounded_bytes(&self.source.after.image.durable, "durable bytes after step")?;
        for (name, value) in [
            ("offset", self.offset),
            ("transfer length", self.transfer_length),
            ("result length", self.result_length),
        ] {
            if value == Some(u64::MAX) {
                return Err(GenerateError(format!(
                    "{name} collides with the SBE optional-u64 null value"
                )));
            }
        }
        Ok(())
    }
}

fn validate_trace(trace: &StorageDurabilityTrace) -> Result<(), GenerateError> {
    if trace.steps.is_empty() || trace.steps.len() > MAX_STEPS {
        return Err(GenerateError(format!(
            "storage step count {} is outside 1..={MAX_STEPS}",
            trace.steps.len()
        )));
    }
    if trace.seed != trace.runtime.reproduction.config.seed {
        return Err(GenerateError(
            "scenario seed disagrees with runtime reproduction".into(),
        ));
    }
    if trace.started_at > trace.completed_at || trace.completed_at != trace.runtime.now {
        return Err(GenerateError(
            "scenario and terminal runtime times are inconsistent".into(),
        ));
    }
    if trace.initial != trace.steps[0].before
        || trace.terminal != trace.steps[trace.steps.len() - 1].after
    {
        return Err(GenerateError(
            "scenario endpoints disagree with the step history".into(),
        ));
    }
    for (index, step) in trace.steps.iter().enumerate() {
        if usize::try_from(step.sequence).ok() != Some(index) {
            return Err(GenerateError(format!(
                "step {index} has noncanonical sequence {}",
                step.sequence
            )));
        }
        if step.started_at > step.completed_at
            || step.started_at != step.before.runtime.now
            || step.completed_at != step.after.runtime.now
        {
            return Err(GenerateError(format!(
                "step {index} has inconsistent virtual time"
            )));
        }
        if index > 0 && trace.steps[index - 1].after != step.before {
            return Err(GenerateError(format!(
                "step {index} is discontinuous from its predecessor"
            )));
        }
        validate_snapshot(&step.before, "before")?;
        validate_snapshot(&step.after, "after")?;
    }
    for (name, value) in [
        ("scenario", trace.scenario),
        ("source test", SOURCE_TEST),
        ("provider", PROVIDER),
        ("generator", GENERATOR),
    ] {
        bounded_text(value, MAX_PROVENANCE_BYTES, name)?;
    }
    Ok(())
}

fn validate_snapshot(snapshot: &StorageTraceSnapshot, position: &str) -> Result<(), GenerateError> {
    if snapshot.status.accepted_len
        != u64::try_from(snapshot.image.accepted.len())
            .map_err(|_| GenerateError(format!("{position} accepted length does not fit u64")))?
        || snapshot.status.durable_len
            != u64::try_from(snapshot.image.durable.len())
                .map_err(|_| GenerateError(format!("{position} durable length does not fit u64")))?
    {
        return Err(GenerateError(format!(
            "{position} status lengths disagree with retained bytes"
        )));
    }
    Ok(())
}

fn encoded_length(
    trace: &StorageDurabilityTrace,
    steps: &[EncodedStep<'_>],
) -> Result<usize, GenerateError> {
    let mut length = MESSAGE_HEADER_LENGTH
        .checked_add(usize::from(SBE_BLOCK_LENGTH))
        .and_then(|length| length.checked_add(4))
        .ok_or_else(|| GenerateError("storage artifact fixed length overflowed".into()))?;
    for step in steps {
        length = length
            .checked_add(usize::from(
                StepsEncoder::<StorageTraceArtifactEncoder<'_>>::block_length(),
            ))
            .ok_or_else(|| GenerateError("storage step fixed length overflowed".into()))?;
        for value_length in [
            step.source.phase.len(),
            step.source.description.len(),
            step.summary.len(),
            step.request.len(),
            step.result.len(),
            step.source.before.image.accepted.len(),
            step.source.before.image.durable.len(),
            step.source.after.image.accepted.len(),
            step.source.after.image.durable.len(),
        ] {
            length = length
                .checked_add(2)
                .and_then(|length| length.checked_add(value_length))
                .ok_or_else(|| GenerateError("storage step variable length overflowed".into()))?;
        }
    }
    for value in [trace.scenario, SOURCE_TEST, PROVIDER, GENERATOR] {
        length = length
            .checked_add(2)
            .and_then(|length| length.checked_add(value.len()))
            .ok_or_else(|| GenerateError("storage provenance length overflowed".into()))?;
    }
    Ok(length)
}

fn bounded_text(value: &str, maximum: usize, name: &str) -> Result<(), GenerateError> {
    if value.len() > maximum {
        return Err(GenerateError(format!(
            "{name} is {} bytes; maximum is {maximum}",
            value.len()
        )));
    }
    Ok(())
}

fn bounded_bytes(value: &[u8], name: &str) -> Result<(), GenerateError> {
    if value.len() > MAX_DATA_BYTES {
        return Err(GenerateError(format!(
            "{name} is {} bytes; maximum is {MAX_DATA_BYTES}",
            value.len()
        )));
    }
    Ok(())
}

fn exact_usize(value: usize, name: &str) -> Result<u64, GenerateError> {
    let value =
        u64::try_from(value).map_err(|_| GenerateError(format!("{name} does not fit u64")))?;
    required_u64(value, name)
}

fn required_u64(value: u64, name: &str) -> Result<u64, GenerateError> {
    if value == u64::MAX {
        return Err(GenerateError(format!(
            "{name} collides with the SBE required-u64 null value"
        )));
    }
    Ok(value)
}

fn required_u32(value: u32, name: &str) -> Result<u32, GenerateError> {
    if value == u32::MAX {
        return Err(GenerateError(format!(
            "{name} collides with the SBE required-u32 null value"
        )));
    }
    Ok(value)
}

fn encode_certainty(
    certainty: RuntimeCompletionCertainty,
) -> Result<CompletionCertainty, GenerateError> {
    match certainty {
        RuntimeCompletionCertainty::NotApplied => Ok(CompletionCertainty::NotApplied),
        RuntimeCompletionCertainty::Applied => Ok(CompletionCertainty::Applied),
        RuntimeCompletionCertainty::MayHaveApplied => Ok(CompletionCertainty::MayHaveApplied),
        _ => Err(GenerateError(format!(
            "artifact schema {ARTIFACT_SCHEMA_VERSION} does not support completion certainty"
        ))),
    }
}

fn runtime_operation_name(operation: RuntimeStorageOperation) -> &'static str {
    match operation {
        RuntimeStorageOperation::ReadAt => "read_at",
        RuntimeStorageOperation::WriteAt => "write_at",
        RuntimeStorageOperation::SetLen => "set_len",
        RuntimeStorageOperation::Len => "len",
        RuntimeStorageOperation::Sync => "sync",
    }
}

fn sim_outcome_name(outcome: SimOutcome) -> &'static str {
    match outcome {
        SimOutcome::Success => "success",
        SimOutcome::FailBefore => "fail_before",
        SimOutcome::FailAfter => "fail_after",
        SimOutcome::MayHaveAppliedBefore => "may_have_applied_before",
        SimOutcome::MayHaveAppliedAfter => "may_have_applied_after",
    }
}

fn crash_model_name(model: SimCrashModel) -> Result<&'static str, GenerateError> {
    match model {
        SimCrashModel::CleanRollback => Ok("clean_rollback"),
        SimCrashModel::FoundationDbLikeV1 => Ok("foundationdb_like_v1"),
        _ => Err(GenerateError(format!(
            "artifact schema {ARTIFACT_SCHEMA_VERSION} does not support this crash model"
        ))),
    }
}

fn generated_error(context: &str, error: impl fmt::Debug) -> GenerateError {
    GenerateError(format!("generated {context} codec failed: {error:?}"))
}

fn write_javascript<W: Write>(mut writer: W, bytes: &[u8]) -> Result<(), std::io::Error> {
    writer.write_all(GENERATED_COMMENT.as_bytes())?;
    writer.write_all(b"globalThis.STORAGE_TRACE_DATA = \"")?;
    writer.write_all(base64(bytes).as_bytes())?;
    writer.write_all(b"\";\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use kr_runtime_ring_trace_wire::message_header_codec::MessageHeaderDecoder;
    use kr_runtime_ring_trace_wire::storage_trace_artifact_codec::{
        SBE_TEMPLATE_ID, StorageTraceArtifactDecoder,
    };
    use kr_runtime_ring_trace_wire::{ReadBuf, SBE_SCHEMA_ID, SBE_SCHEMA_VERSION};

    #[derive(Debug)]
    struct DecodedStep {
        phase: String,
        operation: StorageOperation,
        outcome: StorageOutcome,
        certainty: CompletionCertainty,
        before_closed: bool,
        after_closed: bool,
        accepted_before: Vec<u8>,
        durable_before: Vec<u8>,
        accepted_after: Vec<u8>,
        durable_after: Vec<u8>,
        result: Vec<u8>,
    }

    #[test]
    fn generated_storage_trace_is_deterministic_and_covers_milestones() {
        let first = encode_trace(&run_storage_durability_trace()).expect("first trace encodes");
        let repeated = encode_trace(&run_storage_durability_trace()).expect("trace repeats");
        assert_eq!(first, repeated);

        let mut wrapper = Vec::new();
        write_javascript(&mut wrapper, &first).expect("wrapper renders");
        let wrapper = std::str::from_utf8(&wrapper).expect("wrapper is UTF-8");
        assert!(wrapper.starts_with(GENERATED_COMMENT));
        assert!(wrapper.ends_with("\";\n"));

        let header = MessageHeaderDecoder::default().wrap(ReadBuf::new(&first), 0);
        assert_eq!(header.block_length(), SBE_BLOCK_LENGTH);
        assert_eq!(header.template_id(), SBE_TEMPLATE_ID);
        assert_eq!(header.schema_id(), SBE_SCHEMA_ID);
        assert_eq!(header.version(), SBE_SCHEMA_VERSION);
        let decoder = StorageTraceArtifactDecoder::default().header(header, 0);
        assert_eq!(decoder.artifact_schema_version(), ARTIFACT_SCHEMA_VERSION);
        assert_eq!(decoder.started_at_ns(), 0);
        assert_eq!(decoder.completed_at_ns(), 32);

        let mut config = decoder.config_decoder();
        assert_eq!(config.max_file_bytes(), 32);
        assert_eq!(config.default_latency_ns(), 5);
        let decoder = config.parent().expect("config parent is present");
        let mut runtime = decoder.runtime_decoder();
        assert!(runtime.stopped() != 0);
        assert_eq!(runtime.seed(), 0x7374_6f72_6167_6501);
        let decoder = runtime.parent().expect("runtime parent is present");
        let mut group = decoder.steps_decoder();
        assert_eq!(group.count(), 11);
        let mut steps = Vec::new();
        while group.advance().expect("steps decode").is_some() {
            let operation = group.operation();
            let outcome = group.outcome();
            let certainty = group.certainty();
            let mut before = group.before_decoder();
            let before_closed = before.closed() != 0;
            let group_after_before = before.parent().expect("before parent is present");
            let mut after = group_after_before.after_decoder();
            let after_closed = after.closed() != 0;
            let mut group_after_status = after.parent().expect("after parent is present");
            let phase_coordinates = group_after_status.phase_decoder();
            let phase = std::str::from_utf8(group_after_status.phase_slice(phase_coordinates))
                .expect("phase is UTF-8")
                .to_owned();
            let description = group_after_status.description_decoder();
            let _ = group_after_status.description_slice(description);
            let summary = group_after_status.summary_decoder();
            let _ = group_after_status.summary_slice(summary);
            let request = group_after_status.request_bytes_decoder();
            let _ = group_after_status.request_bytes_slice(request);
            let result = group_after_status.result_bytes_decoder();
            let result = group_after_status.result_bytes_slice(result).to_vec();
            let accepted_before = group_after_status.accepted_bytes_before_decoder();
            let accepted_before = group_after_status
                .accepted_bytes_before_slice(accepted_before)
                .to_vec();
            let durable_before = group_after_status.durable_bytes_before_decoder();
            let durable_before = group_after_status
                .durable_bytes_before_slice(durable_before)
                .to_vec();
            let accepted_after = group_after_status.accepted_bytes_after_decoder();
            let accepted_after = group_after_status
                .accepted_bytes_after_slice(accepted_after)
                .to_vec();
            let durable_after = group_after_status.durable_bytes_after_decoder();
            let durable_after = group_after_status
                .durable_bytes_after_slice(durable_after)
                .to_vec();
            steps.push(DecodedStep {
                phase,
                operation,
                outcome,
                certainty,
                before_closed,
                after_closed,
                accepted_before,
                durable_before,
                accepted_after,
                durable_after,
                result,
            });
            group = group_after_status;
        }
        let mut decoder = group.parent().expect("steps parent is present");
        let scenario = decoder.scenario_decoder();
        assert_eq!(
            decoder.scenario_slice(scenario),
            b"ambiguous_sync_clean_crash_durable_recovery"
        );
        let source_test = decoder.source_test_decoder();
        assert_eq!(
            decoder.source_test_slice(source_test),
            SOURCE_TEST.as_bytes()
        );
        let provider = decoder.provider_decoder();
        assert_eq!(decoder.provider_slice(provider), PROVIDER.as_bytes());
        let generator = decoder.generator_decoder();
        assert_eq!(decoder.generator_slice(generator), GENERATOR.as_bytes());
        assert_eq!(
            MESSAGE_HEADER_LENGTH + decoder.encoded_length(),
            first.len()
        );

        let ambiguous = steps
            .iter()
            .find(|step| {
                step.phase == "ambiguous-sync"
                    && step.operation == StorageOperation::Sync
                    && step.outcome == StorageOutcome::Failed
            })
            .expect("ambiguous sync step");
        assert_eq!(ambiguous.certainty, CompletionCertainty::MayHaveApplied);
        assert_eq!(ambiguous.accepted_after, b"BASE-dirty");
        assert_eq!(ambiguous.durable_after, b"BASE");

        let rollback = steps
            .iter()
            .find(|step| {
                step.phase == "rollback"
                    && step.operation == StorageOperation::Crash
                    && step.outcome == StorageOutcome::Crash
            })
            .expect("rollback crash step");
        assert!(!rollback.before_closed);
        assert!(rollback.after_closed);
        assert_eq!(rollback.accepted_before, b"BASE-dirty");
        assert_eq!(rollback.accepted_after, rollback.durable_after);

        let recovered = steps
            .iter()
            .find(|step| {
                step.phase == "rollback"
                    && step.operation == StorageOperation::Reopen
                    && step.outcome == StorageOutcome::Recovered
            })
            .expect("reopen step");
        assert!(recovered.before_closed);
        assert!(!recovered.after_closed);
        assert_eq!(recovered.accepted_after, recovered.durable_after);

        let final_read = steps.last().expect("final step");
        assert_eq!(final_read.operation, StorageOperation::ReadAt);
        assert_eq!(final_read.result, b"BASE-kept");
        assert_eq!(final_read.accepted_after, b"BASE-kept");
        assert_eq!(final_read.durable_before, b"BASE-kept");
    }
}
