use std::error::Error;
use std::fs;
use std::path::Path;

use kr_runtime_trace_tool::{
    SBE_ARTIFACT_CONTAINER_VERSION, SUPPORTED_TRACE_SCHEMA_VERSION, TRACE_ARTIFACT_SCHEMA_VERSION,
    TraceArtifactMetadata, validate_sbe_trace_artifact, write_sampled_buffered_sbe_trace_artifact,
    write_sampled_sbe_trace_artifact,
};

#[path = "support/base64.rs"]
mod base64;
#[path = "../src/browser_sbe_fixture.rs"]
mod browser_sbe_fixture;
#[path = "support/browser_sbe_sample.rs"]
mod browser_sbe_sample;

use base64::base64;

const GOLDEN_STEM: &str = "browser-sbe-c1-s1v1-a8-t5";
const SAMPLE_MODULE: &str = "dst-trace-sample.js";

fn current_golden_stem() -> String {
    format!(
        "browser-sbe-c{}-s{}v{}-a{}-t{}",
        SBE_ARTIFACT_CONTAINER_VERSION,
        kr_runtime_trace_wire::SBE_SCHEMA_ID,
        kr_runtime_trace_wire::SBE_SCHEMA_VERSION,
        TRACE_ARTIFACT_SCHEMA_VERSION,
        SUPPORTED_TRACE_SCHEMA_VERSION,
    )
}

fn main() -> Result<(), Box<dyn Error>> {
    assert_eq!(
        current_golden_stem(),
        GOLDEN_STEM,
        "schema coordinates changed; rename the version-labelled golden before regenerating",
    );
    let fixture = browser_sbe_fixture::browser_sbe_fixture();
    let (trace, sampling) = fixture.buffered_trace();
    let mut binary = Vec::new();
    write_sampled_buffered_sbe_trace_artifact(
        &mut binary,
        &trace,
        &sampling,
        &fixture.snapshot,
        TraceArtifactMetadata::new(browser_sbe_fixture::DRIVER, browser_sbe_fixture::OUTCOME),
    )?;
    validate_sbe_trace_artifact(binary.as_slice())?;

    let (typed, typed_sampling) = fixture.typed_trace();
    let mut typed_binary = Vec::new();
    write_sampled_sbe_trace_artifact(
        &mut typed_binary,
        &typed,
        &typed_sampling,
        &fixture.snapshot,
        TraceArtifactMetadata::new(browser_sbe_fixture::DRIVER, browser_sbe_fixture::OUTCOME),
    )?;
    validate_sbe_trace_artifact(typed_binary.as_slice())?;

    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("testdata")
        .join(format!("{GOLDEN_STEM}.sbe"));
    fs::write(&path, &binary)?;
    println!("wrote {} bytes to {}", binary.len(), path.display());

    let sample_binary = browser_sbe_sample::build_browser_sbe_sample()?;
    let sample_path = Path::new(env!("CARGO_MANIFEST_DIR")).join(SAMPLE_MODULE);
    fs::write(&sample_path, sample_module(&sample_binary))?;
    println!("wrote embedded browser sample to {}", sample_path.display());
    Ok(())
}

fn sample_module(binary: &[u8]) -> String {
    format!(
        "// Generated by generate_browser_sbe_goldens.rs. Do not edit.\n\"use strict\";\n\nglobalThis.DstTraceSample = Object.freeze({{\n  base64: \"{}\",\n}});\n",
        base64(binary)
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn current_runtime_sample_is_deterministic_and_valid() {
        let first =
            browser_sbe_sample::build_browser_sbe_sample().expect("coherent browser sample builds");
        let repeated =
            browser_sbe_sample::build_browser_sbe_sample().expect("runtime sample repeats");
        assert_eq!(first, repeated);
        validate_sbe_trace_artifact(first.as_slice()).expect("runtime sample validates");

        let module = sample_module(&first);
        assert!(module.starts_with("// Generated by generate_browser_sbe_goldens.rs."));
        assert!(module.contains("globalThis.DstTraceSample = Object.freeze({"));
        assert!(module.ends_with("});\n"));
    }
}
